var dir_5a871cc4f02fc52ef95b8f24978ae614 =
[
    [ "checks.ts", "checks_8ts.html", null ],
    [ "cleanup.test.ts", "cleanup_8test_8ts.html", null ],
    [ "cleanup.ts", "cleanup_8ts.html", null ],
    [ "deepMerge.test.ts", "deep_merge_8test_8ts.html", null ],
    [ "deepMerge.ts", "deep_merge_8ts.html", null ],
    [ "dialogScopeUtils.ts", "dialog_scope_utils_8ts.html", null ],
    [ "envVarResolver.test.ts", "env_var_resolver_8test_8ts.html", null ],
    [ "envVarResolver.ts", "env_var_resolver_8ts.html", null ],
    [ "errors.ts", "cli_2src_2utils_2errors_8ts.html", null ],
    [ "events.ts", "events_8ts.html", null ],
    [ "gitUtils.test.ts", "git_utils_8test_8ts.html", null ],
    [ "gitUtils.ts", "cli_2src_2utils_2git_utils_8ts.html", null ],
    [ "handleAutoUpdate.test.ts", "handle_auto_update_8test_8ts.html", null ],
    [ "handleAutoUpdate.ts", "handle_auto_update_8ts.html", null ],
    [ "installationInfo.test.ts", "installation_info_8test_8ts.html", null ],
    [ "installationInfo.ts", "installation_info_8ts.html", null ],
    [ "package.ts", "package_8ts.html", null ],
    [ "readStdin.test.ts", "read_stdin_8test_8ts.html", null ],
    [ "readStdin.ts", "read_stdin_8ts.html", null ],
    [ "resolvePath.ts", "resolve_path_8ts.html", null ],
    [ "sandbox.ts", "sandbox_8ts.html", null ],
    [ "settingsUtils.test.ts", "settings_utils_8test_8ts.html", null ],
    [ "settingsUtils.ts", "settings_utils_8ts.html", null ],
    [ "spawnWrapper.ts", "spawn_wrapper_8ts.html", null ],
    [ "startupWarnings.test.ts", "startup_warnings_8test_8ts.html", null ],
    [ "startupWarnings.ts", "startup_warnings_8ts.html", null ],
    [ "updateEventEmitter.ts", "update_event_emitter_8ts.html", null ],
    [ "userStartupWarnings.test.ts", "user_startup_warnings_8test_8ts.html", null ],
    [ "userStartupWarnings.ts", "user_startup_warnings_8ts.html", null ],
    [ "version.ts", "version_8ts.html", null ]
];