var dir_b36a919b85e0be1518ef47e828905137 =
[
    [ "clipboardUtils.test.ts", "clipboard_utils_8test_8ts.html", null ],
    [ "clipboardUtils.ts", "clipboard_utils_8ts.html", null ],
    [ "commandUtils.test.ts", "command_utils_8test_8ts.html", null ],
    [ "commandUtils.ts", "command_utils_8ts.html", null ],
    [ "computeStats.test.ts", "compute_stats_8test_8ts.html", null ],
    [ "computeStats.ts", "compute_stats_8ts.html", null ],
    [ "ConsolePatcher.ts", "_console_patcher_8ts.html", null ],
    [ "displayUtils.test.ts", "display_utils_8test_8ts.html", null ],
    [ "displayUtils.ts", "display_utils_8ts.html", null ],
    [ "formatters.test.ts", "formatters_8test_8ts.html", null ],
    [ "formatters.ts", "cli_2src_2ui_2utils_2formatters_8ts.html", null ],
    [ "highlight.test.ts", "highlight_8test_8ts.html", null ],
    [ "highlight.ts", "highlight_8ts.html", null ],
    [ "isNarrowWidth.ts", "is_narrow_width_8ts.html", null ],
    [ "kittyProtocolDetector.ts", "kitty_protocol_detector_8ts.html", null ],
    [ "markdownUtilities.test.ts", "markdown_utilities_8test_8ts.html", null ],
    [ "markdownUtilities.ts", "markdown_utilities_8ts.html", null ],
    [ "platformConstants.ts", "platform_constants_8ts.html", null ],
    [ "terminalSetup.ts", "terminal_setup_8ts.html", null ],
    [ "textUtils.ts", "cli_2src_2ui_2utils_2text_utils_8ts.html", null ],
    [ "updateCheck.test.ts", "update_check_8test_8ts.html", null ],
    [ "updateCheck.ts", "update_check_8ts.html", null ]
];