var searchData=
[
  ['核心事件类型_0',['核心事件类型',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md882',1,'']]],
  ['核心函数_1',['核心函数',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md587',1,'核心函数'],['../md_packages_2core_2src_2core_2prompts.html#autotoc_md610',1,'核心函数'],['../md_packages_2core_2src_2core_2token_limits.html#autotoc_md620',1,'核心函数'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md802',1,'核心函数'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md854',1,'核心函数'],['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1029',1,'核心函数'],['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1043',1,'核心函数']]],
  ['核心功能_2',['核心功能',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md181',1,'核心功能'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md801',1,'核心功能'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md850',1,'核心功能']]],
  ['核心变量_3',['核心变量',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md851',1,'']]],
  ['核心实现_4',['核心实现',['../md_packages_2core_2src_2services_2file_system_service.html#autotoc_md730',1,'']]],
  ['核心属性_5',['核心属性',['../md_packages_2core_2src_2config_2config.html#autotoc_md516',1,'']]],
  ['核心指令_6',['核心指令',['../md_packages_2core_2src_2core_2prompts.html#autotoc_md615',1,'']]],
  ['核心接口和类_7',['核心接口和类',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md988',1,'']]],
  ['核心接口_8',['核心接口',['../md_packages_2core_2src_2services_2file_system_service.html#autotoc_md728',1,'']]],
  ['核心数据结构_9',['核心数据结构',['../md_packages_2core_2src_2services_2chat_recording_service.html#autotoc_md714',1,'核心数据结构'],['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md744',1,'核心数据结构']]],
  ['核心方法_10',['核心方法',['../md_packages_2core_2src_2config_2config.html#autotoc_md521',1,'核心方法'],['../md_packages_2core_2src_2core_2client.html#autotoc_md575',1,'核心方法'],['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md584',1,'核心方法'],['../md_packages_2core_2src_2core_2gemini_chat.html#autotoc_md592',1,'核心方法'],['../md_packages_2core_2src_2core_2logger.html#autotoc_md601',1,'核心方法'],['../md_packages_2core_2src_2core_2turn.html#autotoc_md628',1,'核心方法'],['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md646',1,'核心方法'],['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md672',1,'核心方法'],['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md695',1,'核心方法'],['../md_packages_2core_2src_2services_2chat_recording_service.html#autotoc_md718',1,'核心方法'],['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md747',1,'核心方法']]],
  ['核心模块说明_11',['核心模块说明',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md177',1,'']]],
  ['核心组件_12',['核心组件',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md486',1,'核心组件'],['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md643',1,'核心组件'],['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md670',1,'核心组件'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md765',1,'核心组件'],['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md915',1,'核心组件'],['../md_packages_2core_2src_2tools_2edit.html#autotoc_md941',1,'核心组件'],['../md_packages_2core_2src_2tools_2read-file.html#autotoc_md952',1,'核心组件'],['../md_packages_2core_2src_2tools_2shell.html#autotoc_md962',1,'核心组件']]]
];
