var searchData=
[
  ['safejsonstringify_2etest_2ets_0',['safeJsonStringify.test.ts',['../safe_json_stringify_8test_8ts.html',1,'']]],
  ['safejsonstringify_2ets_1',['safeJsonStringify.ts',['../safe_json_stringify_8ts.html',1,'']]],
  ['sandbox_2ets_2',['sandbox.ts',['../sandbox_8ts.html',1,'']]],
  ['sandboxcliargs_3',['SandboxCliArgs',['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html#autotoc_md335',1,'']]],
  ['sandboxconfig_4',['SandboxConfig',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md544',1,'']]],
  ['sandboxconfig_20ts_5',['sandboxConfig.ts',['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html',1,'']]],
  ['sandboxconfig_2ets_6',['sandboxConfig.ts',['../sandbox_config_8ts.html',1,'']]],
  ['sandboxconfig_2ets_2emd_7',['sandboxConfig.ts.md',['../sandbox_config_8ts_8md.html',1,'']]],
  ['save_8',['save',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md131',1,'<span class="tt">save</span>'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md136',1,'<span class="tt">save</span>']]],
  ['savesettings_20settingsfile_3a_20settingsfile_20_3a_20void_9',['saveSettings(settingsFile: SettingsFile): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md349',1,'']]],
  ['scheduletoolcalls_20测试_10',['scheduleToolCalls 测试',['../md_packages_2a2a-server_2src_2agent_2task_8test_8ts.html#autotoc_md36',1,'']]],
  ['schema_20definitions_11',['3.2 Schema Definitions',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md8',1,'']]],
  ['schema_20management_12',['Schema Management',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md979',1,'']]],
  ['schema_2ets_13',['schema.ts',['../schema_8ts.html',1,'']]],
  ['schemavalidator_2ets_14',['schemaValidator.ts',['../schema_validator_8ts.html',1,'']]],
  ['scope_3a_20settingscope_20cwd_3a_20string_20process_20cwd_15',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['scope_3a_20string_16',['removeMcpServer(name: string, options: { scope: string })',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'']]],
  ['scopes_3a_20settingscope_17',['enableExtension(name: string, scopes: SettingScope[])',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'']]],
  ['screen_20reader_20guidance_18',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]],
  ['sdk_19',['SDK',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md784',1,'OpenTelemetry SDK'],['../md_packages_2core_2src_2telemetry_2sdk_8ts.html',1,'Telemetry SDK']]],
  ['sdk_20',['sdk',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md852',1,'']]],
  ['sdk_20functions_21',['SDK Functions',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md793',1,'']]],
  ['sdk_20sdk_20ts_22',['遥测 SDK (sdk.ts)',['../md_packages_2core_2src_2telemetry_2sdk.html',1,'']]],
  ['sdk_20ts_23',['遥测 SDK (sdk.ts)',['../md_packages_2core_2src_2telemetry_2sdk.html',1,'']]],
  ['sdk_2emd_24',['sdk.md',['../sdk_8md.html',1,'']]],
  ['sdk_2etest_2ets_25',['sdk.test.ts',['../sdk_8test_8ts.html',1,'']]],
  ['sdk_2ets_26',['sdk.ts',['../sdk_8ts.html',1,'']]],
  ['sdk_2ets_2emd_27',['sdk.ts.md',['../sdk_8ts_8md.html',1,'']]],
  ['secure_2dbrowser_2dlauncher_2etest_2ets_28',['secure-browser-launcher.test.ts',['../secure-browser-launcher_8test_8ts.html',1,'']]],
  ['secure_2dbrowser_2dlauncher_2ets_29',['secure-browser-launcher.ts',['../secure-browser-launcher_8ts.html',1,'']]],
  ['semantic_2dcolors_2ets_30',['semantic-colors.ts',['../semantic-colors_8ts.html',1,'']]],
  ['semantic_2dtokens_2ets_31',['semantic-tokens.ts',['../semantic-tokens_8ts.html',1,'']]],
  ['semanticresourceattributes_32',['SemanticResourceAttributes',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md864',1,'']]],
  ['separation_20of_20concerns_33',['4. Separation of Concerns',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md10',1,'']]],
  ['server_34',['Gemini CLI A2A Server',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md16',1,'']]],
  ['server_20integration_35',['MCP Server Integration',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md983',1,'']]],
  ['server_20ts_36',['server.ts',['../md_packages_2a2a-server_2src_2http_2server_8ts.html',1,'']]],
  ['server_2etest_2ets_37',['server.test.ts',['../server_8test_8ts.html',1,'']]],
  ['server_2ets_38',['server.ts',['../a2a-server_2src_2http_2server_8ts.html',1,'(Global Namespace)'],['../core_2src_2code__assist_2server_8ts.html',1,'(Global Namespace)']]],
  ['server_2ets_2emd_39',['server.ts.md',['../server_8ts_8md.html',1,'']]],
  ['server_3a_20mcpserverconfig_20_3a_20promise_40',['getServerStatus(serverName: string, server: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'']]],
  ['servergeministreamevent_41',['ServerGeminiStreamEvent',['../md_packages_2core_2src_2core_2turn.html#autotoc_md633',1,'']]],
  ['servername_3a_20string_20config_3a_20mcpserverconfig_20_3a_20promise_42',['testMCPConnection(serverName: string, config: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'']]],
  ['servername_3a_20string_20server_3a_20mcpserverconfig_20_3a_20promise_43',['getServerStatus(serverName: string, server: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'']]],
  ['service_20and_20privacy_20notice_44',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['service_20name_45',['Service Name',['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md760',1,'']]],
  ['service_5fname_46',['SERVICE_NAME',['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md761',1,'']]],
  ['session_2ets_47',['session.ts',['../session_8ts.html',1,'']]],
  ['sessionid_20argv_20cwd_48',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['settargetdir_20函数_49',['setTargetDir 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md56',1,'']]],
  ['settings_50',['Settings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md344',1,'']]],
  ['settings_20接口_51',['Settings 接口',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md71',1,'']]],
  ['settings_20_3a_20promise_52',['parseArguments(settings: Settings): Promise&amp;lt;CliArgs&amp;gt;',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md282',1,'']]],
  ['settings_20_3a_20void_53',['loadEnvironment(settings: Settings): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md355',1,'']]],
  ['settings_20extensions_20sessionid_20argv_20cwd_54',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['settings_20startupwarnings_20workspaceroot_20initializationresult_55',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['settings_20ts_56',['settings ts',['../md_packages_2cli_2src_2config_2settings_8ts.html',1,'settings.ts'],['../md_packages_2a2a-server_2src_2config_2settings_8ts.html',1,'src/config/settings.ts']]],
  ['settings_2etest_2ets_57',['settings.test.ts',['../settings_8test_8ts.html',1,'']]],
  ['settings_2ets_58',['settings.ts',['../a2a-server_2src_2config_2settings_8ts.html',1,'(Global Namespace)'],['../cli_2src_2config_2settings_8ts.html',1,'(Global Namespace)']]],
  ['settings_2ets_2emd_59',['settings.ts.md',['../a2a-server_2src_2config_2settings_8ts_8md.html',1,'(Global Namespace)'],['../cli_2src_2config_2settings_8ts_8md.html',1,'(Global Namespace)']]],
  ['settings_3a_20loadedsettings_20_3a_20promise_60',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['settings_3a_20record_20_3a_20boolean_61',['needsMigration(settings: Record&amp;lt;string, unknown&amp;gt;): boolean',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md350',1,'']]],
  ['settings_3a_20settings_20_3a_20promise_62',['parseArguments(settings: Settings): Promise&amp;lt;CliArgs&amp;gt;',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md282',1,'']]],
  ['settings_3a_20settings_20_3a_20void_63',['loadEnvironment(settings: Settings): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md355',1,'']]],
  ['settingscommand_2etest_2ets_64',['settingsCommand.test.ts',['../settings_command_8test_8ts.html',1,'']]],
  ['settingscommand_2ets_65',['settingsCommand.ts',['../settings_command_8ts.html',1,'']]],
  ['settingscope_66',['SettingScope',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'enableExtension(name: string, scopes: SettingScope[])'],['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md346',1,'SettingScope']]],
  ['settingscope_20cwd_3a_20string_20process_20cwd_67',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['settingserror_20接口_68',['SettingsError 接口',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md72',1,'']]],
  ['settingsfile_20_3a_20void_69',['saveSettings(settingsFile: SettingsFile): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md349',1,'']]],
  ['settingsfile_3a_20settingsfile_20_3a_20void_70',['saveSettings(settingsFile: SettingsFile): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md349',1,'']]],
  ['settingsschema_2etest_2ets_71',['settingsSchema.test.ts',['../settings_schema_8test_8ts.html',1,'']]],
  ['settingsschema_2ets_72',['settingsSchema.ts',['../settings_schema_8ts.html',1,'']]],
  ['settingsutils_2etest_2ets_73',['settingsUtils.test.ts',['../settings_utils_8test_8ts.html',1,'']]],
  ['settingsutils_2ets_74',['settingsUtils.ts',['../settings_utils_8ts.html',1,'']]],
  ['setup_75',['Core Test Setup',['../md_packages_2core_2test-setup_8ts.html',1,'']]],
  ['setup_20ts_76',['test-setup.ts',['../md_packages_2cli_2test-setup_8ts.html',1,'']]],
  ['setup_2etest_2ets_77',['setup.test.ts',['../setup_8test_8ts.html',1,'']]],
  ['setup_2ets_78',['setup.ts',['../setup_8ts.html',1,'']]],
  ['setupcloudshellenvironment_20envfilepath_3a_20string_20null_20_3a_20void_79',['setUpCloudShellEnvironment(envFilePath: string | null): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md357',1,'']]],
  ['setupgithubcommand_2etest_2ets_80',['setupGithubCommand.test.ts',['../setup_github_command_8test_8ts.html',1,'']]],
  ['setupgithubcommand_2ets_81',['setupGithubCommand.ts',['../setup_github_command_8ts.html',1,'']]],
  ['setupunhandledrejectionhandler_82',['setupUnhandledRejectionHandler()',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md386',1,'']]],
  ['shades_2dof_2dpurple_2ets_83',['shades-of-purple.ts',['../shades-of-purple_8ts.html',1,'']]],
  ['shell_20执行服务_20shellexecutionservice_84',['Shell 执行服务 (ShellExecutionService)',['../md_packages_2core_2src_2services_2shell_execution_service.html',1,'']]],
  ['shell_2dutils_2etest_2ets_85',['shell-utils.test.ts',['../shell-utils_8test_8ts.html',1,'']]],
  ['shell_2dutils_2ets_86',['shell-utils.ts',['../shell-utils_8ts.html',1,'']]],
  ['shell_2emd_87',['shell.md',['../shell_8md.html',1,'']]],
  ['shell_2etest_2ets_88',['shell.test.ts',['../shell_8test_8ts.html',1,'']]],
  ['shell_2ets_89',['shell.ts',['../shell_8ts.html',1,'']]],
  ['shell_5fspecial_5fchars_90',['SHELL_SPECIAL_CHARS',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1050',1,'']]],
  ['shellcommandprocessor_2etest_2ets_91',['shellCommandProcessor.test.ts',['../shell_command_processor_8test_8ts.html',1,'']]],
  ['shellcommandprocessor_2ets_92',['shellCommandProcessor.ts',['../shell_command_processor_8ts.html',1,'']]],
  ['shellexecutionresult_93',['ShellExecutionResult',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md745',1,'']]],
  ['shellexecutionservice_94',['Shell 执行服务 (ShellExecutionService)',['../md_packages_2core_2src_2services_2shell_execution_service.html',1,'']]],
  ['shellexecutionservice_2emd_95',['shellExecutionService.md',['../shell_execution_service_8md.html',1,'']]],
  ['shellexecutionservice_2etest_2ets_96',['shellExecutionService.test.ts',['../shell_execution_service_8test_8ts.html',1,'']]],
  ['shellexecutionservice_2ets_97',['shellExecutionService.ts',['../shell_execution_service_8ts.html',1,'']]],
  ['shelloutputevent_98',['ShellOutputEvent',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md746',1,'']]],
  ['shellprocessor_2etest_2ets_99',['shellProcessor.test.ts',['../shell_processor_8test_8ts.html',1,'']]],
  ['shellprocessor_2ets_100',['shellProcessor.ts',['../shell_processor_8ts.html',1,'']]],
  ['shelltool_20类_101',['ShellTool 类',['../md_packages_2core_2src_2tools_2shell.html',1,'ShellTool 类'],['../md_packages_2core_2src_2tools_2shell.html#autotoc_md964',1,'ShellTool 类']]],
  ['shelltoolinvocation_20类_102',['ShellToolInvocation 类',['../md_packages_2core_2src_2tools_2shell.html#autotoc_md965',1,'']]],
  ['shelltoolparams_20接口_103',['ShellToolParams 接口',['../md_packages_2core_2src_2tools_2shell.html#autotoc_md963',1,'']]],
  ['shortenpath_104',['路径缩短 (shortenPath)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1052',1,'']]],
  ['shouldconfirmexecute_105',['确认函数 (shouldConfirmExecute)',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md925',1,'']]],
  ['shouldloguserprompts_106',['shouldLogUserPrompts',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md826',1,'shouldLogUserPrompts'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md812',1,'shouldLogUserPrompts()']]],
  ['shutdowntelemetry_107',['shutdownTelemetry',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md876',1,'shutdownTelemetry'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md768',1,'shutdownTelemetry()'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md856',1,'shutdownTelemetry()']]],
  ['simulation_108',['429 Simulation',['../md_packages_2core_2test-setup_8ts.html#autotoc_md1059',1,'']]],
  ['slashcommandevent_109',['SlashCommandEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md894',1,'']]],
  ['slashcommandprocessor_2etest_2ets_110',['slashCommandProcessor.test.ts',['../slash_command_processor_8test_8ts.html',1,'']]],
  ['slashcommandprocessor_2ets_111',['slashCommandProcessor.ts',['../slash_command_processor_8ts.html',1,'']]],
  ['slashcommandstatus_112',['SlashCommandStatus',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md909',1,'']]],
  ['smart_2dedit_2etest_2ets_113',['smart-edit.test.ts',['../smart-edit_8test_8ts.html',1,'']]],
  ['smart_2dedit_2ets_114',['smart-edit.ts',['../smart-edit_8ts.html',1,'']]],
  ['spawnwrapper_2ets_115',['spawnWrapper.ts',['../spawn_wrapper_8ts.html',1,'']]],
  ['specific_20paths_116',['Project-Specific Paths',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md571',1,'']]],
  ['src_20agent_20executor_20ts_117',['src/agent/executor.ts',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html',1,'']]],
  ['src_20agent_20task_20ts_118',['src/agent/task.ts',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html',1,'']]],
  ['src_20config_20config_20ts_119',['src/config/config.ts',['../md_packages_2a2a-server_2src_2config_2config_8ts.html',1,'']]],
  ['src_20config_20extension_20ts_120',['src/config/extension.ts',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html',1,'']]],
  ['src_20config_20settings_20ts_121',['src/config/settings.ts',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html',1,'']]],
  ['src_20http_20app_20ts_122',['src/http/app.ts',['../md_packages_2a2a-server_2src_2http_2app_8ts.html',1,'']]],
  ['src_20http_20requeststorage_20ts_123',['src/http/requestStorage.ts',['../md_packages_2a2a-server_2src_2http_2request_storage_8ts.html',1,'']]],
  ['src_20index_20ts_124',['src/index.ts',['../md_packages_2a2a-server_2src_2index_8ts.html',1,'']]],
  ['src_20persistence_20gcs_20ts_125',['src/persistence/gcs.ts',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html',1,'']]],
  ['src_20types_20ts_126',['src/types.ts',['../md_packages_2a2a-server_2src_2types_8ts.html',1,'']]],
  ['src_20utils_20logger_20ts_127',['src/utils/logger.ts',['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html',1,'']]],
  ['sse_128',['sse',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md239',1,'']]],
  ['standardfilesystemservice_20类_129',['StandardFileSystemService 类',['../md_packages_2core_2src_2services_2file_system_service.html#autotoc_md731',1,'']]],
  ['startdir_3a_20string_20_3a_20string_20null_130',['findEnvFile(startDir: string): string | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'']]],
  ['startinteractiveui_20config_20settings_20startupwarnings_20workspaceroot_20initializationresult_131',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['startsessionevent_132',['StartSessionEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md883',1,'']]],
  ['startupwarnings_20workspaceroot_20initializationresult_133',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['startupwarnings_2etest_2ets_134',['startupWarnings.test.ts',['../startup_warnings_8test_8ts.html',1,'']]],
  ['startupwarnings_2ets_135',['startupWarnings.ts',['../startup_warnings_8ts.html',1,'']]],
  ['static_20methods_136',['Static Methods',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md568',1,'']]],
  ['statscommand_2etest_2ets_137',['statsCommand.test.ts',['../stats_command_8test_8ts.html',1,'']]],
  ['statscommand_2ets_138',['statsCommand.ts',['../stats_command_8ts.html',1,'']]],
  ['stdio（默认）_139',['stdio（默认）',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md238',1,'']]],
  ['stdioconfig_140',['StdioConfig',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md661',1,'']]],
  ['storage_20class_141',['Storage Class',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md567',1,'']]],
  ['storage_20management_142',['Storage Management',['../md_packages_2core_2src_2config_2storage_8ts.html',1,'']]],
  ['storage_2etest_2ets_143',['storage.test.ts',['../storage_8test_8ts.html',1,'']]],
  ['storage_2ets_144',['storage.ts',['../storage_8ts.html',1,'']]],
  ['storage_2ets_2emd_145',['storage.ts.md',['../storage_8ts_8md.html',1,'']]],
  ['streameventtype_20枚举_146',['StreamEventType 枚举',['../md_packages_2core_2src_2core_2gemini_chat.html#autotoc_md597',1,'']]],
  ['string_147',['string',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'getNodeMemoryArgs(config: Config): string[]'],['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md385',1,'relaunchWithAdditionalArgs(additionalArgs: string[])'],['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'removeMcpServer(name: string, options: { scope: string })'],['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['string_20_3a_20extension_148',['loadExtensionsFromDir(dir: string): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'']]],
  ['string_20_3a_20extension_20null_149',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['string_20_3a_20promise_150',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['string_20_3a_20string_20null_151',['findEnvFile(startDir: string): string | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'']]],
  ['string_20config_3a_20mcpserverconfig_20_3a_20promise_152',['testMCPConnection(serverName: string, config: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'']]],
  ['string_20cwd_3a_20string_20process_20cwd_20_3a_20promise_153',['uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'']]],
  ['string_20null_154',['findEnvFile(startDir: string): string | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'']]],
  ['string_20null_20_3a_20void_155',['setUpCloudShellEnvironment(envFilePath: string | null): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md357',1,'']]],
  ['string_20options_3a_20scope_3a_20string_156',['removeMcpServer(name: string, options: { scope: string })',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'']]],
  ['string_20process_20cwd_157',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['string_20process_20cwd_20_3a_20extension_158',['loadExtensions(workspaceDir: string = process.cwd()): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'']]],
  ['string_20process_20cwd_20_3a_20loadedsettings_159',['loadSettings(workspaceDir: string = process.cwd()): LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'']]],
  ['string_20process_20cwd_20_3a_20promise_160',['string process cwd : Promise',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]],
  ['string_20prompt_5fid_3a_20string_20_3a_20promise_161',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['string_20scope_3a_20settingscope_20cwd_3a_20string_20process_20cwd_162',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['string_20scopes_3a_20settingscope_163',['enableExtension(name: string, scopes: SettingScope[])',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'']]],
  ['string_20server_3a_20mcpserverconfig_20_3a_20promise_164',['getServerStatus(serverName: string, server: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'']]],
  ['string_20undefined_20_3a_20dnsresolutionorder_165',['validateDnsResolutionOrder(order: string | undefined): DnsResolutionOrder',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md383',1,'']]],
  ['subagent_2etest_2ets_166',['subagent.test.ts',['../subagent_8test_8ts.html',1,'']]],
  ['subagent_2ets_167',['subagent.ts',['../subagent_8ts.html',1,'']]],
  ['summarizer_2etest_2ets_168',['summarizer.test.ts',['../summarizer_8test_8ts.html',1,'']]],
  ['summarizer_2ets_169',['summarizer.ts',['../summarizer_8ts.html',1,'']]],
  ['summarizetooloutputsettings_170',['SummarizeToolOutputSettings',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md542',1,'']]],
  ['systemencoding_2etest_2ets_171',['systemEncoding.test.ts',['../system_encoding_8test_8ts.html',1,'']]],
  ['systemencoding_2ets_172',['systemEncoding.ts',['../system_encoding_8ts.html',1,'']]]
];
