var searchData=
[
  ['debugging_0',['Debugging',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md878',1,'']]],
  ['declarativetool_1',['DeclarativeTool',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1009',1,'']]],
  ['declarativetool_20抽象类_2',['DeclarativeTool 抽象类',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md991',1,'']]],
  ['decodetagname_3',['decodeTagName()',['../md_packages_2core_2src_2core_2logger.html#autotoc_md608',1,'']]],
  ['deepmerge_2etest_2ets_4',['deepMerge.test.ts',['../deep_merge_8test_8ts.html',1,'']]],
  ['deepmerge_2ets_5',['deepMerge.ts',['../deep_merge_8ts.html',1,'']]],
  ['default_20models_6',['Default Models',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md557',1,'']]],
  ['default_20values_7',['Default Values',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md791',1,'']]],
  ['default_2dlight_2ets_8',['default-light.ts',['../default-light_8ts.html',1,'']]],
  ['default_2ets_9',['default.ts',['../default_8ts.html',1,'']]],
  ['default_5fdiff_5foptions_10',['DEFAULT_DIFF_OPTIONS',['../md_packages_2core_2src_2tools_2diff_options_8ts.html#autotoc_md936',1,'']]],
  ['default_5fexcluded_5fenv_5fvars_11',['DEFAULT_EXCLUDED_ENV_VARS',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md361',1,'']]],
  ['default_5fgemini_5fembedding_5fmodel_12',['DEFAULT_GEMINI_EMBEDDING_MODEL',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md561',1,'']]],
  ['default_5fgemini_5fflash_5flite_5fmodel_13',['DEFAULT_GEMINI_FLASH_LITE_MODEL',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md560',1,'']]],
  ['default_5fgemini_5fflash_5fmodel_14',['DEFAULT_GEMINI_FLASH_MODEL',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md559',1,'']]],
  ['default_5fgemini_5fmodel_15',['DEFAULT_GEMINI_MODEL',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md558',1,'']]],
  ['default_5fthinking_5fmode_16',['DEFAULT_THINKING_MODE',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md563',1,'']]],
  ['default_5ftoken_5flimit_17',['DEFAULT_TOKEN_LIMIT',['../md_packages_2core_2src_2core_2token_limits.html#autotoc_md623',1,'']]],
  ['defaultkeybindings_18',['defaultKeyBindings',['../md_packages_2cli_2src_2config_2key_bindings_8ts.html#autotoc_md326',1,'']]],
  ['defaults_19',['Defaults',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md550',1,'File Filtering Defaults'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md551',1,'Truncation Defaults']]],
  ['definitions_20',['Definitions',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md8',1,'3.2 Schema Definitions'],['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md9',1,'3.3 Method Definitions'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md552',1,'Type Definitions'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md797',1,'Type Definitions'],['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1011',1,'Type Definitions']]],
  ['dependencies_21',['Dependencies',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md877',1,'Dependencies'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md986',1,'Dependencies']]],
  ['detect_2dide_2etest_2ets_22',['detect-ide.test.ts',['../detect-ide_8test_8ts.html',1,'']]],
  ['detect_2dide_2ets_23',['detect-ide.ts',['../detect-ide_8ts.html',1,'']]],
  ['development_24',['Local Development',['../md_packages_2vscode-ide-companion_2development.html',1,'']]],
  ['development_25',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['development_20tool_20extension_26',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['development_20tool_20extension_27',['3. The &lt;span class=&quot;tt&quot;&gt;development-tool&lt;/span&gt; extension',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md6',1,'']]],
  ['development_2dextension_2drfc_2emd_28',['development-extension-rfc.md',['../development-extension-rfc_8md.html',1,'']]],
  ['development_2emd_29',['development.md',['../development_8md.html',1,'']]],
  ['dialogscopeutils_2ets_30',['dialogScopeUtils.ts',['../dialog_scope_utils_8ts.html',1,'']]],
  ['diff_20options_20utility_31',['Diff Options Utility',['../md_packages_2core_2src_2tools_2diff_options_8ts.html',1,'']]],
  ['diff_2dmanager_2ets_32',['diff-manager.ts',['../diff-manager_8ts.html',1,'']]],
  ['diffoptions_2etest_2ets_33',['diffOptions.test.ts',['../diff_options_8test_8ts.html',1,'']]],
  ['diffoptions_2ets_34',['diffOptions.ts',['../diff_options_8ts.html',1,'']]],
  ['diffoptions_2ets_2emd_35',['diffOptions.ts.md',['../diff_options_8ts_8md.html',1,'']]],
  ['diffstat_36',['DiffStat',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1014',1,'']]],
  ['diffupdateresult_37',['DiffUpdateResult',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md660',1,'']]],
  ['dir_3a_20string_20_3a_20extension_38',['loadExtensionsFromDir(dir: string): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'']]],
  ['directory_20and_20file_20names_39',['Directory and File Names',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md566',1,'']]],
  ['directory_20paths_40',['Global Directory Paths',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md569',1,'']]],
  ['disable_2ets_41',['disable.ts',['../disable_8ts.html',1,'']]],
  ['disablecommand_42',['disableCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md205',1,'']]],
  ['disableextension_20name_3a_20string_20scope_3a_20settingscope_20cwd_3a_20string_20process_20cwd_43',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['disconnect_44',['disconnect()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md651',1,'']]],
  ['discoveredtool_45',['DiscoveredTool',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md975',1,'']]],
  ['discoveredtoolinvocation_46',['DiscoveredToolInvocation',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md974',1,'']]],
  ['discovery_47',['Discovery',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md982',1,'Dynamic Tool Discovery'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md978',1,'Tool Discovery']]],
  ['displayutils_2etest_2ets_48',['displayUtils.test.ts',['../display_utils_8test_8ts.html',1,'']]],
  ['displayutils_2ets_49',['displayUtils.ts',['../display_utils_8ts.html',1,'']]],
  ['dnsresolutionorder_50',['validateDnsResolutionOrder(order: string | undefined): DnsResolutionOrder',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md383',1,'']]],
  ['docscommand_2etest_2ets_51',['docsCommand.test.ts',['../docs_command_8test_8ts.html',1,'']]],
  ['docscommand_2ets_52',['docsCommand.ts',['../docs_command_8ts.html',1,'']]],
  ['dracula_2ets_53',['dracula.ts',['../dracula_8ts.html',1,'']]],
  ['dynamic_20tool_20discovery_54',['Dynamic Tool Discovery',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md982',1,'']]]
];
