var searchData=
[
  ['oauth_20发现_0',['OAuth 发现',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md677',1,'']]],
  ['oauth_20提供者_20mcpoauthprovider_1',['MCP OAuth 提供者 (MCPOAuthProvider)',['../md_packages_2core_2src_2mcp_2oauth-provider.html',1,'']]],
  ['oauth_2dcredential_2dstorage_2etest_2ets_2',['oauth-credential-storage.test.ts',['../oauth-credential-storage_8test_8ts.html',1,'']]],
  ['oauth_2dcredential_2dstorage_2ets_3',['oauth-credential-storage.ts',['../oauth-credential-storage_8ts.html',1,'']]],
  ['oauth_2dprovider_2emd_4',['oauth-provider.md',['../oauth-provider_8md.html',1,'']]],
  ['oauth_2dprovider_2etest_2ets_5',['oauth-provider.test.ts',['../oauth-provider_8test_8ts.html',1,'']]],
  ['oauth_2dprovider_2ets_6',['oauth-provider.ts',['../oauth-provider_8ts.html',1,'']]],
  ['oauth_2dtoken_2dstorage_2etest_2ets_7',['oauth-token-storage.test.ts',['../oauth-token-storage_8test_8ts.html',1,'']]],
  ['oauth_2dtoken_2dstorage_2ets_8',['oauth-token-storage.ts',['../oauth-token-storage_8ts.html',1,'']]],
  ['oauth_2dutils_2etest_2ets_9',['oauth-utils.test.ts',['../oauth-utils_8test_8ts.html',1,'']]],
  ['oauth_2dutils_2ets_10',['oauth-utils.ts',['../oauth-utils_8ts.html',1,'']]],
  ['oauth2_2etest_2ets_11',['oauth2.test.ts',['../oauth2_8test_8ts.html',1,'']]],
  ['oauth2_2ets_12',['oauth2.ts',['../oauth2_8ts.html',1,'']]],
  ['oauth2client_20集成_13',['OAuth2Client 集成',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md494',1,'']]],
  ['objecttype_20类型_14',['ObjectType 类型',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md139',1,'']]],
  ['of_20concerns_15',['4. Separation of Concerns',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md10',1,'']]],
  ['of_20service_20and_20privacy_20notice_16',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['open_2dfiles_2dmanager_2etest_2ets_17',['open-files-manager.test.ts',['../open-files-manager_8test_8ts.html',1,'']]],
  ['open_2dfiles_2dmanager_2ets_18',['open-files-manager.ts',['../open-files-manager_8ts.html',1,'']]],
  ['opendiff_19',['openDiff()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md649',1,'']]],
  ['opentelemetry_20组件_20',['OpenTelemetry 组件',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md869',1,'']]],
  ['opentelemetry_20exports_21',['OpenTelemetry Exports',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md798',1,'']]],
  ['opentelemetry_20sdk_22',['OpenTelemetry SDK',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md784',1,'']]],
  ['options_20utility_23',['Diff Options Utility',['../md_packages_2core_2src_2tools_2diff_options_8ts.html',1,'']]],
  ['options_3a_20scope_3a_20string_24',['removeMcpServer(name: string, options: { scope: string })',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'']]],
  ['order_3a_20string_20undefined_20_3a_20dnsresolutionorder_25',['validateDnsResolutionOrder(order: string | undefined): DnsResolutionOrder',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md383',1,'']]],
  ['otlp_20导出器_26',['OTLP 导出器',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md860',1,'']]],
  ['overview_27',['Overview',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md2',1,'1.1 Overview'],['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md7',1,'3.1 Overview']]]
];
