var searchData=
[
  ['name_0',['Name',['../md_packages_2core_2src_2ide_2constants_8ts.html#autotoc_md639',1,'Extension Name'],['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md760',1,'Service Name']]],
  ['name_3a_20string_20options_3a_20scope_3a_20string_1',['removeMcpServer(name: string, options: { scope: string })',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'']]],
  ['name_3a_20string_20scope_3a_20settingscope_20cwd_3a_20string_20process_20cwd_2',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['name_3a_20string_20scopes_3a_20settingscope_3',['enableExtension(name: string, scopes: SettingScope[])',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'']]],
  ['names_4',['Directory and File Names',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md566',1,'']]],
  ['needsmigration_20settings_3a_20record_20_3a_20boolean_5',['needsMigration(settings: Record&amp;lt;string, unknown&amp;gt;): boolean',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md350',1,'']]],
  ['new_2etest_2ets_6',['new.test.ts',['../new_8test_8ts.html',1,'']]],
  ['new_2ets_7',['new.ts',['../new_8ts.html',1,'']]],
  ['newcommand_8',['newCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md208',1,'']]],
  ['nextspeakerchecker_2etest_2ets_9',['nextSpeakerChecker.test.ts',['../next_speaker_checker_8test_8ts.html',1,'']]],
  ['nextspeakerchecker_2ets_10',['nextSpeakerChecker.ts',['../next_speaker_checker_8ts.html',1,'']]],
  ['nextspeakercheckevent_11',['NextSpeakerCheckEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md893',1,'']]],
  ['no_2dcolor_2ets_12',['no-color.ts',['../no-color_8ts.html',1,'']]],
  ['noninteractivecli_20ts_13',['nonInteractiveCli.ts',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html',1,'']]],
  ['noninteractivecli_2etest_2ets_14',['nonInteractiveCli.test.ts',['../non_interactive_cli_8test_8ts.html',1,'']]],
  ['noninteractivecli_2ets_15',['nonInteractiveCli.ts',['../non_interactive_cli_8ts.html',1,'']]],
  ['noninteractivecli_2ets_2emd_16',['nonInteractiveCli.ts.md',['../non_interactive_cli_8ts_8md.html',1,'']]],
  ['noninteractivetoolexecutor_2etest_2ets_17',['nonInteractiveToolExecutor.test.ts',['../non_interactive_tool_executor_8test_8ts.html',1,'']]],
  ['noninteractivetoolexecutor_2ets_18',['nonInteractiveToolExecutor.ts',['../non_interactive_tool_executor_8ts.html',1,'']]],
  ['nooptaskstore_20测试套件_19',['NoOpTaskStore 测试套件',['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html#autotoc_md119',1,'']]],
  ['nooptaskstore_20类_20',['NoOpTaskStore 类',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md133',1,'']]],
  ['notice_21',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['notifications_22',['2.1 Asynchronous Responses and Notifications',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md5',1,'']]],
  ['null_23',['null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'findEnvFile(startDir: string): string | null'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'loadExtension(extensionDir: string): Extension | null'],['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md351',1,'migrateSettingsToV2(flatSettings: Record&lt;string, unknown&gt;): Record&lt;string, unknown&gt; | null']]],
  ['null_20_3a_20void_24',['setUpCloudShellEnvironment(envFilePath: string | null): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md357',1,'']]]
];
