var searchData=
[
  ['fatalerror_0',['FatalError',['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1034',1,'']]],
  ['fatalinputerror_1',['FatalInputError',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md404',1,'']]],
  ['fatalturnlimitederror_2',['FatalTurnLimitedError',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md405',1,'']]],
  ['features_3',['Features',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1071',1,'Features'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md981',1,'Key Features']]],
  ['fetch_2ets_4',['fetch.ts',['../fetch_8ts.html',1,'']]],
  ['file_20filtering_20defaults_5',['File Filtering Defaults',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md550',1,'']]],
  ['file_20names_6',['Directory and File Names',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md566',1,'']]],
  ['file_2dexporters_2ets_7',['file-exporters.ts',['../file-exporters_8ts.html',1,'']]],
  ['file_2dsystem_2dtest_2dhelpers_2ets_8',['file-system-test-helpers.ts',['../file-system-test-helpers_8ts.html',1,'']]],
  ['file_2dtoken_2dstorage_2etest_2ets_9',['file-token-storage.test.ts',['../file-token-storage_8test_8ts.html',1,'']]],
  ['file_2dtoken_2dstorage_2ets_10',['file-token-storage.ts',['../file-token-storage_8ts.html',1,'']]],
  ['filecommandloader_2etest_2ets_11',['FileCommandLoader.test.ts',['../_file_command_loader_8test_8ts.html',1,'']]],
  ['filecommandloader_2ets_12',['FileCommandLoader.ts',['../_file_command_loader_8ts.html',1,'']]],
  ['filediff_13',['FileDiff',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1013',1,'']]],
  ['filediscoveryservice_2etest_2ets_14',['fileDiscoveryService.test.ts',['../file_discovery_service_8test_8ts.html',1,'']]],
  ['filediscoveryservice_2ets_15',['fileDiscoveryService.ts',['../file_discovery_service_8ts.html',1,'']]],
  ['filefilteringoptions_16',['FileFilteringOptions',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md545',1,'']]],
  ['filefilteringoptions_20接口_17',['FileFilteringOptions 接口',['../md_packages_2core_2src_2config_2config.html#autotoc_md533',1,'']]],
  ['fileoperationevent_18',['FileOperationEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md896',1,'']]],
  ['filesearch_2etest_2ets_19',['fileSearch.test.ts',['../file_search_8test_8ts.html',1,'']]],
  ['filesearch_2ets_20',['fileSearch.ts',['../file_search_8ts.html',1,'']]],
  ['filesystemservice_21',['文件系统服务 (FileSystemService)',['../md_packages_2core_2src_2services_2file_system_service.html',1,'']]],
  ['filesystemservice_20接口_22',['FileSystemService 接口',['../md_packages_2core_2src_2services_2file_system_service.html#autotoc_md729',1,'']]],
  ['filesystemservice_2emd_23',['fileSystemService.md',['../file_system_service_8md.html',1,'']]],
  ['filesystemservice_2etest_2ets_24',['fileSystemService.test.ts',['../file_system_service_8test_8ts.html',1,'']]],
  ['filesystemservice_2ets_25',['fileSystemService.ts',['../cli_2src_2zed-integration_2file_system_service_8ts.html',1,'(Global Namespace)'],['../core_2src_2services_2file_system_service_8ts.html',1,'(Global Namespace)']]],
  ['fileutils_2etest_2ets_26',['fileUtils.test.ts',['../file_utils_8test_8ts.html',1,'']]],
  ['fileutils_2ets_27',['fileUtils.ts',['../file_utils_8ts.html',1,'']]],
  ['filtering_20defaults_28',['File Filtering Defaults',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md550',1,'']]],
  ['findenvfile_20函数_29',['findEnvFile 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md58',1,'']]],
  ['findenvfile_20startdir_3a_20string_20_3a_20string_20null_30',['findEnvFile(startDir: string): string | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'']]],
  ['flashfallback_2eintegration_2etest_2ets_31',['flashFallback.integration.test.ts',['../flash_fallback_8integration_8test_8ts.html',1,'']]],
  ['flashfallback_2etest_2ets_32',['flashFallback.test.ts',['../flash_fallback_8test_8ts.html',1,'']]],
  ['flashfallbackevent_33',['FlashFallbackEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md890',1,'']]],
  ['flashfallbackhandler_34',['FlashFallbackHandler',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md553',1,'']]],
  ['flashfallbackhandler_20类型_35',['FlashFallbackHandler 类型',['../md_packages_2core_2src_2config_2config.html#autotoc_md531',1,'']]],
  ['flatsettings_3a_20record_20_3a_20record_20null_36',['migrateSettingsToV2(flatSettings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt; | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md351',1,'']]],
  ['flow_37',['Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md4',1,'2. Communication Flow'],['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md12',1,'A. Example Interaction Flow']]],
  ['formatters_2etest_2ets_38',['formatters.test.ts',['../formatters_8test_8ts.html',1,'']]],
  ['formatters_2ets_39',['formatters.ts',['../cli_2src_2ui_2utils_2formatters_8ts.html',1,'(Global Namespace)'],['../core_2src_2utils_2formatters_8ts.html',1,'(Global Namespace)']]],
  ['framework_40',['Tools Framework',['../md_packages_2core_2src_2tools_2tools_8ts.html',1,'']]],
  ['functions_41',['Functions',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md796',1,'Event Creation Functions'],['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md828',1,'Event Logging Functions'],['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md872',1,'Functions'],['../md_packages_2core_2src_2tools_2diff_options_8ts.html#autotoc_md937',1,'Functions'],['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md825',1,'Helper Functions'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md794',1,'Logging Functions'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md793',1,'SDK Functions'],['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1021',1,'Utility Functions']]]
];
