var searchData=
[
  ['canceltask_0',['&lt;span class=&quot;tt&quot;&gt;cancelTask&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md31',1,'']]],
  ['chatcommand_2etest_2ets_1',['chatCommand.test.ts',['../chat_command_8test_8ts.html',1,'']]],
  ['chatcommand_2ets_2',['chatCommand.ts',['../chat_command_8ts.html',1,'']]],
  ['chatcompressionevent_3',['ChatCompressionEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md895',1,'']]],
  ['chatcompressioninfo_20接口_4',['ChatCompressionInfo 接口',['../md_packages_2core_2src_2core_2turn.html#autotoc_md635',1,'']]],
  ['chatcompressionsettings_5',['ChatCompressionSettings',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md541',1,'']]],
  ['chatrecordingservice_6',['聊天记录服务 (ChatRecordingService)',['../md_packages_2core_2src_2services_2chat_recording_service.html',1,'']]],
  ['chatrecordingservice_2emd_7',['chatRecordingService.md',['../chat_recording_service_8md.html',1,'']]],
  ['chatrecordingservice_2etest_2ets_8',['chatRecordingService.test.ts',['../chat_recording_service_8test_8ts.html',1,'']]],
  ['chatrecordingservice_2ets_9',['chatRecordingService.ts',['../chat_recording_service_8ts.html',1,'']]],
  ['checkpointingsettings_20接口_10',['CheckpointingSettings 接口',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md73',1,'']]],
  ['checks_2ets_11',['checks.ts',['../checks_8ts.html',1,'']]],
  ['childprocessfallback_12',['childProcessFallback()',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md750',1,'']]],
  ['class_13',['Storage Class',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md567',1,'']]],
  ['classes_14',['Classes',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1007',1,'Base Classes'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md546',1,'Classes'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md973',1,'Core Classes']]],
  ['cleanup_2etest_2ets_15',['cleanup.test.ts',['../cleanup_8test_8ts.html',1,'']]],
  ['cleanup_2ets_16',['cleanup.ts',['../cleanup_8ts.html',1,'']]],
  ['clear_17',['clear()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md700',1,'']]],
  ['clearcommand_2etest_2ets_18',['clearCommand.test.ts',['../clear_command_8test_8ts.html',1,'']]],
  ['clearcommand_2ets_19',['clearCommand.ts',['../clear_command_8ts.html',1,'']]],
  ['clearcut_20集成_20',['Clearcut 集成',['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md819',1,'']]],
  ['clearcut_2dlogger_2etest_2ets_21',['clearcut-logger.test.ts',['../clearcut-logger_8test_8ts.html',1,'']]],
  ['clearcut_2dlogger_2ets_22',['clearcut-logger.ts',['../clearcut-logger_8ts.html',1,'']]],
  ['clearcutlogger_23',['ClearcutLogger',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md785',1,'']]],
  ['cli_20代码说明文档索引_24',['Gemini CLI 代码说明文档索引',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md175',1,'']]],
  ['cli_20a2a_20development_20tool_20extension_25',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['cli_20a2a_20server_26',['Gemini CLI A2A Server',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md16',1,'']]],
  ['cli_20companion_27',['Gemini CLI Companion',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1070',1,'']]],
  ['cliargs_28',['CliArgs',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md280',1,'']]],
  ['client_2emd_29',['client.md',['../client_8md.html',1,'']]],
  ['client_2etest_2ets_30',['client.test.ts',['../client_8test_8ts.html',1,'']]],
  ['client_2ets_31',['client.ts',['../client_8ts.html',1,'']]],
  ['clipboardutils_2etest_2ets_32',['clipboardUtils.test.ts',['../clipboard_utils_8test_8ts.html',1,'']]],
  ['clipboardutils_2ets_33',['clipboardUtils.ts',['../clipboard_utils_8ts.html',1,'']]],
  ['closediff_34',['closeDiff()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md650',1,'']]],
  ['code_20in_20this_20package_20is_20experimental_20and_20under_20active_20development_35',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['codeassist_36',['代码辅助功能 (codeAssist)',['../md_packages_2core_2src_2code__assist_2code_assist.html',1,'']]],
  ['codeassist_2emd_37',['codeAssist.md',['../code_assist_8md.html',1,'']]],
  ['codeassist_2ets_38',['codeAssist.ts',['../code_assist_8ts.html',1,'']]],
  ['codeassistserver_20类_39',['CodeAssistServer 类',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md490',1,'']]],
  ['coderagentcard_20对象_40',['coderAgentCard 对象',['../md_packages_2a2a-server_2src_2http_2app_8ts.html#autotoc_md89',1,'']]],
  ['coderagentevent_20枚举_41',['CoderAgentEvent 枚举',['../md_packages_2a2a-server_2src_2types_8ts.html#autotoc_md144',1,'']]],
  ['coderagentexecutor_20类_42',['CoderAgentExecutor 类',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md23',1,'']]],
  ['color_2dutils_2etest_2ets_43',['color-utils.test.ts',['../color-utils_8test_8ts.html',1,'']]],
  ['color_2dutils_2ets_44',['color-utils.ts',['../color-utils_8ts.html',1,'']]],
  ['colors_45',['Colors',['../md_packages_2cli_2src_2ui_2colors_8ts.html#autotoc_md445',1,'']]],
  ['colors_20ts_46',['colors.ts',['../md_packages_2cli_2src_2ui_2colors_8ts.html',1,'']]],
  ['colors_2ets_47',['colors.ts',['../colors_8ts.html',1,'']]],
  ['colors_2ets_2emd_48',['colors.ts.md',['../colors_8ts_8md.html',1,'']]],
  ['command_49',['Command',['../md_packages_2cli_2src_2config_2key_bindings_8ts.html#autotoc_md320',1,'']]],
  ['commandmodule_50',['CommandModule',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md236',1,'addCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md199',1,'extensionsCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md216',1,'installCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md227',1,'listCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md249',1,'listCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md257',1,'mcpCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md267',1,'removeCommand: CommandModule']]],
  ['commandservice_2etest_2ets_51',['CommandService.test.ts',['../_command_service_8test_8ts.html',1,'']]],
  ['commandservice_2ets_52',['CommandService.ts',['../_command_service_8ts.html',1,'']]],
  ['commandutils_2etest_2ets_53',['commandUtils.test.ts',['../command_utils_8test_8ts.html',1,'']]],
  ['commandutils_2ets_54',['commandUtils.ts',['../command_utils_8ts.html',1,'']]],
  ['communication_20flow_55',['2. Communication Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md4',1,'']]],
  ['companion_56',['Gemini CLI Companion',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1070',1,'']]],
  ['compresscommand_2etest_2ets_57',['compressCommand.test.ts',['../compress_command_8test_8ts.html',1,'']]],
  ['compresscommand_2ets_58',['compressCommand.ts',['../compress_command_8ts.html',1,'']]],
  ['compressionstatus_20枚举_59',['CompressionStatus 枚举',['../md_packages_2core_2src_2core_2turn.html#autotoc_md634',1,'']]],
  ['computestats_2etest_2ets_60',['computeStats.test.ts',['../compute_stats_8test_8ts.html',1,'']]],
  ['computestats_2ets_61',['computeStats.ts',['../compute_stats_8ts.html',1,'']]],
  ['concerns_62',['4. Separation of Concerns',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md10',1,'']]],
  ['config_63',['Config',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md548',1,'']]],
  ['config_20类_64',['Config 类',['../md_packages_2core_2src_2config_2config.html',1,'']]],
  ['config_20_3a_20string_65',['getNodeMemoryArgs(config: Config): string[]',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'']]],
  ['config_20authtype_3a_20authtype_20undefined_20_3a_20promise_66',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['config_20config_20ts_67',['src/config/config.ts',['../md_packages_2a2a-server_2src_2config_2config_8ts.html',1,'']]],
  ['config_20extension_20ts_68',['src/config/extension.ts',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html',1,'']]],
  ['config_20input_3a_20string_20prompt_5fid_3a_20string_20_3a_20promise_69',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['config_20settings_20startupwarnings_20workspaceroot_20initializationresult_70',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['config_20settings_20ts_71',['src/config/settings.ts',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html',1,'']]],
  ['config_20settings_3a_20loadedsettings_20_3a_20promise_72',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['config_20ts_73',['config ts',['../md_packages_2cli_2src_2config_2config_8ts.html',1,'config.ts'],['../md_packages_2a2a-server_2src_2config_2config_8ts.html',1,'src/config/config.ts'],['../md_packages_2a2a-server_2vitest_8config_8ts.html',1,'vitest.config.ts'],['../md_packages_2cli_2vitest_8config_8ts.html',1,'vitest.config.ts'],['../md_packages_2core_2vitest_8config_8ts.html',1,'vitest.config.ts']]],
  ['config_2eintegration_2etest_2ets_74',['config.integration.test.ts',['../config_8integration_8test_8ts.html',1,'']]],
  ['config_2emd_75',['config.md',['../config_8md.html',1,'']]],
  ['config_2etest_2ets_76',['config.test.ts',['../cli_2src_2config_2config_8test_8ts.html',1,'(Global Namespace)'],['../core_2src_2config_2config_8test_8ts.html',1,'(Global Namespace)']]],
  ['config_2ets_77',['config.ts',['../a2a-server_2src_2config_2config_8ts.html',1,'(Global Namespace)'],['../cli_2src_2config_2config_8ts.html',1,'(Global Namespace)'],['../core_2src_2config_2config_8ts.html',1,'(Global Namespace)'],['../core_2src_2test-utils_2config_8ts.html',1,'(Global Namespace)']]],
  ['config_2ets_2emd_78',['config.ts.md',['../a2a-server_2src_2config_2config_8ts_8md.html',1,'(Global Namespace)'],['../cli_2src_2config_2config_8ts_8md.html',1,'(Global Namespace)'],['../core_2src_2config_2config_8ts_8md.html',1,'(Global Namespace)']]],
  ['config_3a_20config_20_3a_20string_79',['getNodeMemoryArgs(config: Config): string[]',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'']]],
  ['config_3a_20config_20authtype_3a_20authtype_20undefined_20_3a_20promise_80',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['config_3a_20config_20input_3a_20string_20prompt_5fid_3a_20string_20_3a_20promise_81',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['config_3a_20config_20settings_3a_20loadedsettings_20_3a_20promise_82',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['config_3a_20mcpserverconfig_20_3a_20promise_83',['testMCPConnection(serverName: string, config: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'']]],
  ['configuration_84',['Configuration',['../md_packages_2core_2src_2config_2config_8ts.html',1,'Core Configuration'],['../md_packages_2core_2test-setup_8ts.html#autotoc_md1058',1,'Environment Configuration']]],
  ['configuration_20constants_85',['Model Configuration Constants',['../md_packages_2core_2src_2config_2models_8ts.html',1,'']]],
  ['connect_86',['connect()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md648',1,'']]],
  ['consolepatcher_87',['ConsolePatcher',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md411',1,'']]],
  ['consolepatcher_2ets_88',['ConsolePatcher.ts',['../_console_patcher_8ts.html',1,'']]],
  ['constants_89',['Constants',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md549',1,'Constants'],['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md565',1,'Constants'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md790',1,'Constants'],['../md_packages_2core_2src_2tools_2diff_options_8ts.html#autotoc_md935',1,'Constants'],['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md762',1,'Event Constants'],['../md_packages_2core_2src_2ide_2constants_8ts.html',1,'IDE Constants'],['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md763',1,'Metric Constants'],['../md_packages_2core_2src_2config_2models_8ts.html',1,'Model Configuration Constants'],['../md_packages_2core_2src_2telemetry_2constants_8ts.html',1,'Telemetry Constants']]],
  ['constants_20ts_90',['constants.ts',['../md_packages_2cli_2src_2ui_2constants_8ts.html',1,'']]],
  ['constants_2ets_91',['constants.ts',['../cli_2src_2ui_2constants_8ts.html',1,'(Global Namespace)'],['../core_2src_2ide_2constants_8ts.html',1,'(Global Namespace)'],['../core_2src_2telemetry_2constants_8ts.html',1,'(Global Namespace)']]],
  ['constants_2ets_2emd_92',['constants.ts.md',['../cli_2src_2ui_2constants_8ts_8md.html',1,'(Global Namespace)'],['../core_2src_2ide_2constants_8ts_8md.html',1,'(Global Namespace)'],['../core_2src_2telemetry_2constants_8ts_8md.html',1,'(Global Namespace)']]],
  ['contentgenerator_20接口和相关实现_93',['ContentGenerator 接口和相关实现',['../md_packages_2core_2src_2core_2content_generator.html',1,'']]],
  ['contentgenerator_20接口_94',['ContentGenerator 接口',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md583',1,'']]],
  ['contentgenerator_2emd_95',['contentGenerator.md',['../content_generator_8md.html',1,'']]],
  ['contentgenerator_2etest_2ets_96',['contentGenerator.test.ts',['../content_generator_8test_8ts.html',1,'']]],
  ['contentgenerator_2ets_97',['contentGenerator.ts',['../content_generator_8ts.html',1,'']]],
  ['contentgeneratorconfig_20类型_98',['ContentGeneratorConfig 类型',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md586',1,'']]],
  ['contentretryevent_99',['ContentRetryEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md905',1,'']]],
  ['contentretryfailureevent_100',['ContentRetryFailureEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md906',1,'']]],
  ['conversationfinishedevent_101',['ConversationFinishedEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md900',1,'']]],
  ['conversationrecord_102',['ConversationRecord',['../md_packages_2core_2src_2services_2chat_recording_service.html#autotoc_md715',1,'']]],
  ['converter_2etest_2ets_103',['converter.test.ts',['../converter_8test_8ts.html',1,'']]],
  ['converter_2ets_104',['converter.ts',['../converter_8ts.html',1,'']]],
  ['copycommand_2etest_2ets_105',['copyCommand.test.ts',['../copy_command_8test_8ts.html',1,'']]],
  ['copycommand_2ets_106',['copyCommand.ts',['../copy_command_8ts.html',1,'']]],
  ['core_20classes_107',['Core Classes',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md973',1,'']]],
  ['core_20configuration_108',['Core Configuration',['../md_packages_2core_2src_2config_2config_8ts.html',1,'']]],
  ['core_20interfaces_109',['Core Interfaces',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1003',1,'']]],
  ['core_20test_20setup_110',['Core Test Setup',['../md_packages_2core_2test-setup_8ts.html',1,'']]],
  ['coretoolscheduler_2etest_2ets_111',['coreToolScheduler.test.ts',['../core_tool_scheduler_8test_8ts.html',1,'']]],
  ['coretoolscheduler_2ets_112',['coreToolScheduler.ts',['../core_tool_scheduler_8ts.html',1,'']]],
  ['corgicommand_2etest_2ets_113',['corgiCommand.test.ts',['../corgi_command_8test_8ts.html',1,'']]],
  ['corgicommand_2ets_114',['corgiCommand.ts',['../corgi_command_8ts.html',1,'']]],
  ['crawlcache_2etest_2ets_115',['crawlCache.test.ts',['../crawl_cache_8test_8ts.html',1,'']]],
  ['crawlcache_2ets_116',['crawlCache.ts',['../crawl_cache_8ts.html',1,'']]],
  ['crawler_2etest_2ets_117',['crawler.test.ts',['../crawler_8test_8ts.html',1,'']]],
  ['crawler_2ets_118',['crawler.ts',['../crawler_8ts.html',1,'']]],
  ['create_119',['&lt;span class=&quot;tt&quot;&gt;create&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html#autotoc_md45',1,'']]],
  ['createapp_20函数_120',['createApp 函数',['../md_packages_2a2a-server_2src_2http_2app_8ts.html#autotoc_md91',1,'']]],
  ['createcodeassistcontentgenerator_121',['createCodeAssistContentGenerator()',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md487',1,'']]],
  ['createcontentgenerator_122',['createContentGenerator()',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md589',1,'']]],
  ['createcontentgeneratorconfig_123',['createContentGeneratorConfig()',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md588',1,'']]],
  ['createmockconfig_124',['createMockConfig',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html#autotoc_md156',1,'']]],
  ['createstreammessagerequest_125',['createStreamMessageRequest',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html#autotoc_md157',1,'']]],
  ['createtask_126',['&lt;span class=&quot;tt&quot;&gt;createTask&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md28',1,'']]],
  ['creation_20functions_127',['Event Creation Functions',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md796',1,'']]],
  ['csrf_20保护_128',['CSRF 保护',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md690',1,'']]],
  ['custommatchers_2ets_129',['customMatchers.ts',['../custom_matchers_8ts.html',1,'']]],
  ['cwd_130',['cwd',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())'],['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'loadCliConfig(settings, extensions, sessionId, argv, cwd)']]],
  ['cwd_20_3a_20extension_131',['loadExtensions(workspaceDir: string = process.cwd()): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'']]],
  ['cwd_20_3a_20loadedsettings_132',['loadSettings(workspaceDir: string = process.cwd()): LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'']]],
  ['cwd_20_3a_20promise_133',['cwd : Promise',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]],
  ['cwd_3a_20string_20process_20cwd_134',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['cwd_3a_20string_20process_20cwd_20_3a_20promise_135',['cwd: string process cwd : Promise',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]]
];
