var searchData=
[
  ['a_20example_20interaction_20flow_0',['A. Example Interaction Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md12',1,'']]],
  ['a2a_20development_20tool_20extension_1',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['a2a_20server_2',['Gemini CLI A2A Server',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md16',1,'']]],
  ['abortcontroller_3',['AbortController',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md413',1,'']]],
  ['aboutcommand_2etest_2ets_4',['aboutCommand.test.ts',['../about_command_8test_8ts.html',1,'']]],
  ['aboutcommand_2ets_5',['aboutCommand.ts',['../about_command_8ts.html',1,'']]],
  ['accessibilitysettings_6',['AccessibilitySettings',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md539',1,'']]],
  ['acp_2ets_7',['acp.ts',['../acp_8ts.html',1,'']]],
  ['active_20development_8',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['add_20ts_9',['add.ts',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html',1,'']]],
  ['add_2etest_2ets_10',['add.test.ts',['../add_8test_8ts.html',1,'']]],
  ['add_2ets_11',['add.ts',['../add_8ts.html',1,'']]],
  ['add_2ets_2emd_12',['add.ts.md',['../add_8ts_8md.html',1,'']]],
  ['addcommand_13',['addCommand',['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md259',1,'']]],
  ['addcommand_3a_20commandmodule_14',['addCommand: CommandModule',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md236',1,'']]],
  ['additionalargs_3a_20string_15',['relaunchWithAdditionalArgs(additionalArgs: string[])',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md385',1,'']]],
  ['addmcpserver_16',['addMcpServer()',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md235',1,'']]],
  ['agent_20executor_20ts_17',['src/agent/executor.ts',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html',1,'']]],
  ['agent_20task_20ts_18',['src/agent/task.ts',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html',1,'']]],
  ['agentsettings_20接口_19',['AgentSettings 接口',['../md_packages_2a2a-server_2src_2types_8ts.html#autotoc_md145',1,'']]],
  ['aliases_20',['Type Aliases',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1025',1,'']]],
  ['all_20code_20in_20this_20package_20is_20experimental_20and_20under_20active_20development_21',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['allowedmcpservers_22',['allowedMcpServers()',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md286',1,'']]],
  ['and_20file_20names_23',['Directory and File Names',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md566',1,'']]],
  ['and_20notifications_24',['2.1 Asynchronous Responses and Notifications',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md5',1,'']]],
  ['and_20privacy_20notice_25',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['and_20under_20active_20development_26',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['annotateactiveextensions_20extensions_20enabledextensionnames_20workspacedir_20_3a_20geminicliextension_27',['annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'']]],
  ['ansi_20转义序列处理_28',['ANSI 转义序列处理',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md753',1,'']]],
  ['ansi_2dlight_2ets_29',['ansi-light.ts',['../ansi-light_8ts.html',1,'']]],
  ['ansi_2ets_30',['ansi.ts',['../ansi_8ts.html',1,'']]],
  ['anydeclarativetool_31',['AnyDeclarativeTool',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1027',1,'']]],
  ['anytoolinvocation_32',['AnyToolInvocation',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1026',1,'']]],
  ['api_20方法_33',['API 方法',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md496',1,'']]],
  ['apierrorevent_34',['ApiErrorEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md888',1,'']]],
  ['apirequestevent_35',['ApiRequestEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md887',1,'']]],
  ['apiresponseevent_36',['ApiResponseEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md889',1,'']]],
  ['app_20test_20ts_37',['app.test.ts',['../md_packages_2a2a-server_2src_2http_2app_8test_8ts.html',1,'']]],
  ['app_20ts_38',['src/http/app.ts',['../md_packages_2a2a-server_2src_2http_2app_8ts.html',1,'']]],
  ['app_2etest_2ets_39',['app.test.ts',['../app_8test_8ts.html',1,'']]],
  ['app_2etest_2ets_2emd_40',['app.test.ts.md',['../app_8test_8ts_8md.html',1,'']]],
  ['app_2ets_41',['app.ts',['../app_8ts.html',1,'']]],
  ['app_2ets_2emd_42',['app.ts.md',['../app_8ts_8md.html',1,'']]],
  ['appcontainer_20tsx_43',['AppContainer.tsx',['../md_packages_2cli_2src_2ui_2_app_container_8tsx.html',1,'']]],
  ['appcontainer_2etsx_2emd_44',['AppContainer.tsx.md',['../_app_container_8tsx_8md.html',1,'']]],
  ['appendix_45',['Appendix',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md11',1,'']]],
  ['approvalmode_46',['ApprovalMode',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md536',1,'']]],
  ['approvalmode_20枚举_47',['ApprovalMode 枚举',['../md_packages_2core_2src_2config_2config.html#autotoc_md526',1,'']]],
  ['args_3a_20installargs_48',['handleInstall(args: InstallArgs)',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md215',1,'']]],
  ['argumentprocessor_2etest_2ets_49',['argumentProcessor.test.ts',['../argument_processor_8test_8ts.html',1,'']]],
  ['argumentprocessor_2ets_50',['argumentProcessor.ts',['../argument_processor_8ts.html',1,'']]],
  ['argv_20cwd_51',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['asciiart_2ets_52',['AsciiArt.ts',['../_ascii_art_8ts.html',1,'']]],
  ['asserttaskcreationandworkingstatus_53',['assertTaskCreationAndWorkingStatus',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html#autotoc_md159',1,'']]],
  ['assertuniquefinaleventislast_54',['assertUniqueFinalEventIsLast',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html#autotoc_md158',1,'']]],
  ['asynchronous_20responses_20and_20notifications_55',['2.1 Asynchronous Responses and Notifications',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md5',1,'']]],
  ['atcommandprocessor_2etest_2ets_56',['atCommandProcessor.test.ts',['../at_command_processor_8test_8ts.html',1,'']]],
  ['atcommandprocessor_2ets_57',['atCommandProcessor.ts',['../at_command_processor_8ts.html',1,'']]],
  ['atfileprocessor_2etest_2ets_58',['atFileProcessor.test.ts',['../at_file_processor_8test_8ts.html',1,'']]],
  ['atfileprocessor_2ets_59',['atFileProcessor.ts',['../at_file_processor_8ts.html',1,'']]],
  ['atom_2done_2ddark_2ets_60',['atom-one-dark.ts',['../atom-one-dark_8ts.html',1,'']]],
  ['auth_20ts_61',['auth ts',['../md_packages_2cli_2src_2config_2auth_8ts.html',1,'auth.ts'],['../md_packages_2cli_2src_2core_2auth_8ts.html',1,'auth.ts']]],
  ['auth_2etest_2ets_62',['auth.test.ts',['../auth_8test_8ts.html',1,'']]],
  ['auth_2ets_63',['auth.ts',['../config_2auth_8ts.html',1,'(Global Namespace)'],['../core_2auth_8ts.html',1,'(Global Namespace)']]],
  ['auth_2ets_2emd_64',['auth.ts.md',['../config_2auth_8ts_8md.html',1,'(Global Namespace)'],['../core_2auth_8ts_8md.html',1,'(Global Namespace)']]],
  ['authcommand_2etest_2ets_65',['authCommand.test.ts',['../auth_command_8test_8ts.html',1,'']]],
  ['authcommand_2ets_66',['authCommand.ts',['../auth_command_8ts.html',1,'']]],
  ['authenticate_67',['authenticate()',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md673',1,'']]],
  ['authprovidertype_68',['AuthProviderType',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md537',1,'']]],
  ['authprovidertype_20枚举_69',['AuthProviderType 枚举',['../md_packages_2core_2src_2config_2config.html#autotoc_md530',1,'']]],
  ['authtype_20枚举_70',['AuthType 枚举',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md585',1,'']]],
  ['authtype_20undefined_20_3a_20promise_71',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['authtype_3a_20authtype_20undefined_20_3a_20promise_72',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['ayu_2dlight_2ets_73',['ayu-light.ts',['../ayu-light_8ts.html',1,'']]],
  ['ayu_2ets_74',['ayu.ts',['../ayu_8ts.html',1,'']]]
];
