var searchData=
[
  ['main_0',['main',['../md_packages_2cli_2index_8ts.html#autotoc_md173',1,'main()'],['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md388',1,'main()']]],
  ['main_20函数_1',['main 函数',['../md_packages_2a2a-server_2src_2http_2app_8ts.html#autotoc_md92',1,'']]],
  ['makechatcompressionevent_2',['makeChatCompressionEvent()',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md913',1,'']]],
  ['makerelative_3',['相对路径计算 (makeRelative)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1053',1,'']]],
  ['makeslashcommandevent_4',['makeSlashCommandEvent()',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md912',1,'']]],
  ['malformedjsonresponseevent_5',['MalformedJsonResponseEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md903',1,'']]],
  ['management_6',['Management',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md984',1,'Process Management'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md979',1,'Schema Management'],['../md_packages_2core_2src_2config_2storage_8ts.html',1,'Storage Management'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md977',1,'Tool Management']]],
  ['markdownutilities_2etest_2ets_7',['markdownUtilities.test.ts',['../markdown_utilities_8test_8ts.html',1,'']]],
  ['markdownutilities_2ets_8',['markdownUtilities.ts',['../markdown_utilities_8ts.html',1,'']]],
  ['mcp_20命令_9',['MCP 命令',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md185',1,'']]],
  ['mcp_20支持_10',['MCP 支持',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md191',1,'']]],
  ['mcp_20管理_11',['MCP 管理',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md194',1,'']]],
  ['mcp_20集成_12',['MCP 集成',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md709',1,'']]],
  ['mcp_20integration_13',['MCP Integration',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md980',1,'']]],
  ['mcp_20oauth_20提供者_20mcpoauthprovider_14',['MCP OAuth 提供者 (MCPOAuthProvider)',['../md_packages_2core_2src_2mcp_2oauth-provider.html',1,'']]],
  ['mcp_20server_20integration_15',['MCP Server Integration',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md983',1,'']]],
  ['mcp_20ts_16',['mcp.ts',['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html',1,'']]],
  ['mcp_2dclient_2dmanager_2etest_2ets_17',['mcp-client-manager.test.ts',['../mcp-client-manager_8test_8ts.html',1,'']]],
  ['mcp_2dclient_2dmanager_2ets_18',['mcp-client-manager.ts',['../mcp-client-manager_8ts.html',1,'']]],
  ['mcp_2dclient_2etest_2ets_19',['mcp-client.test.ts',['../mcp-client_8test_8ts.html',1,'']]],
  ['mcp_2dclient_2ets_20',['mcp-client.ts',['../mcp-client_8ts.html',1,'']]],
  ['mcp_2dprompts_2ets_21',['mcp-prompts.ts',['../mcp-prompts_8ts.html',1,'']]],
  ['mcp_2dtool_2etest_2ets_22',['mcp-tool.test.ts',['../mcp-tool_8test_8ts.html',1,'']]],
  ['mcp_2dtool_2ets_23',['mcp-tool.ts',['../mcp-tool_8ts.html',1,'']]],
  ['mcp_2etest_2ets_24',['mcp.test.ts',['../mcp_8test_8ts.html',1,'']]],
  ['mcp_2ets_25',['mcp.ts',['../mcp_8ts.html',1,'']]],
  ['mcp_2ets_2emd_26',['mcp.ts.md',['../mcp_8ts_8md.html',1,'']]],
  ['mcpcommand_2etest_2ets_27',['mcpCommand.test.ts',['../mcp_command_8test_8ts.html',1,'']]],
  ['mcpcommand_2ets_28',['mcpCommand.ts',['../mcp_command_8ts.html',1,'']]],
  ['mcpcommand_3a_20commandmodule_29',['mcpCommand: CommandModule',['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md257',1,'']]],
  ['mcpoauthconfig_30',['MCPOAuthConfig',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md671',1,'']]],
  ['mcpoauthprovider_31',['MCP OAuth 提供者 (MCPOAuthProvider)',['../md_packages_2core_2src_2mcp_2oauth-provider.html',1,'']]],
  ['mcppromptloader_2etest_2ets_32',['McpPromptLoader.test.ts',['../_mcp_prompt_loader_8test_8ts.html',1,'']]],
  ['mcppromptloader_2ets_33',['McpPromptLoader.ts',['../_mcp_prompt_loader_8ts.html',1,'']]],
  ['mcpserverconfig_34',['MCPServerConfig',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md547',1,'']]],
  ['mcpserverconfig_20类_35',['MCPServerConfig 类',['../md_packages_2core_2src_2config_2config.html#autotoc_md528',1,'']]],
  ['mcpserverconfig_20_3a_20promise_36',['MCPServerConfig : Promise',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'getServerStatus(serverName: string, server: MCPServerConfig): Promise&lt;MCPServerStatus&gt;'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'testMCPConnection(serverName: string, config: MCPServerConfig): Promise&lt;MCPServerStatus&gt;']]],
  ['memorycommand_2etest_2ets_37',['memoryCommand.test.ts',['../memory_command_8test_8ts.html',1,'']]],
  ['memorycommand_2ets_38',['memoryCommand.ts',['../memory_command_8ts.html',1,'']]],
  ['memorydiscovery_2etest_2ets_39',['memoryDiscovery.test.ts',['../memory_discovery_8test_8ts.html',1,'']]],
  ['memorydiscovery_2ets_40',['memoryDiscovery.ts',['../memory_discovery_8ts.html',1,'']]],
  ['memoryimportprocessor_2etest_2ets_41',['memoryImportProcessor.test.ts',['../memory_import_processor_8test_8ts.html',1,'']]],
  ['memoryimportprocessor_2ets_42',['memoryImportProcessor.ts',['../memory_import_processor_8ts.html',1,'']]],
  ['memorytool_2etest_2ets_43',['memoryTool.test.ts',['../memory_tool_8test_8ts.html',1,'']]],
  ['memorytool_2ets_44',['memoryTool.ts',['../memory_tool_8ts.html',1,'']]],
  ['mergeexcludetools_45',['mergeExcludeTools()',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md288',1,'']]],
  ['mergemcpservers_46',['mergeMcpServers()',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md287',1,'']]],
  ['mergemcpservers_20函数_47',['mergeMcpServers 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md55',1,'']]],
  ['mergesettings_48',['mergeSettings()',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md354',1,'']]],
  ['messageinspectors_2ets_49',['messageInspectors.ts',['../message_inspectors_8ts.html',1,'']]],
  ['messagerecord_50',['MessageRecord',['../md_packages_2core_2src_2services_2chat_recording_service.html#autotoc_md716',1,'']]],
  ['messagesendertype_20枚举_51',['MessageSenderType 枚举',['../md_packages_2core_2src_2core_2logger.html#autotoc_md604',1,'']]],
  ['method_20definitions_52',['3.3 Method Definitions',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md9',1,'']]],
  ['methods_53',['Methods',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md570',1,'Instance Methods'],['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md572',1,'Private Methods'],['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md568',1,'Static Methods']]],
  ['metric_20constants_54',['Metric Constants',['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md763',1,'']]],
  ['metrics_2etest_2ets_55',['metrics.test.ts',['../metrics_8test_8ts.html',1,'']]],
  ['metrics_2ets_56',['metrics.ts',['../metrics_8ts.html',1,'']]],
  ['migratesettingstov1_20v2settings_3a_20record_20_3a_20record_57',['migrateSettingsToV1(v2Settings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt;',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md352',1,'']]],
  ['migratesettingstov2_20flatsettings_3a_20record_20_3a_20record_20null_58',['migrateSettingsToV2(flatSettings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt; | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md351',1,'']]],
  ['migration_5fmap_59',['MIGRATION_MAP',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md359',1,'']]],
  ['mock_2dtool_2ets_60',['mock-tool.ts',['../mock-tool_8ts.html',1,'']]],
  ['mockcommandcontext_2etest_2ets_61',['mockCommandContext.test.ts',['../mock_command_context_8test_8ts.html',1,'']]],
  ['mockcommandcontext_2ets_62',['mockCommandContext.ts',['../mock_command_context_8ts.html',1,'']]],
  ['mocktool_20类_63',['MockTool 类',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md916',1,'']]],
  ['mocktoolinvocation_20类_64',['MockToolInvocation 类',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md918',1,'']]],
  ['mocktooloptions_20接口_65',['MockToolOptions 接口',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md917',1,'']]],
  ['mockworkspacecontext_2ets_66',['mockWorkspaceContext.ts',['../mock_workspace_context_8ts.html',1,'']]],
  ['mode_67',['Thinking Mode',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md562',1,'']]],
  ['model_20configuration_20constants_68',['Model Configuration Constants',['../md_packages_2core_2src_2config_2models_8ts.html',1,'']]],
  ['models_69',['Default Models',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md557',1,'']]],
  ['models_2ets_70',['models.ts',['../models_8ts.html',1,'']]],
  ['models_2ets_2emd_71',['models.ts.md',['../models_8ts_8md.html',1,'']]],
  ['modifiable_2dtool_2etest_2ets_72',['modifiable-tool.test.ts',['../modifiable-tool_8test_8ts.html',1,'']]],
  ['modifiable_2dtool_2ets_73',['modifiable-tool.ts',['../modifiable-tool_8ts.html',1,'']]],
  ['motivation_74',['1.2 Motivation',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md3',1,'']]],
  ['msw_2ets_75',['msw.ts',['../msw_8ts.html',1,'']]]
];
