var searchData=
[
  ['language_2ddetection_2ets_0',['language-detection.ts',['../language-detection_8ts.html',1,'']]],
  ['library_20screen_20reader_20guidance_1',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]],
  ['link_2ets_2',['link.ts',['../link_8ts.html',1,'']]],
  ['linkcommand_3',['linkCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md207',1,'']]],
  ['list_20ts_4',['list ts',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html',1,'list.ts'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html',1,'list.ts']]],
  ['list_2etest_2ets_5',['list.test.ts',['../list_8test_8ts.html',1,'']]],
  ['list_2ets_6',['list.ts',['../extensions_2list_8ts.html',1,'(Global Namespace)'],['../mcp_2list_8ts.html',1,'(Global Namespace)']]],
  ['list_2ets_2emd_7',['list.ts.md',['../extensions_2list_8ts_8md.html',1,'(Global Namespace)'],['../mcp_2list_8ts_8md.html',1,'(Global Namespace)']]],
  ['listcommand_8',['listCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md203',1,'listCommand'],['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md261',1,'listCommand']]],
  ['listcommand_3a_20commandmodule_9',['listCommand: CommandModule',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md227',1,'listCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md249',1,'listCommand: CommandModule']]],
  ['listmcpservers_20_3a_20promise_10',['listMcpServers(): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md248',1,'']]],
  ['llm_2dedit_2dfixer_2ets_11',['llm-edit-fixer.ts',['../llm-edit-fixer_8ts.html',1,'']]],
  ['load_12',['load',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md132',1,'<span class="tt">load</span>'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md137',1,'<span class="tt">load</span>']]],
  ['loadcliconfig_20settings_20extensions_20sessionid_20argv_20cwd_13',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['loadconfig_20函数_14',['loadConfig 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md54',1,'']]],
  ['loadedsettings_15',['LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md345',1,'LoadedSettings'],['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'loadSettings(workspaceDir: string = process.cwd()): LoadedSettings']]],
  ['loadedsettings_20_3a_20promise_16',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['loadenvironment_20函数_17',['loadEnvironment 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md57',1,'']]],
  ['loadenvironment_20settings_3a_20settings_20_3a_20void_18',['loadEnvironment(settings: Settings): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md355',1,'']]],
  ['loadextension_20函数_19',['loadExtension 函数',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md66',1,'']]],
  ['loadextension_20extensiondir_3a_20string_20_3a_20extension_20null_20',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['loadextensions_20函数_21',['loadExtensions 函数',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md64',1,'']]],
  ['loadextensions_20workspacedir_3a_20string_20process_20cwd_20_3a_20extension_22',['loadExtensions(workspaceDir: string = process.cwd()): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'']]],
  ['loadextensionsfromdir_20函数_23',['loadExtensionsFromDir 函数',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md65',1,'']]],
  ['loadextensionsfromdir_20dir_3a_20string_20_3a_20extension_24',['loadExtensionsFromDir(dir: string): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'']]],
  ['loadhierarchicalgeminimemory_25',['loadHierarchicalGeminiMemory()',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md283',1,'']]],
  ['loadsandboxconfig_26',['loadSandboxConfig',['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html#autotoc_md332',1,'']]],
  ['loadsettings_20函数_27',['loadSettings 函数',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md75',1,'']]],
  ['loadsettings_20workspacedir_3a_20string_20process_20cwd_20_3a_20loadedsettings_28',['loadSettings(workspaceDir: string = process.cwd()): LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'']]],
  ['loaduserextensions_20_3a_20extension_29',['loadUserExtensions(): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md300',1,'']]],
  ['local_20development_30',['Local Development',['../md_packages_2vscode-ide-companion_2development.html',1,'']]],
  ['logapierror_31',['logApiError',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md835',1,'logApiError'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md774',1,'logApiError()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md808',1,'logApiError()']]],
  ['logapirequest_32',['logApiRequest',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md833',1,'logApiRequest'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md773',1,'logApiRequest()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md807',1,'logApiRequest()']]],
  ['logapiresponse_33',['logApiResponse',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md836',1,'logApiResponse'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md775',1,'logApiResponse()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md809',1,'logApiResponse()']]],
  ['logchatcompression_34',['logChatCompression',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md842',1,'']]],
  ['logcliconfiguration_35',['logCliConfiguration',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md829',1,'logCliConfiguration'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md770',1,'logCliConfiguration()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md803',1,'logCliConfiguration()']]],
  ['logcontentretry_36',['logContentRetry',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md846',1,'']]],
  ['logcontentretryfailure_37',['logContentRetryFailure',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md847',1,'']]],
  ['logconversationfinishedevent_38',['logConversationFinishedEvent',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md841',1,'']]],
  ['logentry_20接口_39',['LogEntry 接口',['../md_packages_2core_2src_2core_2logger.html#autotoc_md605',1,'']]],
  ['logfileoperation_40',['logFileOperation',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md832',1,'logFileOperation'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md806',1,'logFileOperation()']]],
  ['logflashfallback_41',['logFlashFallback',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md834',1,'']]],
  ['logger_20对象_42',['logger 对象',['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html#autotoc_md151',1,'']]],
  ['logger_20类_43',['Logger 类',['../md_packages_2core_2src_2core_2logger.html',1,'']]],
  ['logger_20ts_44',['src/utils/logger.ts',['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html',1,'']]],
  ['logger_2emd_45',['logger.md',['../logger_8md.html',1,'']]],
  ['logger_2etest_2ets_46',['logger.test.ts',['../logger_8test_8ts.html',1,'']]],
  ['logger_2ets_47',['logger.ts',['../a2a-server_2src_2utils_2logger_8ts.html',1,'(Global Namespace)'],['../core_2src_2core_2logger_8ts.html',1,'(Global Namespace)'],['../vscode-ide-companion_2src_2utils_2logger_8ts.html',1,'(Global Namespace)']]],
  ['logger_2ets_2emd_48',['logger.ts.md',['../logger_8ts_8md.html',1,'']]],
  ['loggers_49',['Telemetry Loggers',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html',1,'']]],
  ['loggers_20ts_50',['遥测日志记录器 (loggers.ts)',['../md_packages_2core_2src_2telemetry_2loggers.html',1,'']]],
  ['loggers_2emd_51',['loggers.md',['../loggers_8md.html',1,'']]],
  ['loggers_2etest_2ecircular_2ets_52',['loggers.test.circular.ts',['../loggers_8test_8circular_8ts.html',1,'']]],
  ['loggers_2etest_2ets_53',['loggers.test.ts',['../loggers_8test_8ts.html',1,'']]],
  ['loggers_2ets_54',['loggers.ts',['../loggers_8ts.html',1,'']]],
  ['loggers_2ets_2emd_55',['loggers.ts.md',['../loggers_8ts_8md.html',1,'']]],
  ['logging_20functions_56',['Logging Functions',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md828',1,'Event Logging Functions'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md794',1,'Logging Functions']]],
  ['loggingcontentgenerator_2ets_57',['loggingContentGenerator.ts',['../logging_content_generator_8ts.html',1,'']]],
  ['logideconnection_58',['logIdeConnection',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md840',1,'']]],
  ['loginvalidchunk_59',['logInvalidChunk',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md845',1,'']]],
  ['logkittysequenceoverflow_60',['logKittySequenceOverflow',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md843',1,'']]],
  ['logloopdetected_61',['logLoopDetected',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md837',1,'']]],
  ['logmalformedjsonresponse_62',['logMalformedJsonResponse',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md844',1,'']]],
  ['lognextspeakercheck_63',['logNextSpeakerCheck',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md838',1,'']]],
  ['logslashcommand_64',['logSlashCommand',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md839',1,'']]],
  ['logtoolcall_65',['logToolCall',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md831',1,'logToolCall'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md772',1,'logToolCall()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md805',1,'logToolCall()']]],
  ['loguserprompt_66',['logUserPrompt',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md830',1,'logUserPrompt'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md771',1,'logUserPrompt()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md804',1,'logUserPrompt()']]],
  ['loopdetectedevent_67',['LoopDetectedEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md892',1,'']]],
  ['loopdetectionservice_2etest_2ets_68',['loopDetectionService.test.ts',['../loop_detection_service_8test_8ts.html',1,'']]],
  ['loopdetectionservice_2ets_69',['loopDetectionService.ts',['../loop_detection_service_8ts.html',1,'']]],
  ['looptype_70',['LoopType',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md908',1,'']]],
  ['lrucache_2ets_71',['LruCache.ts',['../_lru_cache_8ts.html',1,'']]],
  ['ls_2etest_2ets_72',['ls.test.ts',['../ls_8test_8ts.html',1,'']]],
  ['ls_2ets_73',['ls.ts',['../ls_8ts.html',1,'']]]
];
