var searchData=
[
  ['ui_20上下文_0',['UI 上下文',['../md_packages_2cli_2src_2ui_2_app_container_8tsx.html#autotoc_md422',1,'']]],
  ['ui_20尺寸常量_1',['UI 尺寸常量',['../md_packages_2cli_2src_2ui_2constants_8ts.html#autotoc_md452',1,'']]],
  ['ui_20状态_2',['UI 状态',['../md_packages_2cli_2src_2ui_2_app_container_8tsx.html#autotoc_md432',1,'']]],
  ['ui_20组件_3',['UI 组件',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md183',1,'']]],
  ['ui_20遥测集成_4',['UI 遥测集成',['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md820',1,'']]],
  ['ui_20telemetry_5',['UI Telemetry',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md799',1,'']]],
  ['uitelemetry_2etest_2ets_6',['uiTelemetry.test.ts',['../ui_telemetry_8test_8ts.html',1,'']]],
  ['uitelemetry_2ets_7',['uiTelemetry.ts',['../ui_telemetry_8ts.html',1,'']]],
  ['undefined_20_3a_20dnsresolutionorder_8',['validateDnsResolutionOrder(order: string | undefined): DnsResolutionOrder',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md383',1,'']]],
  ['undefined_20_3a_20promise_9',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['under_20active_20development_10',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['uninstall_2etest_2ets_11',['uninstall.test.ts',['../uninstall_8test_8ts.html',1,'']]],
  ['uninstall_2ets_12',['uninstall.ts',['../uninstall_8ts.html',1,'']]],
  ['uninstallcommand_13',['uninstallCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md202',1,'']]],
  ['uninstallextension_20extensionname_3a_20string_20cwd_3a_20string_20process_20cwd_20_3a_20promise_14',['uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'']]],
  ['update_2ets_15',['update.ts',['../update_8ts.html',1,'']]],
  ['updatecheck_2etest_2ets_16',['updateCheck.test.ts',['../update_check_8test_8ts.html',1,'']]],
  ['updatecheck_2ets_17',['updateCheck.ts',['../update_check_8ts.html',1,'']]],
  ['updatecoderagentcardurl_20函数_18',['updateCoderAgentCardUrl 函数',['../md_packages_2a2a-server_2src_2http_2app_8ts.html#autotoc_md90',1,'']]],
  ['updatecommand_19',['updateCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md204',1,'']]],
  ['updateeventemitter_2ets_20',['updateEventEmitter.ts',['../update_event_emitter_8ts.html',1,'']]],
  ['updateextension_20extension_3a_20extension_20cwd_3a_20string_20process_20cwd_20_3a_20promise_21',['updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&amp;lt;ExtensionUpdateInfo&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'']]],
  ['useatcompletion_2etest_2ets_22',['useAtCompletion.test.ts',['../use_at_completion_8test_8ts.html',1,'']]],
  ['useatcompletion_2ets_23',['useAtCompletion.ts',['../use_at_completion_8ts.html',1,'']]],
  ['useauth_2ets_24',['useAuth.ts',['../use_auth_8ts.html',1,'']]],
  ['useautoacceptindicator_2etest_2ets_25',['useAutoAcceptIndicator.test.ts',['../use_auto_accept_indicator_8test_8ts.html',1,'']]],
  ['useautoacceptindicator_2ets_26',['useAutoAcceptIndicator.ts',['../use_auto_accept_indicator_8ts.html',1,'']]],
  ['usebracketedpaste_2ets_27',['useBracketedPaste.ts',['../use_bracketed_paste_8ts.html',1,'']]],
  ['usecommandcompletion_2etest_2ets_28',['useCommandCompletion.test.ts',['../use_command_completion_8test_8ts.html',1,'']]],
  ['usecompletion_2ets_29',['useCompletion.ts',['../use_completion_8ts.html',1,'']]],
  ['useconsolemessages_2etest_2ets_30',['useConsoleMessages.test.ts',['../use_console_messages_8test_8ts.html',1,'']]],
  ['useconsolemessages_2ets_31',['useConsoleMessages.ts',['../use_console_messages_8ts.html',1,'']]],
  ['useeditorsettings_2etest_2ets_32',['useEditorSettings.test.ts',['../use_editor_settings_8test_8ts.html',1,'']]],
  ['useeditorsettings_2ets_33',['useEditorSettings.ts',['../use_editor_settings_8ts.html',1,'']]],
  ['usefocus_2etest_2ets_34',['useFocus.test.ts',['../use_focus_8test_8ts.html',1,'']]],
  ['usefocus_2ets_35',['useFocus.ts',['../use_focus_8ts.html',1,'']]],
  ['usefoldertrust_2etest_2ets_36',['useFolderTrust.test.ts',['../use_folder_trust_8test_8ts.html',1,'']]],
  ['usefoldertrust_2ets_37',['useFolderTrust.ts',['../use_folder_trust_8ts.html',1,'']]],
  ['usegeministream_2ets_38',['useGeminiStream.ts',['../use_gemini_stream_8ts.html',1,'']]],
  ['usegitbranchname_2etest_2ets_39',['useGitBranchName.test.ts',['../use_git_branch_name_8test_8ts.html',1,'']]],
  ['usegitbranchname_2ets_40',['useGitBranchName.ts',['../use_git_branch_name_8ts.html',1,'']]],
  ['usehistorymanager_2etest_2ets_41',['useHistoryManager.test.ts',['../use_history_manager_8test_8ts.html',1,'']]],
  ['usehistorymanager_2ets_42',['useHistoryManager.ts',['../use_history_manager_8ts.html',1,'']]],
  ['useidetrustlistener_2ets_43',['useIdeTrustListener.ts',['../use_ide_trust_listener_8ts.html',1,'']]],
  ['useinputhistory_2etest_2ets_44',['useInputHistory.test.ts',['../use_input_history_8test_8ts.html',1,'']]],
  ['useinputhistory_2ets_45',['useInputHistory.ts',['../use_input_history_8ts.html',1,'']]],
  ['useinputhistorystore_2etest_2ets_46',['useInputHistoryStore.test.ts',['../use_input_history_store_8test_8ts.html',1,'']]],
  ['useinputhistorystore_2ets_47',['useInputHistoryStore.ts',['../use_input_history_store_8ts.html',1,'']]],
  ['usekeypress_2etest_2ets_48',['useKeypress.test.ts',['../use_keypress_8test_8ts.html',1,'']]],
  ['usekeypress_2ets_49',['useKeypress.ts',['../use_keypress_8ts.html',1,'']]],
  ['usekittykeyboardprotocol_2ets_50',['useKittyKeyboardProtocol.ts',['../use_kitty_keyboard_protocol_8ts.html',1,'']]],
  ['useloadingindicator_2etest_2ets_51',['useLoadingIndicator.test.ts',['../use_loading_indicator_8test_8ts.html',1,'']]],
  ['useloadingindicator_2ets_52',['useLoadingIndicator.ts',['../use_loading_indicator_8ts.html',1,'']]],
  ['uselogger_2ets_53',['useLogger.ts',['../use_logger_8ts.html',1,'']]],
  ['usemessagequeue_2etest_2ets_54',['useMessageQueue.test.ts',['../use_message_queue_8test_8ts.html',1,'']]],
  ['usemessagequeue_2ets_55',['useMessageQueue.ts',['../use_message_queue_8ts.html',1,'']]],
  ['usephrasecycler_2etest_2ets_56',['usePhraseCycler.test.ts',['../use_phrase_cycler_8test_8ts.html',1,'']]],
  ['usephrasecycler_2ets_57',['usePhraseCycler.ts',['../use_phrase_cycler_8ts.html',1,'']]],
  ['useprivacysettings_2etest_2ets_58',['usePrivacySettings.test.ts',['../use_privacy_settings_8test_8ts.html',1,'']]],
  ['useprivacysettings_2ets_59',['usePrivacySettings.ts',['../use_privacy_settings_8ts.html',1,'']]],
  ['usepromptcompletion_2ets_60',['usePromptCompletion.ts',['../use_prompt_completion_8ts.html',1,'']]],
  ['useraccountmanager_2etest_2ets_61',['userAccountManager.test.ts',['../user_account_manager_8test_8ts.html',1,'']]],
  ['useraccountmanager_2ets_62',['userAccountManager.ts',['../user_account_manager_8ts.html',1,'']]],
  ['usereacttoolscheduler_2ets_63',['useReactToolScheduler.ts',['../use_react_tool_scheduler_8ts.html',1,'']]],
  ['userefreshmemorycommand_2ets_64',['useRefreshMemoryCommand.ts',['../use_refresh_memory_command_8ts.html',1,'']]],
  ['userpromptevent_65',['UserPromptEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md885',1,'']]],
  ['userstartupwarnings_2etest_2ets_66',['userStartupWarnings.test.ts',['../user_startup_warnings_8test_8ts.html',1,'']]],
  ['userstartupwarnings_2ets_67',['userStartupWarnings.ts',['../user_startup_warnings_8ts.html',1,'']]],
  ['usesettingscommand_2ets_68',['useSettingsCommand.ts',['../use_settings_command_8ts.html',1,'']]],
  ['useshellhistory_2etest_2ets_69',['useShellHistory.test.ts',['../use_shell_history_8test_8ts.html',1,'']]],
  ['useshellhistory_2ets_70',['useShellHistory.ts',['../use_shell_history_8ts.html',1,'']]],
  ['useshowmemorycommand_2ets_71',['useShowMemoryCommand.ts',['../use_show_memory_command_8ts.html',1,'']]],
  ['useslashcompletion_2etest_2ets_72',['useSlashCompletion.test.ts',['../use_slash_completion_8test_8ts.html',1,'']]],
  ['useslashcompletion_2ets_73',['useSlashCompletion.ts',['../use_slash_completion_8ts.html',1,'']]],
  ['usestateandref_2ets_74',['useStateAndRef.ts',['../use_state_and_ref_8ts.html',1,'']]],
  ['useterminalsize_2ets_75',['useTerminalSize.ts',['../use_terminal_size_8ts.html',1,'']]],
  ['usethemecommand_2ets_76',['useThemeCommand.ts',['../use_theme_command_8ts.html',1,'']]],
  ['usetimer_2etest_2ets_77',['useTimer.test.ts',['../use_timer_8test_8ts.html',1,'']]],
  ['usetimer_2ets_78',['useTimer.ts',['../use_timer_8ts.html',1,'']]],
  ['usetoolscheduler_2etest_2ets_79',['useToolScheduler.test.ts',['../use_tool_scheduler_8test_8ts.html',1,'']]],
  ['useworkspacemigration_2ets_80',['useWorkspaceMigration.ts',['../use_workspace_migration_8ts.html',1,'']]],
  ['utility_81',['Diff Options Utility',['../md_packages_2core_2src_2tools_2diff_options_8ts.html',1,'']]],
  ['utility_20functions_82',['Utility Functions',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1021',1,'']]],
  ['utils_83',['测试工具 (test-utils)',['../md_packages_2core_2src_2test-utils_2index.html',1,'']]],
  ['utils_20logger_20ts_84',['src/utils/logger.ts',['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html',1,'']]]
];
