var searchData=
[
  ['e2e_20测试套件_0',['E2E 测试套件',['../md_packages_2a2a-server_2src_2http_2app_8test_8ts.html#autotoc_md82',1,'']]],
  ['edit_2emd_1',['edit.md',['../edit_8md.html',1,'']]],
  ['edit_2etest_2ets_2',['edit.test.ts',['../edit_8test_8ts.html',1,'']]],
  ['edit_2ets_3',['edit.ts',['../edit_8ts.html',1,'']]],
  ['editcorrector_2etest_2ets_4',['editCorrector.test.ts',['../edit_corrector_8test_8ts.html',1,'']]],
  ['editcorrector_2ets_5',['editCorrector.ts',['../edit_corrector_8ts.html',1,'']]],
  ['editor_2etest_2ets_6',['editor.test.ts',['../editor_8test_8ts.html',1,'']]],
  ['editor_2ets_7',['editor.ts',['../editor_8ts.html',1,'']]],
  ['editorcommand_2etest_2ets_8',['editorCommand.test.ts',['../editor_command_8test_8ts.html',1,'']]],
  ['editorcommand_2ets_9',['editorCommand.ts',['../editor_command_8ts.html',1,'']]],
  ['editorsettingsmanager_2ets_10',['editorSettingsManager.ts',['../editor_settings_manager_8ts.html',1,'']]],
  ['edittool_20类_11',['EditTool 类',['../md_packages_2core_2src_2tools_2edit.html',1,'EditTool 类'],['../md_packages_2core_2src_2tools_2edit.html#autotoc_md943',1,'EditTool 类']]],
  ['edittoolinvocation_20类_12',['EditToolInvocation 类',['../md_packages_2core_2src_2tools_2edit.html#autotoc_md944',1,'']]],
  ['edittoolparams_20接口_13',['EditToolParams 接口',['../md_packages_2core_2src_2tools_2edit.html#autotoc_md942',1,'']]],
  ['emptystreamerror_20类_14',['EmptyStreamError 类',['../md_packages_2core_2src_2core_2gemini_chat.html#autotoc_md598',1,'']]],
  ['enable_2ets_15',['enable.ts',['../enable_8ts.html',1,'']]],
  ['enablecommand_16',['enableCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md206',1,'']]],
  ['enabledextensionnames_20workspacedir_20_3a_20geminicliextension_17',['annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'']]],
  ['enableextension_20name_3a_20string_20scopes_3a_20settingscope_18',['enableExtension(name: string, scopes: SettingScope[])',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'']]],
  ['encodetagname_19',['encodeTagName()',['../md_packages_2core_2src_2core_2logger.html#autotoc_md607',1,'']]],
  ['endpoints_20test_20ts_20',['endpoints.test.ts',['../md_packages_2a2a-server_2src_2http_2endpoints_8test_8ts.html',1,'']]],
  ['endpoints_2etest_2ets_21',['endpoints.test.ts',['../endpoints_8test_8ts.html',1,'']]],
  ['endpoints_2etest_2ets_2emd_22',['endpoints.test.ts.md',['../endpoints_8test_8ts_8md.html',1,'']]],
  ['endsessionevent_23',['EndSessionEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md884',1,'']]],
  ['ensurebucketinitialized_24',['&lt;span class=&quot;tt&quot;&gt;ensureBucketInitialized&lt;/span&gt;',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md129',1,'']]],
  ['enumerations_25',['Enumerations',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md535',1,'Enumerations'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md788',1,'Enumerations'],['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1018',1,'Enumerations']]],
  ['envfilepath_3a_20string_20null_20_3a_20void_26',['setUpCloudShellEnvironment(envFilePath: string | null): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md357',1,'']]],
  ['environment_20configuration_27',['Environment Configuration',['../md_packages_2core_2test-setup_8ts.html#autotoc_md1058',1,'']]],
  ['environmentcontext_2etest_2ets_28',['environmentContext.test.ts',['../environment_context_8test_8ts.html',1,'']]],
  ['environmentcontext_2ets_29',['environmentContext.ts',['../environment_context_8ts.html',1,'']]],
  ['envvarresolver_2etest_2ets_30',['envVarResolver.test.ts',['../env_var_resolver_8test_8ts.html',1,'']]],
  ['envvarresolver_2ets_31',['envVarResolver.ts',['../env_var_resolver_8ts.html',1,'']]],
  ['epipe_20错误_32',['EPIPE 错误',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md415',1,'']]],
  ['error_20handling_33',['Error Handling',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md985',1,'']]],
  ['errorparsing_2etest_2ets_34',['errorParsing.test.ts',['../error_parsing_8test_8ts.html',1,'']]],
  ['errorparsing_2ets_35',['errorParsing.ts',['../error_parsing_8ts.html',1,'']]],
  ['errorreporting_2etest_2ets_36',['errorReporting.test.ts',['../error_reporting_8test_8ts.html',1,'']]],
  ['errorreporting_2ets_37',['errorReporting.ts',['../error_reporting_8ts.html',1,'']]],
  ['errors_2emd_38',['errors.md',['../errors_8md.html',1,'']]],
  ['errors_2ets_39',['errors.ts',['../cli_2src_2utils_2errors_8ts.html',1,'(Global Namespace)'],['../core_2src_2utils_2errors_8ts.html',1,'(Global Namespace)']]],
  ['escapepath_40',['特殊字符转义 (escapePath)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1054',1,'']]],
  ['event_20constants_41',['Event Constants',['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md762',1,'']]],
  ['event_20creation_20functions_42',['Event Creation Functions',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md796',1,'']]],
  ['event_20logging_20functions_43',['Event Logging Functions',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md828',1,'']]],
  ['event_20types_44',['Event Types',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md795',1,'']]],
  ['event_2dmetadata_2dkey_2ets_45',['event-metadata-key.ts',['../event-metadata-key_8ts.html',1,'']]],
  ['events_2ets_46',['events.ts',['../events_8ts.html',1,'']]],
  ['example_20interaction_20flow_47',['A. Example Interaction Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md12',1,'']]],
  ['example_2ets_48',['example.ts',['../example_8ts.html',1,'']]],
  ['execute_49',['execute',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md924',1,'执行函数 (execute)'],['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md32',1,'<span class="tt">execute</span>'],['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md748',1,'execute()']]],
  ['executewithpty_50',['executeWithPty()',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md749',1,'']]],
  ['executor_20ts_51',['src/agent/executor.ts',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html',1,'']]],
  ['executor_2ets_52',['executor.ts',['../executor_8ts.html',1,'']]],
  ['executor_2ets_2emd_53',['executor.ts.md',['../executor_8ts_8md.html',1,'']]],
  ['experimental_20and_20under_20active_20development_54',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['exports_55',['Exports',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md792',1,'Exports'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md798',1,'OpenTelemetry Exports']]],
  ['exports_56',['Re-exports',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md555',1,'']]],
  ['extension_57',['Extension',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md293',1,'Extension'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'loadExtensions(workspaceDir: string = process.cwd()): Extension[]'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'loadExtensionsFromDir(dir: string): Extension[]'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md300',1,'loadUserExtensions(): Extension[]'],['../md_packages_2a2a-server_2development-extension-rfc.html',1,'RFC: Gemini CLI A2A Development-Tool Extension'],['../md_packages_2vscode-ide-companion_2development.html#autotoc_md1068',1,'Running the Extension']]],
  ['extension_58',['3. The &lt;span class=&quot;tt&quot;&gt;development-tool&lt;/span&gt; extension',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md6',1,'']]],
  ['extension_20接口_59',['Extension 接口',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md61',1,'']]],
  ['extension_20_3a_20promise_60',['performWorkspaceExtensionMigration(extensions: Extension[]): Promise&amp;lt;string[]&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md311',1,'']]],
  ['extension_20_3a_20string_61',['Extension : string',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['extension_20cwd_3a_20string_20process_20cwd_20_3a_20promise_62',['updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&amp;lt;ExtensionUpdateInfo&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'']]],
  ['extension_20name_63',['Extension Name',['../md_packages_2core_2src_2ide_2constants_8ts.html#autotoc_md639',1,'']]],
  ['extension_20null_64',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['extension_20ts_65',['extension ts',['../md_packages_2cli_2src_2config_2extension_8ts.html',1,'extension.ts'],['../md_packages_2a2a-server_2src_2config_2extension_8ts.html',1,'src/config/extension.ts']]],
  ['extension_2etest_2ets_66',['extension.test.ts',['../cli_2src_2config_2extension_8test_8ts.html',1,'(Global Namespace)'],['../vscode-ide-companion_2src_2extension_8test_8ts.html',1,'(Global Namespace)']]],
  ['extension_2ets_67',['extension.ts',['../a2a-server_2src_2config_2extension_8ts.html',1,'(Global Namespace)'],['../cli_2src_2config_2extension_8ts.html',1,'(Global Namespace)'],['../vscode-ide-companion_2src_2extension_8ts.html',1,'(Global Namespace)']]],
  ['extension_2ets_2emd_68',['extension.ts.md',['../a2a-server_2src_2config_2extension_8ts_8md.html',1,'(Global Namespace)'],['../cli_2src_2config_2extension_8ts_8md.html',1,'(Global Namespace)']]],
  ['extension_3a_20extension_20_3a_20string_69',['extension: Extension : string',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['extension_3a_20extension_20cwd_3a_20string_20process_20cwd_20_3a_20promise_70',['updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&amp;lt;ExtensionUpdateInfo&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'']]],
  ['extensionconfig_71',['ExtensionConfig',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md294',1,'']]],
  ['extensionconfig_20接口_72',['ExtensionConfig 接口',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md62',1,'']]],
  ['extensiondir_3a_20string_20_3a_20extension_20null_73',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['extensioninstallmetadata_74',['ExtensionInstallMetadata',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md295',1,'']]],
  ['extensioninstallmetadata_20cwd_3a_20string_20process_20cwd_20_3a_20promise_75',['installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&amp;lt;string&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'']]],
  ['extensionname_3a_20string_20cwd_3a_20string_20process_20cwd_20_3a_20promise_76',['uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'']]],
  ['extensions_20enabledextensionnames_20workspacedir_20_3a_20geminicliextension_77',['annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'']]],
  ['extensions_20sessionid_20argv_20cwd_78',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['extensions_20tsx_79',['extensions.tsx',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html',1,'']]],
  ['extensions_2etsx_2emd_80',['extensions.tsx.md',['../extensions_8tsx_8md.html',1,'']]],
  ['extensions_3a_20extension_20_3a_20promise_81',['performWorkspaceExtensionMigration(extensions: Extension[]): Promise&amp;lt;string[]&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md311',1,'']]],
  ['extensions_5fconfig_5ffilename_82',['EXTENSIONS_CONFIG_FILENAME',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md314',1,'']]],
  ['extensions_5fdirectory_5fname_83',['EXTENSIONS_DIRECTORY_NAME',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md313',1,'']]],
  ['extensionscommand_2etest_2ets_84',['extensionsCommand.test.ts',['../extensions_command_8test_8ts.html',1,'']]],
  ['extensionscommand_2ets_85',['extensionsCommand.ts',['../extensions_command_8ts.html',1,'']]],
  ['extensionscommand_3a_20commandmodule_86',['extensionsCommand: CommandModule',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md199',1,'']]],
  ['extensionstorage_87',['ExtensionStorage',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md297',1,'']]]
];
