var searchData=
[
  ['package_20is_20experimental_20and_20under_20active_20development_0',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['package_2ets_1',['package.ts',['../package_8ts.html',1,'']]],
  ['parsearguments_20settings_3a_20settings_20_3a_20promise_2',['parseArguments(settings: Settings): Promise&amp;lt;CliArgs&amp;gt;',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md282',1,'']]],
  ['parseotlpendpoint_3',['parseOtlpEndpoint',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md874',1,'parseOtlpEndpoint'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md858',1,'parseOtlpEndpoint()']]],
  ['parseresponsedata_4',['响应数据解析 (parseResponseData)',['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1041',1,'']]],
  ['partutils_2etest_2ets_5',['partUtils.test.ts',['../part_utils_8test_8ts.html',1,'']]],
  ['partutils_2ets_6',['partUtils.ts',['../part_utils_8ts.html',1,'']]],
  ['pathreader_2etest_2ets_7',['pathReader.test.ts',['../path_reader_8test_8ts.html',1,'']]],
  ['pathreader_2ets_8',['pathReader.ts',['../path_reader_8ts.html',1,'']]],
  ['paths_9',['Paths',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md569',1,'Global Directory Paths'],['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md571',1,'Project-Specific Paths']]],
  ['paths_2emd_10',['paths.md',['../paths_8md.html',1,'']]],
  ['paths_2etest_2ets_11',['paths.test.ts',['../paths_8test_8ts.html',1,'']]],
  ['paths_2ets_12',['paths.ts',['../paths_8ts.html',1,'']]],
  ['performinitialauth_20config_3a_20config_20authtype_3a_20authtype_20undefined_20_3a_20promise_13',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['performworkspaceextensionmigration_20extensions_3a_20extension_20_3a_20promise_14',['performWorkspaceExtensionMigration(extensions: Extension[]): Promise&amp;lt;string[]&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md311',1,'']]],
  ['persistence_20gcs_20ts_15',['src/persistence/gcs.ts',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html',1,'']]],
  ['pkce_20保护_16',['PKCE 保护',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md691',1,'']]],
  ['pkce_20流程_17',['PKCE 流程',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md679',1,'']]],
  ['platformconstants_2ets_18',['platformConstants.ts',['../platform_constants_8ts.html',1,'']]],
  ['posix_20支持_19',['POSIX 支持',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md758',1,'']]],
  ['principles_20',['General Principles',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html#autotoc_md211',1,'']]],
  ['privacy_20notice_21',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['privacycommand_2etest_2ets_22',['privacyCommand.test.ts',['../privacy_command_8test_8ts.html',1,'']]],
  ['privacycommand_2ets_23',['privacyCommand.ts',['../privacy_command_8ts.html',1,'']]],
  ['private_20methods_24',['Private Methods',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md572',1,'']]],
  ['process_20cwd_25',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['process_20cwd_20_3a_20extension_26',['loadExtensions(workspaceDir: string = process.cwd()): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'']]],
  ['process_20cwd_20_3a_20loadedsettings_27',['loadSettings(workspaceDir: string = process.cwd()): LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'']]],
  ['process_20cwd_20_3a_20promise_28',['process cwd : Promise',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]],
  ['process_20management_29',['Process Management',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md984',1,'']]],
  ['process_2dutils_2etest_2ets_30',['process-utils.test.ts',['../process-utils_8test_8ts.html',1,'']]],
  ['process_2dutils_2ets_31',['process-utils.ts',['../process-utils_8ts.html',1,'']]],
  ['project_20specific_20paths_32',['Project-Specific Paths',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md571',1,'']]],
  ['promise_33',['Promise',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'getServerStatus(serverName: string, server: MCPServerConfig): Promise&lt;MCPServerStatus&gt;'],['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'initializeApp(config: Config, settings: LoadedSettings): Promise&lt;InitializationResult&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md248',1,'listMcpServers(): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md282',1,'parseArguments(settings: Settings): Promise&lt;CliArgs&gt;'],['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'performInitialAuth(config: Config, authType: AuthType | undefined): Promise&lt;string | null&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md311',1,'performWorkspaceExtensionMigration(extensions: Extension[]): Promise&lt;string[]&gt;'],['../md_packages_2cli_2src_2utils_2read_stdin_8ts.html#autotoc_md461',1,'readStdin(): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'runNonInteractive(config: Config, input: string, prompt_id: string): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'testMCPConnection(serverName: string, config: MCPServerConfig): Promise&lt;MCPServerStatus&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]],
  ['promises_2ets_34',['promises.ts',['../promises_8ts.html',1,'']]],
  ['prompt_2dregistry_2emd_35',['prompt-registry.md',['../prompt-registry_8md.html',1,'']]],
  ['prompt_2dregistry_2ets_36',['prompt-registry.ts',['../prompt-registry_8ts.html',1,'']]],
  ['prompt_5fid_3a_20string_20_3a_20promise_37',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['promptregistry_38',['提示词注册表 (PromptRegistry)',['../md_packages_2core_2src_2prompts_2prompt-registry.html',1,'']]],
  ['prompts_2emd_39',['prompts.md',['../prompts_8md.html',1,'']]],
  ['prompts_2etest_2ets_40',['prompts.test.ts',['../prompts_8test_8ts.html',1,'']]],
  ['prompts_2ets_41',['prompts.ts',['../prompts_8ts.html',1,'']]]
];
