var searchData=
[
  ['task_20类_0',['Task 类',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html#autotoc_md42',1,'']]],
  ['task_20test_20ts_1',['task.test.ts',['../md_packages_2a2a-server_2src_2agent_2task_8test_8ts.html',1,'']]],
  ['task_20ts_2',['src/agent/task.ts',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html',1,'']]],
  ['task_2etest_2ets_3',['task.test.ts',['../task_8test_8ts.html',1,'']]],
  ['task_2etest_2ets_2emd_4',['task.test.ts.md',['../task_8test_8ts_8md.html',1,'']]],
  ['task_2ets_5',['task.ts',['../task_8ts.html',1,'']]],
  ['task_2ets_2emd_6',['task.ts.md',['../task_8ts_8md.html',1,'']]],
  ['taskwrapper_20类_7',['TaskWrapper 类',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md20',1,'']]],
  ['telemetry_8',['UI Telemetry',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md799',1,'']]],
  ['telemetry_20constants_9',['Telemetry Constants',['../md_packages_2core_2src_2telemetry_2constants_8ts.html',1,'']]],
  ['telemetry_20index_10',['Telemetry Index',['../md_packages_2core_2src_2telemetry_2index_8ts.html',1,'']]],
  ['telemetry_20loggers_11',['Telemetry Loggers',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html',1,'']]],
  ['telemetry_20sdk_12',['Telemetry SDK',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html',1,'']]],
  ['telemetry_2dutils_2etest_2ets_13',['telemetry-utils.test.ts',['../telemetry-utils_8test_8ts.html',1,'']]],
  ['telemetry_2dutils_2ets_14',['telemetry-utils.ts',['../telemetry-utils_8ts.html',1,'']]],
  ['telemetry_2etest_2ets_15',['telemetry.test.ts',['../telemetry_8test_8ts.html',1,'']]],
  ['telemetryinitialized_16',['telemetryInitialized',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md853',1,'']]],
  ['telemetrysettings_17',['TelemetrySettings',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md543',1,'']]],
  ['telemetrysettings_20接口_18',['TelemetrySettings 接口',['../md_packages_2core_2src_2config_2config.html#autotoc_md527',1,'']]],
  ['telemetrytarget_19',['TelemetryTarget',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md789',1,'']]],
  ['telemetrytarget_20枚举_20',['TelemetryTarget 枚举',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md766',1,'']]],
  ['terminalsetup_2ets_21',['terminalSetup.ts',['../terminal_setup_8ts.html',1,'']]],
  ['terminalsetupcommand_2etest_2ets_22',['terminalSetupCommand.test.ts',['../terminal_setup_command_8test_8ts.html',1,'']]],
  ['terminalsetupcommand_2ets_23',['terminalSetupCommand.ts',['../terminal_setup_command_8ts.html',1,'']]],
  ['terms_20of_20service_20and_20privacy_20notice_24',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['test_20setup_25',['Core Test Setup',['../md_packages_2core_2test-setup_8ts.html',1,'']]],
  ['test_20setup_20ts_26',['test-setup.ts',['../md_packages_2cli_2test-setup_8ts.html',1,'']]],
  ['test_20ts_27',['test ts',['../md_packages_2a2a-server_2src_2http_2app_8test_8ts.html',1,'app.test.ts'],['../md_packages_2a2a-server_2src_2http_2endpoints_8test_8ts.html',1,'endpoints.test.ts'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html',1,'gcs.test.ts'],['../md_packages_2a2a-server_2src_2agent_2task_8test_8ts.html',1,'task.test.ts']]],
  ['test_20utils_28',['测试工具 (test-utils)',['../md_packages_2core_2src_2test-utils_2index.html',1,'']]],
  ['test_2dsetup_2ets_29',['test-setup.ts',['../cli_2test-setup_8ts.html',1,'(Global Namespace)'],['../core_2test-setup_8ts.html',1,'(Global Namespace)']]],
  ['test_2dsetup_2ets_2emd_30',['test-setup.ts.md',['../cli_2test-setup_8ts_8md.html',1,'(Global Namespace)'],['../core_2test-setup_8ts_8md.html',1,'(Global Namespace)']]],
  ['testing_5futils_20ts_31',['testing_utils.ts',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html',1,'']]],
  ['testing_5futils_2ets_32',['testing_utils.ts',['../testing__utils_8ts.html',1,'']]],
  ['testing_5futils_2ets_2emd_33',['testing_utils.ts.md',['../testing__utils_8ts_8md.html',1,'']]],
  ['testmcpconnection_20servername_3a_20string_20config_3a_20mcpserverconfig_20_3a_20promise_34',['testMCPConnection(serverName: string, config: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'']]],
  ['tests_35',['Running Tests',['../md_packages_2vscode-ide-companion_2development.html#autotoc_md1069',1,'']]],
  ['testutils_2ets_36',['testUtils.ts',['../test_utils_8ts.html',1,'']]],
  ['text_2dbuffer_2etest_2ets_37',['text-buffer.test.ts',['../text-buffer_8test_8ts.html',1,'']]],
  ['text_2dbuffer_2ets_38',['text-buffer.ts',['../text-buffer_8ts.html',1,'']]],
  ['textconstants_2ets_39',['textConstants.ts',['../text_constants_8ts.html',1,'']]],
  ['textutils_2ets_40',['textUtils.ts',['../cli_2src_2ui_2utils_2text_utils_8ts.html',1,'(Global Namespace)'],['../core_2src_2utils_2text_utils_8ts.html',1,'(Global Namespace)']]],
  ['the_20development_20tool_20extension_41',['3. The &lt;span class=&quot;tt&quot;&gt;development-tool&lt;/span&gt; extension',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md6',1,'']]],
  ['the_20extension_42',['Running the Extension',['../md_packages_2vscode-ide-companion_2development.html#autotoc_md1068',1,'']]],
  ['theme_2dmanager_2etest_2ets_43',['theme-manager.test.ts',['../theme-manager_8test_8ts.html',1,'']]],
  ['theme_2dmanager_2ets_44',['theme-manager.ts',['../theme-manager_8ts.html',1,'']]],
  ['theme_2etest_2ets_45',['theme.test.ts',['../theme_8test_8ts.html',1,'']]],
  ['theme_2ets_46',['theme.ts',['../core_2theme_8ts.html',1,'(Global Namespace)'],['../ui_2themes_2theme_8ts.html',1,'(Global Namespace)']]],
  ['themecommand_2etest_2ets_47',['themeCommand.test.ts',['../theme_command_8test_8ts.html',1,'']]],
  ['themecommand_2ets_48',['themeCommand.ts',['../theme_command_8ts.html',1,'']]],
  ['thinking_20mode_49',['Thinking Mode',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md562',1,'']]],
  ['this_20package_20is_20experimental_20and_20under_20active_20development_50',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['tofriendlyerror_51',['友好错误转换 (toFriendlyError)',['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1040',1,'']]],
  ['token_20计数_52',['Token 计数',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md500',1,'']]],
  ['token_20限制管理_53',['Token 限制管理',['../md_packages_2core_2src_2core_2token_limits.html',1,'']]],
  ['tokenlimit_54',['tokenLimit()',['../md_packages_2core_2src_2core_2token_limits.html#autotoc_md621',1,'']]],
  ['tokenlimits_2emd_55',['tokenLimits.md',['../token_limits_8md.html',1,'']]],
  ['tokenlimits_2ets_56',['tokenLimits.ts',['../token_limits_8ts.html',1,'']]],
  ['tool_20discovery_57',['Tool Discovery',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md982',1,'Dynamic Tool Discovery'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md978',1,'Tool Discovery']]],
  ['tool_20extension_58',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['tool_20extension_59',['3. The &lt;span class=&quot;tt&quot;&gt;development-tool&lt;/span&gt; extension',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md6',1,'']]],
  ['tool_20management_60',['Tool Management',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md977',1,'']]],
  ['tool_20registry_61',['Tool Registry',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html',1,'']]],
  ['tool_2dcall_2ddecision_2ets_62',['tool-call-decision.ts',['../tool-call-decision_8ts.html',1,'']]],
  ['tool_2derror_2ets_63',['tool-error.ts',['../tool-error_8ts.html',1,'']]],
  ['tool_2dregistry_2etest_2ets_64',['tool-registry.test.ts',['../tool-registry_8test_8ts.html',1,'']]],
  ['tool_2dregistry_2ets_65',['tool-registry.ts',['../tool-registry_8ts.html',1,'']]],
  ['tool_2dregistry_2ets_2emd_66',['tool-registry.ts.md',['../tool-registry_8ts_8md.html',1,'']]],
  ['tool_2dutils_2etest_2ets_67',['tool-utils.test.ts',['../tool-utils_8test_8ts.html',1,'']]],
  ['tool_2dutils_2ets_68',['tool-utils.ts',['../tool-utils_8ts.html',1,'']]],
  ['toolbuilder_69',['ToolBuilder',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1005',1,'']]],
  ['toolbuilder_20接口_70',['ToolBuilder 接口',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md990',1,'']]],
  ['toolcallconfirmationdetails_71',['ToolCallConfirmationDetails',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1015',1,'']]],
  ['toolcallconfirmationdetails_20类型_72',['ToolCallConfirmationDetails 类型',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md995',1,'']]],
  ['toolcallevent_73',['ToolCallEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md886',1,'']]],
  ['toolcallrecord_74',['ToolCallRecord',['../md_packages_2core_2src_2services_2chat_recording_service.html#autotoc_md717',1,'']]],
  ['toolconfirmationoutcome_75',['ToolConfirmationOutcome',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1019',1,'']]],
  ['toolconfirmationoutcome_20枚举_76',['ToolConfirmationOutcome 枚举',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md998',1,'']]],
  ['toolconfirmationpayload_77',['ToolConfirmationPayload',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1016',1,'']]],
  ['toolinvocation_78',['ToolInvocation',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1004',1,'']]],
  ['toolinvocation_20接口_79',['ToolInvocation 接口',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md989',1,'']]],
  ['toollocation_80',['ToolLocation',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1017',1,'']]],
  ['toolregistry_81',['ToolRegistry',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md976',1,'']]],
  ['toolresult_82',['ToolResult',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1006',1,'']]],
  ['toolresult_20接口_83',['ToolResult 接口',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md994',1,'']]],
  ['toolresultdisplay_84',['ToolResultDisplay',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1012',1,'']]],
  ['tools_20framework_85',['Tools Framework',['../md_packages_2core_2src_2tools_2tools_8ts.html',1,'']]],
  ['tools_2emd_86',['tools.md',['../tools_8md.html',1,'']]],
  ['tools_2etest_2ets_87',['tools.test.ts',['../tools_8test_8ts.html',1,'']]],
  ['tools_2ets_88',['tools.ts',['../test-utils_2tools_8ts.html',1,'(Global Namespace)'],['../tools_2tools_8ts.html',1,'(Global Namespace)']]],
  ['tools_2ets_2emd_89',['tools.ts.md',['../tools_8ts_8md.html',1,'']]],
  ['toolscommand_2etest_2ets_90',['toolsCommand.test.ts',['../tools_command_8test_8ts.html',1,'']]],
  ['toolscommand_2ets_91',['toolsCommand.ts',['../tools_command_8ts.html',1,'']]],
  ['tooutputstring_20extension_3a_20extension_20_3a_20string_92',['toOutputString extension: Extension : string',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['truncation_20defaults_93',['Truncation Defaults',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md551',1,'']]],
  ['trustedfolders_2etest_2ets_94',['trustedFolders.test.ts',['../trusted_folders_8test_8ts.html',1,'']]],
  ['trustedfolders_2ets_95',['trustedFolders.ts',['../trusted_folders_8ts.html',1,'']]],
  ['ts_96',['ts',['../md_packages_2core_2src_2telemetry_2types.html',1,'遥测事件类型 (types.ts)'],['../md_packages_2core_2src_2telemetry_2loggers.html',1,'遥测日志记录器 (loggers.ts)'],['../md_packages_2core_2src_2telemetry_2sdk.html',1,'遥测 SDK (sdk.ts)'],['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html',1,'add.ts'],['../md_packages_2a2a-server_2src_2http_2app_8test_8ts.html',1,'app.test.ts'],['../md_packages_2cli_2src_2config_2auth_8ts.html',1,'auth.ts'],['../md_packages_2cli_2src_2core_2auth_8ts.html',1,'auth.ts'],['../md_packages_2cli_2src_2ui_2colors_8ts.html',1,'colors.ts'],['../md_packages_2cli_2src_2config_2config_8ts.html',1,'config.ts'],['../md_packages_2cli_2src_2ui_2constants_8ts.html',1,'constants.ts'],['../md_packages_2a2a-server_2src_2http_2endpoints_8test_8ts.html',1,'endpoints.test.ts'],['../md_packages_2cli_2src_2config_2extension_8ts.html',1,'extension.ts'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html',1,'gcs.test.ts'],['../md_packages_2a2a-server_2index_8ts.html',1,'index.ts'],['../md_packages_2cli_2index_8ts.html',1,'index.ts'],['../md_packages_2cli_2src_2core_2initializer_8ts.html',1,'initializer.ts'],['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html',1,'install.ts'],['../md_packages_2cli_2src_2config_2key_bindings_8ts.html',1,'keyBindings.ts'],['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html',1,'list.ts'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html',1,'list.ts'],['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html',1,'mcp.ts'],['../md_packages_2cli_2src_2non_interactive_cli_8ts.html',1,'nonInteractiveCli.ts'],['../md_packages_2cli_2src_2utils_2read_stdin_8ts.html',1,'readStdin.ts'],['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html',1,'remove.ts'],['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html',1,'sandboxConfig.ts'],['../md_packages_2a2a-server_2src_2http_2server_8ts.html',1,'server.ts'],['../md_packages_2cli_2src_2config_2settings_8ts.html',1,'settings.ts'],['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html',1,'src/agent/executor.ts'],['../md_packages_2a2a-server_2src_2agent_2task_8ts.html',1,'src/agent/task.ts'],['../md_packages_2a2a-server_2src_2config_2config_8ts.html',1,'src/config/config.ts'],['../md_packages_2a2a-server_2src_2config_2extension_8ts.html',1,'src/config/extension.ts'],['../md_packages_2a2a-server_2src_2config_2settings_8ts.html',1,'src/config/settings.ts'],['../md_packages_2a2a-server_2src_2http_2app_8ts.html',1,'src/http/app.ts'],['../md_packages_2a2a-server_2src_2http_2request_storage_8ts.html',1,'src/http/requestStorage.ts'],['../md_packages_2a2a-server_2src_2index_8ts.html',1,'src/index.ts'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html',1,'src/persistence/gcs.ts'],['../md_packages_2a2a-server_2src_2types_8ts.html',1,'src/types.ts'],['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html',1,'src/utils/logger.ts'],['../md_packages_2a2a-server_2src_2agent_2task_8test_8ts.html',1,'task.test.ts'],['../md_packages_2cli_2test-setup_8ts.html',1,'test-setup.ts'],['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html',1,'testing_utils.ts'],['../md_packages_2a2a-server_2vitest_8config_8ts.html',1,'vitest.config.ts'],['../md_packages_2cli_2vitest_8config_8ts.html',1,'vitest.config.ts'],['../md_packages_2core_2vitest_8config_8ts.html',1,'vitest.config.ts']]],
  ['tsx_97',['tsx',['../md_packages_2cli_2src_2ui_2_app_container_8tsx.html',1,'AppContainer.tsx'],['../md_packages_2cli_2src_2commands_2extensions_8tsx.html',1,'extensions.tsx'],['../md_packages_2cli_2src_2gemini_8tsx.html',1,'gemini.tsx']]],
  ['turn_20类和相关类型_98',['Turn 类和相关类型',['../md_packages_2core_2src_2core_2turn.html',1,'']]],
  ['turn_20类_99',['Turn 类',['../md_packages_2core_2src_2core_2turn.html#autotoc_md626',1,'']]],
  ['turn_2emd_100',['turn.md',['../turn_8md.html',1,'']]],
  ['turn_2etest_2ets_101',['turn.test.ts',['../turn_8test_8ts.html',1,'']]],
  ['turn_2ets_102',['turn.ts',['../turn_8ts.html',1,'']]],
  ['type_20aliases_103',['Type Aliases',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1025',1,'']]],
  ['type_20definitions_104',['Type Definitions',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md552',1,'Type Definitions'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md797',1,'Type Definitions'],['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1011',1,'Type Definitions']]],
  ['type_20guards_105',['Type Guards',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1023',1,'']]],
  ['types_106',['Event Types',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md795',1,'']]],
  ['types_20ts_107',['types ts',['../md_packages_2core_2src_2telemetry_2types.html',1,'遥测事件类型 (types.ts)'],['../md_packages_2a2a-server_2src_2types_8ts.html',1,'src/types.ts']]],
  ['types_2emd_108',['types.md',['../types_8md.html',1,'']]],
  ['types_2ets_109',['types.ts',['../a2a-server_2src_2types_8ts.html',1,'(Global Namespace)'],['../cli_2src_2services_2prompt-processors_2types_8ts.html',1,'(Global Namespace)'],['../cli_2src_2services_2types_8ts.html',1,'(Global Namespace)'],['../cli_2src_2ui_2commands_2types_8ts.html',1,'(Global Namespace)'],['../cli_2src_2ui_2types_8ts.html',1,'(Global Namespace)'],['../core_2src_2code__assist_2types_8ts.html',1,'(Global Namespace)'],['../core_2src_2mcp_2token-storage_2types_8ts.html',1,'(Global Namespace)'],['../core_2src_2telemetry_2types_8ts.html',1,'(Global Namespace)']]],
  ['types_2ets_2emd_110',['types.ts.md',['../types_8ts_8md.html',1,'']]]
];
