var searchData=
[
  ['ide_20客户端_20ideclient_0',['IDE 客户端 (IdeClient)',['../md_packages_2core_2src_2ide_2ide-client.html',1,'']]],
  ['ide_20相关事件_1',['IDE 相关事件',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md897',1,'']]],
  ['ide_20constants_2',['IDE Constants',['../md_packages_2core_2src_2ide_2constants_8ts.html',1,'']]],
  ['ide_2dclient_2emd_3',['ide-client.md',['../ide-client_8md.html',1,'']]],
  ['ide_2dclient_2etest_2ets_4',['ide-client.test.ts',['../ide-client_8test_8ts.html',1,'']]],
  ['ide_2dclient_2ets_5',['ide-client.ts',['../ide-client_8ts.html',1,'']]],
  ['ide_2dinstaller_2etest_2ets_6',['ide-installer.test.ts',['../ide-installer_8test_8ts.html',1,'']]],
  ['ide_2dinstaller_2ets_7',['ide-installer.ts',['../ide-installer_8ts.html',1,'']]],
  ['ide_2dserver_2etest_2ets_8',['ide-server.test.ts',['../ide-server_8test_8ts.html',1,'']]],
  ['ide_2dserver_2ets_9',['ide-server.ts',['../ide-server_8ts.html',1,'']]],
  ['ide_2dtrust_2ets_10',['ide-trust.ts',['../ide-trust_8ts.html',1,'']]],
  ['ideclient_11',['IDE 客户端 (IdeClient)',['../md_packages_2core_2src_2ide_2ide-client.html',1,'']]],
  ['idecommand_2etest_2ets_12',['ideCommand.test.ts',['../ide_command_8test_8ts.html',1,'']]],
  ['idecommand_2ets_13',['ideCommand.ts',['../ide_command_8ts.html',1,'']]],
  ['ideconnectionevent_14',['IdeConnectionEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md898',1,'']]],
  ['ideconnectionstate_15',['IDEConnectionState',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md644',1,'']]],
  ['ideconnectionstatus_20枚举_16',['IDEConnectionStatus 枚举',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md645',1,'']]],
  ['ideconnectiontype_17',['IdeConnectionType',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md910',1,'']]],
  ['idecontext_2etest_2ets_18',['ideContext.test.ts',['../ide_context_8test_8ts.html',1,'']]],
  ['idecontext_2ets_19',['ideContext.ts',['../ide_context_8ts.html',1,'']]],
  ['ignore_2etest_2ets_20',['ignore.test.ts',['../ignore_8test_8ts.html',1,'']]],
  ['ignore_2ets_21',['ignore.ts',['../ignore_8ts.html',1,'']]],
  ['ignorepatterns_2etest_2ets_22',['ignorePatterns.test.ts',['../ignore_patterns_8test_8ts.html',1,'']]],
  ['ignorepatterns_2ets_23',['ignorePatterns.ts',['../ignore_patterns_8ts.html',1,'']]],
  ['in_20this_20package_20is_20experimental_20and_20under_20active_20development_24',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['index_25',['Telemetry Index',['../md_packages_2core_2src_2telemetry_2index_8ts.html',1,'']]],
  ['index_20ts_26',['index ts',['../md_packages_2a2a-server_2index_8ts.html',1,'index.ts'],['../md_packages_2cli_2index_8ts.html',1,'index.ts'],['../md_packages_2a2a-server_2src_2index_8ts.html',1,'src/index.ts']]],
  ['index_2emd_27',['index.md',['../telemetry_2index_8md.html',1,'(Global Namespace)'],['../test-utils_2index_8md.html',1,'(Global Namespace)']]],
  ['index_2etest_2ets_28',['index.test.ts',['../index_8test_8ts.html',1,'']]],
  ['index_2ets_29',['index.ts',['../a2a-server_2index_8ts.html',1,'(Global Namespace)'],['../a2a-server_2src_2index_8ts.html',1,'(Global Namespace)'],['../cli_2index_8ts.html',1,'(Global Namespace)'],['../core_2index_8ts.html',1,'(Global Namespace)'],['../core_2src_2index_8ts.html',1,'(Global Namespace)'],['../core_2src_2telemetry_2index_8ts.html',1,'(Global Namespace)'],['../core_2src_2test-utils_2index_8ts.html',1,'(Global Namespace)'],['../test-utils_2index_8ts.html',1,'(Global Namespace)'],['../test-utils_2src_2index_8ts.html',1,'(Global Namespace)']]],
  ['index_2ets_2emd_30',['index.ts.md',['../a2a-server_2index_8ts_8md.html',1,'(Global Namespace)'],['../a2a-server_2src_2index_8ts_8md.html',1,'(Global Namespace)'],['../cli_2index_8ts_8md.html',1,'(Global Namespace)'],['../core_2src_2telemetry_2index_8ts_8md.html',1,'(Global Namespace)']]],
  ['initcommand_2etest_2ets_31',['initCommand.test.ts',['../init_command_8test_8ts.html',1,'']]],
  ['initcommand_2ets_32',['initCommand.ts',['../init_command_8ts.html',1,'']]],
  ['initializationresult_33',['InitializationResult',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md374',1,'']]],
  ['initializationresult_34',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['initializeapp_20config_3a_20config_20settings_3a_20loadedsettings_20_3a_20promise_35',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['initializebucket_36',['&lt;span class=&quot;tt&quot;&gt;initializeBucket&lt;/span&gt;',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md128',1,'']]],
  ['initializer_20ts_37',['initializer.ts',['../md_packages_2cli_2src_2core_2initializer_8ts.html',1,'']]],
  ['initializer_2ets_38',['initializer.ts',['../initializer_8ts.html',1,'']]],
  ['initializer_2ets_2emd_39',['initializer.ts.md',['../initializer_8ts_8md.html',1,'']]],
  ['initializetelemetry_40',['initializeTelemetry',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md875',1,'initializeTelemetry'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md767',1,'initializeTelemetry()'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md855',1,'initializeTelemetry()']]],
  ['initializingcomponent_41',['InitializingComponent',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md390',1,'']]],
  ['injectionparser_2etest_2ets_42',['injectionParser.test.ts',['../injection_parser_8test_8ts.html',1,'']]],
  ['injectionparser_2ets_43',['injectionParser.ts',['../injection_parser_8ts.html',1,'']]],
  ['ink_20library_20screen_20reader_20guidance_44',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]],
  ['input_3a_20string_20prompt_5fid_3a_20string_20_3a_20promise_45',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['install_20ts_46',['install.ts',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html',1,'']]],
  ['install_2etest_2ets_47',['install.test.ts',['../install_8test_8ts.html',1,'']]],
  ['install_2ets_48',['install.ts',['../install_8ts.html',1,'']]],
  ['install_2ets_2emd_49',['install.ts.md',['../install_8ts_8md.html',1,'']]],
  ['install_5fmetadata_5ffilename_50',['INSTALL_METADATA_FILENAME',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md315',1,'']]],
  ['installargs_51',['handleInstall(args: InstallArgs)',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md215',1,'']]],
  ['installationinfo_2etest_2ets_52',['installationInfo.test.ts',['../installation_info_8test_8ts.html',1,'']]],
  ['installationinfo_2ets_53',['installationInfo.ts',['../installation_info_8ts.html',1,'']]],
  ['installationmanager_2etest_2ets_54',['installationManager.test.ts',['../installation_manager_8test_8ts.html',1,'']]],
  ['installationmanager_2ets_55',['installationManager.ts',['../installation_manager_8ts.html',1,'']]],
  ['installcommand_56',['installCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md201',1,'']]],
  ['installcommand_3a_20commandmodule_57',['installCommand: CommandModule',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md216',1,'']]],
  ['installextension_20installmetadata_3a_20extensioninstallmetadata_20cwd_3a_20string_20process_20cwd_20_3a_20promise_58',['installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&amp;lt;string&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'']]],
  ['installmetadata_3a_20extensioninstallmetadata_20cwd_3a_20string_20process_20cwd_20_3a_20promise_59',['installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&amp;lt;string&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'']]],
  ['instance_20methods_60',['Instance Methods',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md570',1,'']]],
  ['integration_61',['Integration',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md848',1,'Integration'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md980',1,'MCP Integration'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md983',1,'MCP Server Integration']]],
  ['integration_2etest_2ecircular_2ets_62',['integration.test.circular.ts',['../integration_8test_8circular_8ts.html',1,'']]],
  ['interaction_20flow_63',['A. Example Interaction Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md12',1,'']]],
  ['interfaces_64',['Interfaces',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1003',1,'Core Interfaces'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md538',1,'Interfaces']]],
  ['introduction_65',['1. Introduction',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md1',1,'']]],
  ['invalidchunkevent_66',['InvalidChunkEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md904',1,'']]],
  ['is_20experimental_20and_20under_20active_20development_67',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['is_2din_2dci_2ets_68',['is-in-ci.ts',['../is-in-ci_8ts.html',1,'']]],
  ['isnarrowwidth_2ets_69',['isNarrowWidth.ts',['../is_narrow_width_8ts.html',1,'']]],
  ['isnodeerror_70',['错误类型检查 (isNodeError)',['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1038',1,'']]],
  ['issubpath_71',['子路径检查 (isSubpath)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1056',1,'']]],
  ['istelemetrysdkinitialized_72',['isTelemetrySdkInitialized',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md873',1,'isTelemetrySdkInitialized'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md857',1,'isTelemetrySdkInitialized()']]],
  ['istool_73',['isTool',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1024',1,'isTool'],['../md_packages_2core_2src_2tools_2tools.html#autotoc_md1001',1,'isTool()']]]
];
