var searchData=
[
  ['gcs_20test_20ts_0',['gcs.test.ts',['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html',1,'']]],
  ['gcs_20ts_1',['src/persistence/gcs.ts',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html',1,'']]],
  ['gcs_2etest_2ets_2',['gcs.test.ts',['../gcs_8test_8ts.html',1,'']]],
  ['gcs_2etest_2ets_2emd_3',['gcs.test.ts.md',['../gcs_8test_8ts_8md.html',1,'']]],
  ['gcs_2ets_4',['gcs.ts',['../gcs_8ts.html',1,'']]],
  ['gcs_2ets_2emd_5',['gcs.ts.md',['../gcs_8ts_8md.html',1,'']]],
  ['gcstaskstore_20测试套件_6',['GCSTaskStore 测试套件',['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html#autotoc_md118',1,'']]],
  ['gcstaskstore_20类_7',['GCSTaskStore 类',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md125',1,'']]],
  ['gemini_20cli_20代码说明文档索引_8',['Gemini CLI 代码说明文档索引',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md175',1,'']]],
  ['gemini_20cli_20a2a_20development_20tool_20extension_9',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['gemini_20cli_20a2a_20server_10',['Gemini CLI A2A Server',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md16',1,'']]],
  ['gemini_20cli_20companion_11',['Gemini CLI Companion',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1070',1,'']]],
  ['gemini_20tsx_12',['gemini.tsx',['../md_packages_2cli_2src_2gemini_8tsx.html',1,'']]],
  ['gemini_2emd_13',['GEMINI.md',['../_g_e_m_i_n_i_8md.html',1,'']]],
  ['gemini_2etsx_2emd_14',['gemini.tsx.md',['../gemini_8tsx_8md.html',1,'']]],
  ['gemini_5fcli_5fcompanion_5fextension_5fname_15',['GEMINI_CLI_COMPANION_EXTENSION_NAME',['../md_packages_2core_2src_2ide_2constants_8ts.html#autotoc_md640',1,'']]],
  ['gemini_5fdir_16',['GEMINI_DIR',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1048',1,'']]],
  ['geminichat_20类_17',['GeminiChat 类',['../md_packages_2core_2src_2core_2gemini_chat.html',1,'']]],
  ['geminichat_2emd_18',['geminiChat.md',['../gemini_chat_8md.html',1,'']]],
  ['geminichat_2etest_2ets_19',['geminiChat.test.ts',['../gemini_chat_8test_8ts.html',1,'']]],
  ['geminichat_2ets_20',['geminiChat.ts',['../gemini_chat_8ts.html',1,'']]],
  ['geminiclient_20类_21',['GeminiClient 类',['../md_packages_2core_2src_2core_2client.html',1,'']]],
  ['geminicliextension_22',['GeminiCLIExtension',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md554',1,'GeminiCLIExtension']]],
  ['geminieventtype_20枚举_23',['GeminiEventType 枚举',['../md_packages_2core_2src_2core_2turn.html#autotoc_md631',1,'']]],
  ['geminirequest_2ets_24',['geminiRequest.ts',['../gemini_request_8ts.html',1,'']]],
  ['general_20principles_25',['General Principles',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html#autotoc_md211',1,'']]],
  ['generatecontentresponseutilities_2etest_2ets_26',['generateContentResponseUtilities.test.ts',['../generate_content_response_utilities_8test_8ts.html',1,'']]],
  ['generatecontentresponseutilities_2ets_27',['generateContentResponseUtilities.ts',['../generate_content_response_utilities_8ts.html',1,'']]],
  ['getallprompts_28',['getAllPrompts()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md697',1,'']]],
  ['getalltasks_29',['&lt;span class=&quot;tt&quot;&gt;getAllTasks&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md30',1,'']]],
  ['getcitations_30',['getCitations()',['../md_packages_2core_2src_2core_2turn.html#autotoc_md637',1,'']]],
  ['getcodeassistserver_31',['getCodeAssistServer()',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md488',1,'']]],
  ['getcommonattributes_32',['getCommonAttributes',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md827',1,'getCommonAttributes'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md811',1,'getCommonAttributes()']]],
  ['getcompressionprompt_33',['getCompressionPrompt()',['../md_packages_2core_2src_2core_2prompts.html#autotoc_md612',1,'']]],
  ['getconfig_34',['&lt;span class=&quot;tt&quot;&gt;getConfig&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md26',1,'']]],
  ['getcontextfilenames_20函数_35',['getContextFileNames 函数',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md67',1,'']]],
  ['getcoresystemprompt_36',['getCoreSystemPrompt()',['../md_packages_2core_2src_2core_2prompts.html#autotoc_md611',1,'']]],
  ['getdiffstat_37',['getDiffStat',['../md_packages_2core_2src_2tools_2diff_options_8ts.html#autotoc_md938',1,'']]],
  ['geterrormessage_38',['错误消息提取 (getErrorMessage)',['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1039',1,'']]],
  ['getfolderstructure_2etest_2ets_39',['getFolderStructure.test.ts',['../get_folder_structure_8test_8ts.html',1,'']]],
  ['getfolderstructure_2ets_40',['getFolderStructure.ts',['../get_folder_structure_8ts.html',1,'']]],
  ['getinstance_41',['getInstance()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md647',1,'']]],
  ['getmcpserversfromconfig_42',['getMcpServersFromConfig()',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md245',1,'']]],
  ['getmetadata_43',['&lt;span class=&quot;tt&quot;&gt;getMetadata&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html#autotoc_md47',1,'']]],
  ['getnodememoryargs_20config_3a_20config_20_3a_20string_44',['getNodeMemoryArgs(config: Config): string[]',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'']]],
  ['getobjectpath_45',['&lt;span class=&quot;tt&quot;&gt;getObjectPath&lt;/span&gt;',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md130',1,'']]],
  ['getprojecthash_46',['项目哈希 (getProjectHash)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1055',1,'']]],
  ['getprompt_47',['getPrompt()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md698',1,'']]],
  ['getpromptsbyserver_48',['getPromptsByServer()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md699',1,'']]],
  ['getpty_2ets_49',['getPty.ts',['../get_pty_8ts.html',1,'']]],
  ['getsandboxcommand_20内部函数_50',['getSandboxCommand (内部函数)',['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html#autotoc_md333',1,'']]],
  ['getserverstatus_20servername_3a_20string_20server_3a_20mcpserverconfig_20_3a_20promise_51',['getServerStatus(serverName: string, server: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'']]],
  ['gettask_52',['&lt;span class=&quot;tt&quot;&gt;getTask&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md29',1,'']]],
  ['gettmparchivefilename_20函数_53',['getTmpArchiveFilename 函数',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md141',1,'']]],
  ['getvalidtoken_54',['getValidToken()',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md674',1,'']]],
  ['git_20仓库_55',['Git 仓库',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md218',1,'']]],
  ['github_2ddark_2ets_56',['github-dark.ts',['../github-dark_8ts.html',1,'']]],
  ['github_2dlight_2ets_57',['github-light.ts',['../github-light_8ts.html',1,'']]],
  ['gitignoreparser_2etest_2ets_58',['gitIgnoreParser.test.ts',['../git_ignore_parser_8test_8ts.html',1,'']]],
  ['gitignoreparser_2ets_59',['gitIgnoreParser.ts',['../git_ignore_parser_8ts.html',1,'']]],
  ['gitservice_2etest_2ets_60',['gitService.test.ts',['../git_service_8test_8ts.html',1,'']]],
  ['gitservice_2ets_61',['gitService.ts',['../git_service_8ts.html',1,'']]],
  ['gitutils_2etest_2ets_62',['gitUtils.test.ts',['../git_utils_8test_8ts.html',1,'']]],
  ['gitutils_2ets_63',['gitUtils.ts',['../cli_2src_2utils_2git_utils_8ts.html',1,'(Global Namespace)'],['../core_2src_2utils_2git_utils_8ts.html',1,'(Global Namespace)']]],
  ['glob_2etest_2ets_64',['glob.test.ts',['../glob_8test_8ts.html',1,'']]],
  ['glob_2ets_65',['glob.ts',['../glob_8ts.html',1,'']]],
  ['global_20directory_20paths_66',['Global Directory Paths',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md569',1,'']]],
  ['global_20variables_67',['Global Variables',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md871',1,'']]],
  ['google_2dauth_2dprovider_2etest_2ets_68',['google-auth-provider.test.ts',['../google-auth-provider_8test_8ts.html',1,'']]],
  ['google_2dauth_2dprovider_2ets_69',['google-auth-provider.ts',['../google-auth-provider_8ts.html',1,'']]],
  ['google_5faccounts_5ffilename_70',['GOOGLE_ACCOUNTS_FILENAME',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1049',1,'']]],
  ['googlecode_2ets_71',['googlecode.ts',['../googlecode_8ts.html',1,'']]],
  ['grep_2etest_2ets_72',['grep.test.ts',['../grep_8test_8ts.html',1,'']]],
  ['grep_2ets_73',['grep.ts',['../grep_8ts.html',1,'']]],
  ['guards_74',['Type Guards',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1023',1,'']]],
  ['guidance_75',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]]
];
