var searchData=
[
  ['debugging_0',['Debugging',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md878',1,'']]],
  ['declarativetool_1',['DeclarativeTool',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1009',1,'']]],
  ['declarativetool_20抽象类_2',['DeclarativeTool 抽象类',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md991',1,'']]],
  ['decodetagname_3',['decodeTagName()',['../md_packages_2core_2src_2core_2logger.html#autotoc_md608',1,'']]],
  ['default_20models_4',['Default Models',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md557',1,'']]],
  ['default_20values_5',['Default Values',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md791',1,'']]],
  ['default_5fdiff_5foptions_6',['DEFAULT_DIFF_OPTIONS',['../md_packages_2core_2src_2tools_2diff_options_8ts.html#autotoc_md936',1,'']]],
  ['default_5fexcluded_5fenv_5fvars_7',['DEFAULT_EXCLUDED_ENV_VARS',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md361',1,'']]],
  ['default_5fgemini_5fembedding_5fmodel_8',['DEFAULT_GEMINI_EMBEDDING_MODEL',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md561',1,'']]],
  ['default_5fgemini_5fflash_5flite_5fmodel_9',['DEFAULT_GEMINI_FLASH_LITE_MODEL',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md560',1,'']]],
  ['default_5fgemini_5fflash_5fmodel_10',['DEFAULT_GEMINI_FLASH_MODEL',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md559',1,'']]],
  ['default_5fgemini_5fmodel_11',['DEFAULT_GEMINI_MODEL',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md558',1,'']]],
  ['default_5fthinking_5fmode_12',['DEFAULT_THINKING_MODE',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md563',1,'']]],
  ['default_5ftoken_5flimit_13',['DEFAULT_TOKEN_LIMIT',['../md_packages_2core_2src_2core_2token_limits.html#autotoc_md623',1,'']]],
  ['defaultkeybindings_14',['defaultKeyBindings',['../md_packages_2cli_2src_2config_2key_bindings_8ts.html#autotoc_md326',1,'']]],
  ['defaults_15',['Defaults',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md550',1,'File Filtering Defaults'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md551',1,'Truncation Defaults']]],
  ['definitions_16',['Definitions',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md8',1,'3.2 Schema Definitions'],['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md9',1,'3.3 Method Definitions'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md552',1,'Type Definitions'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md797',1,'Type Definitions'],['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1011',1,'Type Definitions']]],
  ['dependencies_17',['Dependencies',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md877',1,'Dependencies'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md986',1,'Dependencies']]],
  ['development_18',['Local Development',['../md_packages_2vscode-ide-companion_2development.html',1,'']]],
  ['development_19',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['development_20tool_20extension_20',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['development_20tool_20extension_21',['3. The &lt;span class=&quot;tt&quot;&gt;development-tool&lt;/span&gt; extension',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md6',1,'']]],
  ['diff_20options_20utility_22',['Diff Options Utility',['../md_packages_2core_2src_2tools_2diff_options_8ts.html',1,'']]],
  ['diffstat_23',['DiffStat',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1014',1,'']]],
  ['diffupdateresult_24',['DiffUpdateResult',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md660',1,'']]],
  ['dir_3a_20string_20_3a_20extension_25',['loadExtensionsFromDir(dir: string): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'']]],
  ['directory_20and_20file_20names_26',['Directory and File Names',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md566',1,'']]],
  ['directory_20paths_27',['Global Directory Paths',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md569',1,'']]],
  ['disablecommand_28',['disableCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md205',1,'']]],
  ['disableextension_20name_3a_20string_20scope_3a_20settingscope_20cwd_3a_20string_20process_20cwd_29',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['disconnect_30',['disconnect()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md651',1,'']]],
  ['discoveredtool_31',['DiscoveredTool',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md975',1,'']]],
  ['discoveredtoolinvocation_32',['DiscoveredToolInvocation',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md974',1,'']]],
  ['discovery_33',['Discovery',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md982',1,'Dynamic Tool Discovery'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md978',1,'Tool Discovery']]],
  ['dnsresolutionorder_34',['validateDnsResolutionOrder(order: string | undefined): DnsResolutionOrder',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md383',1,'']]],
  ['dynamic_20tool_20discovery_35',['Dynamic Tool Discovery',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md982',1,'']]]
];
