var searchData=
[
  ['re_20exports_0',['Re-exports',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md555',1,'']]],
  ['reader_20guidance_1',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]],
  ['readfiletool_20类_2',['ReadFileTool 类',['../md_packages_2core_2src_2tools_2read-file.html',1,'ReadFileTool 类'],['../md_packages_2core_2src_2tools_2read-file.html#autotoc_md954',1,'ReadFileTool 类']]],
  ['readfiletoolinvocation_20类_3',['ReadFileToolInvocation 类',['../md_packages_2core_2src_2tools_2read-file.html#autotoc_md955',1,'']]],
  ['readfiletoolparams_20接口_4',['ReadFileToolParams 接口',['../md_packages_2core_2src_2tools_2read-file.html#autotoc_md953',1,'']]],
  ['readstdin_20_3a_20promise_5',['readStdin(): Promise&amp;lt;string&amp;gt;',['../md_packages_2cli_2src_2utils_2read_stdin_8ts.html#autotoc_md461',1,'']]],
  ['readstdin_20ts_6',['readStdin.ts',['../md_packages_2cli_2src_2utils_2read_stdin_8ts.html',1,'']]],
  ['readtextfile_7',['文本文件读取 (readTextFile)',['../md_packages_2core_2src_2services_2file_system_service.html#autotoc_md733',1,'']]],
  ['reconstruct_8',['&lt;span class=&quot;tt&quot;&gt;reconstruct&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md27',1,'']]],
  ['record_9',['migrateSettingsToV1(v2Settings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt;',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md352',1,'']]],
  ['record_20_3a_20boolean_10',['needsMigration(settings: Record&amp;lt;string, unknown&amp;gt;): boolean',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md350',1,'']]],
  ['record_20_3a_20record_11',['migrateSettingsToV1(v2Settings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt;',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md352',1,'']]],
  ['record_20_3a_20record_20null_12',['migrateSettingsToV2(flatSettings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt; | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md351',1,'']]],
  ['record_20null_13',['migrateSettingsToV2(flatSettings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt; | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md351',1,'']]],
  ['recordapierrormetrics_14',['recordApiErrorMetrics',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md777',1,'recordApiErrorMetrics()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md816',1,'recordApiErrorMetrics()']]],
  ['recordapiresponsemetrics_15',['recordApiResponseMetrics',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md779',1,'recordApiResponseMetrics()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md818',1,'recordApiResponseMetrics()']]],
  ['recordfileoperationmetric_16',['recordFileOperationMetric()',['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md815',1,'']]],
  ['recordtokenusagemetrics_17',['recordTokenUsageMetrics',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md778',1,'recordTokenUsageMetrics()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md817',1,'recordTokenUsageMetrics()']]],
  ['recordtoolcallmetrics_18',['recordToolCallMetrics',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md780',1,'recordToolCallMetrics()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md814',1,'recordToolCallMetrics()']]],
  ['refreshaccesstoken_19',['refreshAccessToken()',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md675',1,'']]],
  ['registerprompt_20',['registerPrompt()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md696',1,'']]],
  ['registry_21',['Tool Registry',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html',1,'']]],
  ['relaunchwithadditionalargs_20additionalargs_3a_20string_22',['relaunchWithAdditionalArgs(additionalArgs: string[])',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md385',1,'']]],
  ['remove_20ts_23',['remove.ts',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html',1,'']]],
  ['removecommand_24',['removeCommand',['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md260',1,'']]],
  ['removecommand_3a_20commandmodule_25',['removeCommand: CommandModule',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md267',1,'']]],
  ['removemcpserver_20name_3a_20string_20options_3a_20scope_3a_20string_26',['removeMcpServer(name: string, options: { scope: string })',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'']]],
  ['removepromptsbyserver_27',['removePromptsByServer()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md701',1,'']]],
  ['requeststorage_20对象_28',['requestStorage 对象',['../md_packages_2a2a-server_2src_2http_2request_storage_8ts.html#autotoc_md102',1,'']]],
  ['requeststorage_20ts_29',['src/http/requestStorage.ts',['../md_packages_2a2a-server_2src_2http_2request_storage_8ts.html',1,'']]],
  ['requirements_30',['Requirements',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1072',1,'']]],
  ['resolveenvvarsinobject_20函数_31',['resolveEnvVarsInObject 函数',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md77',1,'']]],
  ['resolveenvvarsinstring_20函数_32',['resolveEnvVarsInString 函数',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md76',1,'']]],
  ['resolvepathfromenv_33',['resolvePathFromEnv()',['../md_packages_2core_2src_2core_2prompts.html#autotoc_md613',1,'']]],
  ['responses_20and_20notifications_34',['2.1 Asynchronous Responses and Notifications',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md5',1,'']]],
  ['rfc_3a_20gemini_20cli_20a2a_20development_20tool_20extension_35',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['running_20tests_36',['Running Tests',['../md_packages_2vscode-ide-companion_2development.html#autotoc_md1069',1,'']]],
  ['running_20the_20extension_37',['Running the Extension',['../md_packages_2vscode-ide-companion_2development.html#autotoc_md1068',1,'']]],
  ['runnoninteractive_20config_3a_20config_20input_3a_20string_20prompt_5fid_3a_20string_20_3a_20promise_38',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]]
];
