var searchData=
[
  ['ide_20客户端_20ideclient_0',['IDE 客户端 (IdeClient)',['../md_packages_2core_2src_2ide_2ide-client.html',1,'']]],
  ['ide_20相关事件_1',['IDE 相关事件',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md897',1,'']]],
  ['ide_20constants_2',['IDE Constants',['../md_packages_2core_2src_2ide_2constants_8ts.html',1,'']]],
  ['ideclient_3',['IDE 客户端 (IdeClient)',['../md_packages_2core_2src_2ide_2ide-client.html',1,'']]],
  ['ideconnectionevent_4',['IdeConnectionEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md898',1,'']]],
  ['ideconnectionstate_5',['IDEConnectionState',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md644',1,'']]],
  ['ideconnectionstatus_20枚举_6',['IDEConnectionStatus 枚举',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md645',1,'']]],
  ['ideconnectiontype_7',['IdeConnectionType',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md910',1,'']]],
  ['in_20this_20package_20is_20experimental_20and_20under_20active_20development_8',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['index_9',['Telemetry Index',['../md_packages_2core_2src_2telemetry_2index_8ts.html',1,'']]],
  ['index_20ts_10',['index ts',['../md_packages_2a2a-server_2index_8ts.html',1,'index.ts'],['../md_packages_2cli_2index_8ts.html',1,'index.ts'],['../md_packages_2a2a-server_2src_2index_8ts.html',1,'src/index.ts']]],
  ['initializationresult_11',['InitializationResult',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md374',1,'']]],
  ['initializationresult_12',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['initializeapp_20config_3a_20config_20settings_3a_20loadedsettings_20_3a_20promise_13',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['initializebucket_14',['&lt;span class=&quot;tt&quot;&gt;initializeBucket&lt;/span&gt;',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md128',1,'']]],
  ['initializer_20ts_15',['initializer.ts',['../md_packages_2cli_2src_2core_2initializer_8ts.html',1,'']]],
  ['initializetelemetry_16',['initializeTelemetry',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md875',1,'initializeTelemetry'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md767',1,'initializeTelemetry()'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md855',1,'initializeTelemetry()']]],
  ['initializingcomponent_17',['InitializingComponent',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md390',1,'']]],
  ['ink_20library_20screen_20reader_20guidance_18',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]],
  ['input_3a_20string_20prompt_5fid_3a_20string_20_3a_20promise_19',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['install_20ts_20',['install.ts',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html',1,'']]],
  ['install_5fmetadata_5ffilename_21',['INSTALL_METADATA_FILENAME',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md315',1,'']]],
  ['installargs_22',['handleInstall(args: InstallArgs)',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md215',1,'']]],
  ['installcommand_23',['installCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md201',1,'']]],
  ['installcommand_3a_20commandmodule_24',['installCommand: CommandModule',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md216',1,'']]],
  ['installextension_20installmetadata_3a_20extensioninstallmetadata_20cwd_3a_20string_20process_20cwd_20_3a_20promise_25',['installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&amp;lt;string&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'']]],
  ['installmetadata_3a_20extensioninstallmetadata_20cwd_3a_20string_20process_20cwd_20_3a_20promise_26',['installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&amp;lt;string&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'']]],
  ['instance_20methods_27',['Instance Methods',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md570',1,'']]],
  ['integration_28',['Integration',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md848',1,'Integration'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md980',1,'MCP Integration'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md983',1,'MCP Server Integration']]],
  ['interaction_20flow_29',['A. Example Interaction Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md12',1,'']]],
  ['interfaces_30',['Interfaces',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1003',1,'Core Interfaces'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md538',1,'Interfaces']]],
  ['introduction_31',['1. Introduction',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md1',1,'']]],
  ['invalidchunkevent_32',['InvalidChunkEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md904',1,'']]],
  ['is_20experimental_20and_20under_20active_20development_33',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['isnodeerror_34',['错误类型检查 (isNodeError)',['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1038',1,'']]],
  ['issubpath_35',['子路径检查 (isSubpath)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1056',1,'']]],
  ['istelemetrysdkinitialized_36',['isTelemetrySdkInitialized',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md873',1,'isTelemetrySdkInitialized'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md857',1,'isTelemetrySdkInitialized()']]],
  ['istool_37',['isTool',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1024',1,'isTool'],['../md_packages_2core_2src_2tools_2tools.html#autotoc_md1001',1,'isTool()']]]
];
