var searchData=
[
  ['sandboxcliargs_0',['SandboxCliArgs',['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html#autotoc_md335',1,'']]],
  ['sandboxconfig_1',['SandboxConfig',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md544',1,'']]],
  ['sandboxconfig_20ts_2',['sandboxConfig.ts',['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html',1,'']]],
  ['save_3',['save',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md131',1,'<span class="tt">save</span>'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md136',1,'<span class="tt">save</span>']]],
  ['savesettings_20settingsfile_3a_20settingsfile_20_3a_20void_4',['saveSettings(settingsFile: SettingsFile): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md349',1,'']]],
  ['scheduletoolcalls_20测试_5',['scheduleToolCalls 测试',['../md_packages_2a2a-server_2src_2agent_2task_8test_8ts.html#autotoc_md36',1,'']]],
  ['schema_20definitions_6',['3.2 Schema Definitions',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md8',1,'']]],
  ['schema_20management_7',['Schema Management',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md979',1,'']]],
  ['scope_3a_20settingscope_20cwd_3a_20string_20process_20cwd_8',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['scope_3a_20string_9',['removeMcpServer(name: string, options: { scope: string })',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'']]],
  ['scopes_3a_20settingscope_10',['enableExtension(name: string, scopes: SettingScope[])',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'']]],
  ['screen_20reader_20guidance_11',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]],
  ['sdk_12',['SDK',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md784',1,'OpenTelemetry SDK'],['../md_packages_2core_2src_2telemetry_2sdk_8ts.html',1,'Telemetry SDK']]],
  ['sdk_13',['sdk',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md852',1,'']]],
  ['sdk_20functions_14',['SDK Functions',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md793',1,'']]],
  ['sdk_20sdk_20ts_15',['遥测 SDK (sdk.ts)',['../md_packages_2core_2src_2telemetry_2sdk.html',1,'']]],
  ['sdk_20ts_16',['遥测 SDK (sdk.ts)',['../md_packages_2core_2src_2telemetry_2sdk.html',1,'']]],
  ['semanticresourceattributes_17',['SemanticResourceAttributes',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md864',1,'']]],
  ['separation_20of_20concerns_18',['4. Separation of Concerns',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md10',1,'']]],
  ['server_19',['Gemini CLI A2A Server',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md16',1,'']]],
  ['server_20integration_20',['MCP Server Integration',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md983',1,'']]],
  ['server_20ts_21',['server.ts',['../md_packages_2a2a-server_2src_2http_2server_8ts.html',1,'']]],
  ['server_3a_20mcpserverconfig_20_3a_20promise_22',['getServerStatus(serverName: string, server: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'']]],
  ['servergeministreamevent_23',['ServerGeminiStreamEvent',['../md_packages_2core_2src_2core_2turn.html#autotoc_md633',1,'']]],
  ['servername_3a_20string_20config_3a_20mcpserverconfig_20_3a_20promise_24',['testMCPConnection(serverName: string, config: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'']]],
  ['servername_3a_20string_20server_3a_20mcpserverconfig_20_3a_20promise_25',['getServerStatus(serverName: string, server: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'']]],
  ['service_20and_20privacy_20notice_26',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['service_20name_27',['Service Name',['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md760',1,'']]],
  ['service_5fname_28',['SERVICE_NAME',['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md761',1,'']]],
  ['sessionid_20argv_20cwd_29',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['settargetdir_20函数_30',['setTargetDir 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md56',1,'']]],
  ['settings_31',['Settings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md344',1,'']]],
  ['settings_20接口_32',['Settings 接口',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md71',1,'']]],
  ['settings_20_3a_20promise_33',['parseArguments(settings: Settings): Promise&amp;lt;CliArgs&amp;gt;',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md282',1,'']]],
  ['settings_20_3a_20void_34',['loadEnvironment(settings: Settings): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md355',1,'']]],
  ['settings_20extensions_20sessionid_20argv_20cwd_35',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['settings_20startupwarnings_20workspaceroot_20initializationresult_36',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['settings_20ts_37',['settings ts',['../md_packages_2cli_2src_2config_2settings_8ts.html',1,'settings.ts'],['../md_packages_2a2a-server_2src_2config_2settings_8ts.html',1,'src/config/settings.ts']]],
  ['settings_3a_20loadedsettings_20_3a_20promise_38',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['settings_3a_20record_20_3a_20boolean_39',['needsMigration(settings: Record&amp;lt;string, unknown&amp;gt;): boolean',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md350',1,'']]],
  ['settings_3a_20settings_20_3a_20promise_40',['parseArguments(settings: Settings): Promise&amp;lt;CliArgs&amp;gt;',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md282',1,'']]],
  ['settings_3a_20settings_20_3a_20void_41',['loadEnvironment(settings: Settings): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md355',1,'']]],
  ['settingscope_42',['SettingScope',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'enableExtension(name: string, scopes: SettingScope[])'],['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md346',1,'SettingScope']]],
  ['settingscope_20cwd_3a_20string_20process_20cwd_43',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['settingserror_20接口_44',['SettingsError 接口',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md72',1,'']]],
  ['settingsfile_20_3a_20void_45',['saveSettings(settingsFile: SettingsFile): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md349',1,'']]],
  ['settingsfile_3a_20settingsfile_20_3a_20void_46',['saveSettings(settingsFile: SettingsFile): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md349',1,'']]],
  ['setup_47',['Core Test Setup',['../md_packages_2core_2test-setup_8ts.html',1,'']]],
  ['setup_20ts_48',['test-setup.ts',['../md_packages_2cli_2test-setup_8ts.html',1,'']]],
  ['setupcloudshellenvironment_20envfilepath_3a_20string_20null_20_3a_20void_49',['setUpCloudShellEnvironment(envFilePath: string | null): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md357',1,'']]],
  ['setupunhandledrejectionhandler_50',['setupUnhandledRejectionHandler()',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md386',1,'']]],
  ['shell_20执行服务_20shellexecutionservice_51',['Shell 执行服务 (ShellExecutionService)',['../md_packages_2core_2src_2services_2shell_execution_service.html',1,'']]],
  ['shell_5fspecial_5fchars_52',['SHELL_SPECIAL_CHARS',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1050',1,'']]],
  ['shellexecutionresult_53',['ShellExecutionResult',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md745',1,'']]],
  ['shellexecutionservice_54',['Shell 执行服务 (ShellExecutionService)',['../md_packages_2core_2src_2services_2shell_execution_service.html',1,'']]],
  ['shelloutputevent_55',['ShellOutputEvent',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md746',1,'']]],
  ['shelltool_20类_56',['ShellTool 类',['../md_packages_2core_2src_2tools_2shell.html',1,'ShellTool 类'],['../md_packages_2core_2src_2tools_2shell.html#autotoc_md964',1,'ShellTool 类']]],
  ['shelltoolinvocation_20类_57',['ShellToolInvocation 类',['../md_packages_2core_2src_2tools_2shell.html#autotoc_md965',1,'']]],
  ['shelltoolparams_20接口_58',['ShellToolParams 接口',['../md_packages_2core_2src_2tools_2shell.html#autotoc_md963',1,'']]],
  ['shortenpath_59',['路径缩短 (shortenPath)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1052',1,'']]],
  ['shouldconfirmexecute_60',['确认函数 (shouldConfirmExecute)',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md925',1,'']]],
  ['shouldloguserprompts_61',['shouldLogUserPrompts',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md826',1,'shouldLogUserPrompts'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md812',1,'shouldLogUserPrompts()']]],
  ['shutdowntelemetry_62',['shutdownTelemetry',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md876',1,'shutdownTelemetry'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md768',1,'shutdownTelemetry()'],['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md856',1,'shutdownTelemetry()']]],
  ['simulation_63',['429 Simulation',['../md_packages_2core_2test-setup_8ts.html#autotoc_md1059',1,'']]],
  ['slashcommandevent_64',['SlashCommandEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md894',1,'']]],
  ['slashcommandstatus_65',['SlashCommandStatus',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md909',1,'']]],
  ['specific_20paths_66',['Project-Specific Paths',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md571',1,'']]],
  ['src_20agent_20executor_20ts_67',['src/agent/executor.ts',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html',1,'']]],
  ['src_20agent_20task_20ts_68',['src/agent/task.ts',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html',1,'']]],
  ['src_20config_20config_20ts_69',['src/config/config.ts',['../md_packages_2a2a-server_2src_2config_2config_8ts.html',1,'']]],
  ['src_20config_20extension_20ts_70',['src/config/extension.ts',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html',1,'']]],
  ['src_20config_20settings_20ts_71',['src/config/settings.ts',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html',1,'']]],
  ['src_20http_20app_20ts_72',['src/http/app.ts',['../md_packages_2a2a-server_2src_2http_2app_8ts.html',1,'']]],
  ['src_20http_20requeststorage_20ts_73',['src/http/requestStorage.ts',['../md_packages_2a2a-server_2src_2http_2request_storage_8ts.html',1,'']]],
  ['src_20index_20ts_74',['src/index.ts',['../md_packages_2a2a-server_2src_2index_8ts.html',1,'']]],
  ['src_20persistence_20gcs_20ts_75',['src/persistence/gcs.ts',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html',1,'']]],
  ['src_20types_20ts_76',['src/types.ts',['../md_packages_2a2a-server_2src_2types_8ts.html',1,'']]],
  ['src_20utils_20logger_20ts_77',['src/utils/logger.ts',['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html',1,'']]],
  ['sse_78',['sse',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md239',1,'']]],
  ['standardfilesystemservice_20类_79',['StandardFileSystemService 类',['../md_packages_2core_2src_2services_2file_system_service.html#autotoc_md731',1,'']]],
  ['startdir_3a_20string_20_3a_20string_20null_80',['findEnvFile(startDir: string): string | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'']]],
  ['startinteractiveui_20config_20settings_20startupwarnings_20workspaceroot_20initializationresult_81',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['startsessionevent_82',['StartSessionEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md883',1,'']]],
  ['startupwarnings_20workspaceroot_20initializationresult_83',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['static_20methods_84',['Static Methods',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md568',1,'']]],
  ['stdio（默认）_85',['stdio（默认）',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md238',1,'']]],
  ['stdioconfig_86',['StdioConfig',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md661',1,'']]],
  ['storage_20class_87',['Storage Class',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md567',1,'']]],
  ['storage_20management_88',['Storage Management',['../md_packages_2core_2src_2config_2storage_8ts.html',1,'']]],
  ['streameventtype_20枚举_89',['StreamEventType 枚举',['../md_packages_2core_2src_2core_2gemini_chat.html#autotoc_md597',1,'']]],
  ['string_90',['string',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'getNodeMemoryArgs(config: Config): string[]'],['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md385',1,'relaunchWithAdditionalArgs(additionalArgs: string[])'],['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'removeMcpServer(name: string, options: { scope: string })'],['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['string_20_3a_20extension_91',['loadExtensionsFromDir(dir: string): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'']]],
  ['string_20_3a_20extension_20null_92',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['string_20_3a_20promise_93',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['string_20_3a_20string_20null_94',['findEnvFile(startDir: string): string | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'']]],
  ['string_20config_3a_20mcpserverconfig_20_3a_20promise_95',['testMCPConnection(serverName: string, config: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'']]],
  ['string_20cwd_3a_20string_20process_20cwd_20_3a_20promise_96',['uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'']]],
  ['string_20null_97',['findEnvFile(startDir: string): string | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'']]],
  ['string_20null_20_3a_20void_98',['setUpCloudShellEnvironment(envFilePath: string | null): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md357',1,'']]],
  ['string_20options_3a_20scope_3a_20string_99',['removeMcpServer(name: string, options: { scope: string })',['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md266',1,'']]],
  ['string_20process_20cwd_100',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['string_20process_20cwd_20_3a_20extension_101',['loadExtensions(workspaceDir: string = process.cwd()): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'']]],
  ['string_20process_20cwd_20_3a_20loadedsettings_102',['loadSettings(workspaceDir: string = process.cwd()): LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'']]],
  ['string_20process_20cwd_20_3a_20promise_103',['string process cwd : Promise',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]],
  ['string_20prompt_5fid_3a_20string_20_3a_20promise_104',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['string_20scope_3a_20settingscope_20cwd_3a_20string_20process_20cwd_105',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['string_20scopes_3a_20settingscope_106',['enableExtension(name: string, scopes: SettingScope[])',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'']]],
  ['string_20server_3a_20mcpserverconfig_20_3a_20promise_107',['getServerStatus(serverName: string, server: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'']]],
  ['string_20undefined_20_3a_20dnsresolutionorder_108',['validateDnsResolutionOrder(order: string | undefined): DnsResolutionOrder',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md383',1,'']]],
  ['summarizetooloutputsettings_109',['SummarizeToolOutputSettings',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md542',1,'']]]
];
