var searchData=
[
  ['task_20类_0',['Task 类',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html#autotoc_md42',1,'']]],
  ['task_20test_20ts_1',['task.test.ts',['../md_packages_2a2a-server_2src_2agent_2task_8test_8ts.html',1,'']]],
  ['task_20ts_2',['src/agent/task.ts',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html',1,'']]],
  ['taskwrapper_20类_3',['TaskWrapper 类',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md20',1,'']]],
  ['telemetry_4',['UI Telemetry',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md799',1,'']]],
  ['telemetry_20constants_5',['Telemetry Constants',['../md_packages_2core_2src_2telemetry_2constants_8ts.html',1,'']]],
  ['telemetry_20index_6',['Telemetry Index',['../md_packages_2core_2src_2telemetry_2index_8ts.html',1,'']]],
  ['telemetry_20loggers_7',['Telemetry Loggers',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html',1,'']]],
  ['telemetry_20sdk_8',['Telemetry SDK',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html',1,'']]],
  ['telemetryinitialized_9',['telemetryInitialized',['../md_packages_2core_2src_2telemetry_2sdk.html#autotoc_md853',1,'']]],
  ['telemetrysettings_10',['TelemetrySettings',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md543',1,'']]],
  ['telemetrysettings_20接口_11',['TelemetrySettings 接口',['../md_packages_2core_2src_2config_2config.html#autotoc_md527',1,'']]],
  ['telemetrytarget_12',['TelemetryTarget',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md789',1,'']]],
  ['telemetrytarget_20枚举_13',['TelemetryTarget 枚举',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md766',1,'']]],
  ['terms_20of_20service_20and_20privacy_20notice_14',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['test_20setup_15',['Core Test Setup',['../md_packages_2core_2test-setup_8ts.html',1,'']]],
  ['test_20setup_20ts_16',['test-setup.ts',['../md_packages_2cli_2test-setup_8ts.html',1,'']]],
  ['test_20ts_17',['test ts',['../md_packages_2a2a-server_2src_2http_2app_8test_8ts.html',1,'app.test.ts'],['../md_packages_2a2a-server_2src_2http_2endpoints_8test_8ts.html',1,'endpoints.test.ts'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html',1,'gcs.test.ts'],['../md_packages_2a2a-server_2src_2agent_2task_8test_8ts.html',1,'task.test.ts']]],
  ['test_20utils_18',['测试工具 (test-utils)',['../md_packages_2core_2src_2test-utils_2index.html',1,'']]],
  ['testing_5futils_20ts_19',['testing_utils.ts',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html',1,'']]],
  ['testmcpconnection_20servername_3a_20string_20config_3a_20mcpserverconfig_20_3a_20promise_20',['testMCPConnection(serverName: string, config: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'']]],
  ['tests_21',['Running Tests',['../md_packages_2vscode-ide-companion_2development.html#autotoc_md1069',1,'']]],
  ['the_20development_20tool_20extension_22',['3. The &lt;span class=&quot;tt&quot;&gt;development-tool&lt;/span&gt; extension',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md6',1,'']]],
  ['the_20extension_23',['Running the Extension',['../md_packages_2vscode-ide-companion_2development.html#autotoc_md1068',1,'']]],
  ['thinking_20mode_24',['Thinking Mode',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md562',1,'']]],
  ['this_20package_20is_20experimental_20and_20under_20active_20development_25',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['tofriendlyerror_26',['友好错误转换 (toFriendlyError)',['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1040',1,'']]],
  ['token_20计数_27',['Token 计数',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md500',1,'']]],
  ['token_20限制管理_28',['Token 限制管理',['../md_packages_2core_2src_2core_2token_limits.html',1,'']]],
  ['tokenlimit_29',['tokenLimit()',['../md_packages_2core_2src_2core_2token_limits.html#autotoc_md621',1,'']]],
  ['tool_20discovery_30',['Tool Discovery',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md982',1,'Dynamic Tool Discovery'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md978',1,'Tool Discovery']]],
  ['tool_20extension_31',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['tool_20extension_32',['3. The &lt;span class=&quot;tt&quot;&gt;development-tool&lt;/span&gt; extension',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md6',1,'']]],
  ['tool_20management_33',['Tool Management',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md977',1,'']]],
  ['tool_20registry_34',['Tool Registry',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html',1,'']]],
  ['toolbuilder_35',['ToolBuilder',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1005',1,'']]],
  ['toolbuilder_20接口_36',['ToolBuilder 接口',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md990',1,'']]],
  ['toolcallconfirmationdetails_37',['ToolCallConfirmationDetails',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1015',1,'']]],
  ['toolcallconfirmationdetails_20类型_38',['ToolCallConfirmationDetails 类型',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md995',1,'']]],
  ['toolcallevent_39',['ToolCallEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md886',1,'']]],
  ['toolcallrecord_40',['ToolCallRecord',['../md_packages_2core_2src_2services_2chat_recording_service.html#autotoc_md717',1,'']]],
  ['toolconfirmationoutcome_41',['ToolConfirmationOutcome',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1019',1,'']]],
  ['toolconfirmationoutcome_20枚举_42',['ToolConfirmationOutcome 枚举',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md998',1,'']]],
  ['toolconfirmationpayload_43',['ToolConfirmationPayload',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1016',1,'']]],
  ['toolinvocation_44',['ToolInvocation',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1004',1,'']]],
  ['toolinvocation_20接口_45',['ToolInvocation 接口',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md989',1,'']]],
  ['toollocation_46',['ToolLocation',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1017',1,'']]],
  ['toolregistry_47',['ToolRegistry',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md976',1,'']]],
  ['toolresult_48',['ToolResult',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1006',1,'']]],
  ['toolresult_20接口_49',['ToolResult 接口',['../md_packages_2core_2src_2tools_2tools.html#autotoc_md994',1,'']]],
  ['toolresultdisplay_50',['ToolResultDisplay',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1012',1,'']]],
  ['tools_20framework_51',['Tools Framework',['../md_packages_2core_2src_2tools_2tools_8ts.html',1,'']]],
  ['tooutputstring_20extension_3a_20extension_20_3a_20string_52',['toOutputString extension: Extension : string',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['truncation_20defaults_53',['Truncation Defaults',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md551',1,'']]],
  ['ts_54',['ts',['../md_packages_2core_2src_2telemetry_2types.html',1,'遥测事件类型 (types.ts)'],['../md_packages_2core_2src_2telemetry_2loggers.html',1,'遥测日志记录器 (loggers.ts)'],['../md_packages_2core_2src_2telemetry_2sdk.html',1,'遥测 SDK (sdk.ts)'],['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html',1,'add.ts'],['../md_packages_2a2a-server_2src_2http_2app_8test_8ts.html',1,'app.test.ts'],['../md_packages_2cli_2src_2config_2auth_8ts.html',1,'auth.ts'],['../md_packages_2cli_2src_2core_2auth_8ts.html',1,'auth.ts'],['../md_packages_2cli_2src_2ui_2colors_8ts.html',1,'colors.ts'],['../md_packages_2cli_2src_2config_2config_8ts.html',1,'config.ts'],['../md_packages_2cli_2src_2ui_2constants_8ts.html',1,'constants.ts'],['../md_packages_2a2a-server_2src_2http_2endpoints_8test_8ts.html',1,'endpoints.test.ts'],['../md_packages_2cli_2src_2config_2extension_8ts.html',1,'extension.ts'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html',1,'gcs.test.ts'],['../md_packages_2a2a-server_2index_8ts.html',1,'index.ts'],['../md_packages_2cli_2index_8ts.html',1,'index.ts'],['../md_packages_2cli_2src_2core_2initializer_8ts.html',1,'initializer.ts'],['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html',1,'install.ts'],['../md_packages_2cli_2src_2config_2key_bindings_8ts.html',1,'keyBindings.ts'],['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html',1,'list.ts'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html',1,'list.ts'],['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html',1,'mcp.ts'],['../md_packages_2cli_2src_2non_interactive_cli_8ts.html',1,'nonInteractiveCli.ts'],['../md_packages_2cli_2src_2utils_2read_stdin_8ts.html',1,'readStdin.ts'],['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html',1,'remove.ts'],['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html',1,'sandboxConfig.ts'],['../md_packages_2a2a-server_2src_2http_2server_8ts.html',1,'server.ts'],['../md_packages_2cli_2src_2config_2settings_8ts.html',1,'settings.ts'],['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html',1,'src/agent/executor.ts'],['../md_packages_2a2a-server_2src_2agent_2task_8ts.html',1,'src/agent/task.ts'],['../md_packages_2a2a-server_2src_2config_2config_8ts.html',1,'src/config/config.ts'],['../md_packages_2a2a-server_2src_2config_2extension_8ts.html',1,'src/config/extension.ts'],['../md_packages_2a2a-server_2src_2config_2settings_8ts.html',1,'src/config/settings.ts'],['../md_packages_2a2a-server_2src_2http_2app_8ts.html',1,'src/http/app.ts'],['../md_packages_2a2a-server_2src_2http_2request_storage_8ts.html',1,'src/http/requestStorage.ts'],['../md_packages_2a2a-server_2src_2index_8ts.html',1,'src/index.ts'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html',1,'src/persistence/gcs.ts'],['../md_packages_2a2a-server_2src_2types_8ts.html',1,'src/types.ts'],['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html',1,'src/utils/logger.ts'],['../md_packages_2a2a-server_2src_2agent_2task_8test_8ts.html',1,'task.test.ts'],['../md_packages_2cli_2test-setup_8ts.html',1,'test-setup.ts'],['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html',1,'testing_utils.ts'],['../md_packages_2a2a-server_2vitest_8config_8ts.html',1,'vitest.config.ts'],['../md_packages_2cli_2vitest_8config_8ts.html',1,'vitest.config.ts'],['../md_packages_2core_2vitest_8config_8ts.html',1,'vitest.config.ts']]],
  ['tsx_55',['tsx',['../md_packages_2cli_2src_2ui_2_app_container_8tsx.html',1,'AppContainer.tsx'],['../md_packages_2cli_2src_2commands_2extensions_8tsx.html',1,'extensions.tsx'],['../md_packages_2cli_2src_2gemini_8tsx.html',1,'gemini.tsx']]],
  ['turn_20类和相关类型_56',['Turn 类和相关类型',['../md_packages_2core_2src_2core_2turn.html',1,'']]],
  ['turn_20类_57',['Turn 类',['../md_packages_2core_2src_2core_2turn.html#autotoc_md626',1,'']]],
  ['type_20aliases_58',['Type Aliases',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1025',1,'']]],
  ['type_20definitions_59',['Type Definitions',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md552',1,'Type Definitions'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md797',1,'Type Definitions'],['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1011',1,'Type Definitions']]],
  ['type_20guards_60',['Type Guards',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1023',1,'']]],
  ['types_61',['Event Types',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md795',1,'']]],
  ['types_20ts_62',['types ts',['../md_packages_2core_2src_2telemetry_2types.html',1,'遥测事件类型 (types.ts)'],['../md_packages_2a2a-server_2src_2types_8ts.html',1,'src/types.ts']]]
];
