var searchData=
[
  ['e2e_20测试套件_0',['E2E 测试套件',['../md_packages_2a2a-server_2src_2http_2app_8test_8ts.html#autotoc_md82',1,'']]],
  ['edittool_20类_1',['EditTool 类',['../md_packages_2core_2src_2tools_2edit.html',1,'EditTool 类'],['../md_packages_2core_2src_2tools_2edit.html#autotoc_md943',1,'EditTool 类']]],
  ['edittoolinvocation_20类_2',['EditToolInvocation 类',['../md_packages_2core_2src_2tools_2edit.html#autotoc_md944',1,'']]],
  ['edittoolparams_20接口_3',['EditToolParams 接口',['../md_packages_2core_2src_2tools_2edit.html#autotoc_md942',1,'']]],
  ['emptystreamerror_20类_4',['EmptyStreamError 类',['../md_packages_2core_2src_2core_2gemini_chat.html#autotoc_md598',1,'']]],
  ['enablecommand_5',['enableCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md206',1,'']]],
  ['enabledextensionnames_20workspacedir_20_3a_20geminicliextension_6',['annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'']]],
  ['enableextension_20name_3a_20string_20scopes_3a_20settingscope_7',['enableExtension(name: string, scopes: SettingScope[])',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md307',1,'']]],
  ['encodetagname_8',['encodeTagName()',['../md_packages_2core_2src_2core_2logger.html#autotoc_md607',1,'']]],
  ['endpoints_20test_20ts_9',['endpoints.test.ts',['../md_packages_2a2a-server_2src_2http_2endpoints_8test_8ts.html',1,'']]],
  ['endsessionevent_10',['EndSessionEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md884',1,'']]],
  ['ensurebucketinitialized_11',['&lt;span class=&quot;tt&quot;&gt;ensureBucketInitialized&lt;/span&gt;',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md129',1,'']]],
  ['enumerations_12',['Enumerations',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md535',1,'Enumerations'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md788',1,'Enumerations'],['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1018',1,'Enumerations']]],
  ['envfilepath_3a_20string_20null_20_3a_20void_13',['setUpCloudShellEnvironment(envFilePath: string | null): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md357',1,'']]],
  ['environment_20configuration_14',['Environment Configuration',['../md_packages_2core_2test-setup_8ts.html#autotoc_md1058',1,'']]],
  ['epipe_20错误_15',['EPIPE 错误',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md415',1,'']]],
  ['error_20handling_16',['Error Handling',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md985',1,'']]],
  ['escapepath_17',['特殊字符转义 (escapePath)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1054',1,'']]],
  ['event_20constants_18',['Event Constants',['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md762',1,'']]],
  ['event_20creation_20functions_19',['Event Creation Functions',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md796',1,'']]],
  ['event_20logging_20functions_20',['Event Logging Functions',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md828',1,'']]],
  ['event_20types_21',['Event Types',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md795',1,'']]],
  ['example_20interaction_20flow_22',['A. Example Interaction Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md12',1,'']]],
  ['execute_23',['execute',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md924',1,'执行函数 (execute)'],['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md32',1,'<span class="tt">execute</span>'],['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md748',1,'execute()']]],
  ['executewithpty_24',['executeWithPty()',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md749',1,'']]],
  ['executor_20ts_25',['src/agent/executor.ts',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html',1,'']]],
  ['experimental_20and_20under_20active_20development_26',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['exports_27',['Exports',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md792',1,'Exports'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md798',1,'OpenTelemetry Exports']]],
  ['exports_28',['Re-exports',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md555',1,'']]],
  ['extension_29',['Extension',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md293',1,'Extension'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'loadExtensions(workspaceDir: string = process.cwd()): Extension[]'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'loadExtensionsFromDir(dir: string): Extension[]'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md300',1,'loadUserExtensions(): Extension[]'],['../md_packages_2a2a-server_2development-extension-rfc.html',1,'RFC: Gemini CLI A2A Development-Tool Extension'],['../md_packages_2vscode-ide-companion_2development.html#autotoc_md1068',1,'Running the Extension']]],
  ['extension_30',['3. The &lt;span class=&quot;tt&quot;&gt;development-tool&lt;/span&gt; extension',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md6',1,'']]],
  ['extension_20接口_31',['Extension 接口',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md61',1,'']]],
  ['extension_20_3a_20promise_32',['performWorkspaceExtensionMigration(extensions: Extension[]): Promise&amp;lt;string[]&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md311',1,'']]],
  ['extension_20_3a_20string_33',['Extension : string',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['extension_20cwd_3a_20string_20process_20cwd_20_3a_20promise_34',['updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&amp;lt;ExtensionUpdateInfo&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'']]],
  ['extension_20name_35',['Extension Name',['../md_packages_2core_2src_2ide_2constants_8ts.html#autotoc_md639',1,'']]],
  ['extension_20null_36',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['extension_20ts_37',['extension ts',['../md_packages_2cli_2src_2config_2extension_8ts.html',1,'extension.ts'],['../md_packages_2a2a-server_2src_2config_2extension_8ts.html',1,'src/config/extension.ts']]],
  ['extension_3a_20extension_20_3a_20string_38',['extension: Extension : string',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['extension_3a_20extension_20cwd_3a_20string_20process_20cwd_20_3a_20promise_39',['updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&amp;lt;ExtensionUpdateInfo&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'']]],
  ['extensionconfig_40',['ExtensionConfig',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md294',1,'']]],
  ['extensionconfig_20接口_41',['ExtensionConfig 接口',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md62',1,'']]],
  ['extensiondir_3a_20string_20_3a_20extension_20null_42',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['extensioninstallmetadata_43',['ExtensionInstallMetadata',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md295',1,'']]],
  ['extensioninstallmetadata_20cwd_3a_20string_20process_20cwd_20_3a_20promise_44',['installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&amp;lt;string&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'']]],
  ['extensionname_3a_20string_20cwd_3a_20string_20process_20cwd_20_3a_20promise_45',['uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'']]],
  ['extensions_20enabledextensionnames_20workspacedir_20_3a_20geminicliextension_46',['annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'']]],
  ['extensions_20sessionid_20argv_20cwd_47',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['extensions_20tsx_48',['extensions.tsx',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html',1,'']]],
  ['extensions_3a_20extension_20_3a_20promise_49',['performWorkspaceExtensionMigration(extensions: Extension[]): Promise&amp;lt;string[]&amp;gt;',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md311',1,'']]],
  ['extensions_5fconfig_5ffilename_50',['EXTENSIONS_CONFIG_FILENAME',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md314',1,'']]],
  ['extensions_5fdirectory_5fname_51',['EXTENSIONS_DIRECTORY_NAME',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md313',1,'']]],
  ['extensionscommand_3a_20commandmodule_52',['extensionsCommand: CommandModule',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md199',1,'']]],
  ['extensionstorage_53',['ExtensionStorage',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md297',1,'']]]
];
