var searchData=
[
  ['main_0',['main',['../md_packages_2cli_2index_8ts.html#autotoc_md173',1,'main()'],['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md388',1,'main()']]],
  ['main_20函数_1',['main 函数',['../md_packages_2a2a-server_2src_2http_2app_8ts.html#autotoc_md92',1,'']]],
  ['makechatcompressionevent_2',['makeChatCompressionEvent()',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md913',1,'']]],
  ['makerelative_3',['相对路径计算 (makeRelative)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1053',1,'']]],
  ['makeslashcommandevent_4',['makeSlashCommandEvent()',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md912',1,'']]],
  ['malformedjsonresponseevent_5',['MalformedJsonResponseEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md903',1,'']]],
  ['management_6',['Management',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md984',1,'Process Management'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md979',1,'Schema Management'],['../md_packages_2core_2src_2config_2storage_8ts.html',1,'Storage Management'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md977',1,'Tool Management']]],
  ['mcp_20命令_7',['MCP 命令',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md185',1,'']]],
  ['mcp_20支持_8',['MCP 支持',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md191',1,'']]],
  ['mcp_20管理_9',['MCP 管理',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md194',1,'']]],
  ['mcp_20集成_10',['MCP 集成',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md709',1,'']]],
  ['mcp_20integration_11',['MCP Integration',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md980',1,'']]],
  ['mcp_20oauth_20提供者_20mcpoauthprovider_12',['MCP OAuth 提供者 (MCPOAuthProvider)',['../md_packages_2core_2src_2mcp_2oauth-provider.html',1,'']]],
  ['mcp_20server_20integration_13',['MCP Server Integration',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md983',1,'']]],
  ['mcp_20ts_14',['mcp.ts',['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html',1,'']]],
  ['mcpcommand_3a_20commandmodule_15',['mcpCommand: CommandModule',['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md257',1,'']]],
  ['mcpoauthconfig_16',['MCPOAuthConfig',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md671',1,'']]],
  ['mcpoauthprovider_17',['MCP OAuth 提供者 (MCPOAuthProvider)',['../md_packages_2core_2src_2mcp_2oauth-provider.html',1,'']]],
  ['mcpserverconfig_18',['MCPServerConfig',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md547',1,'']]],
  ['mcpserverconfig_20类_19',['MCPServerConfig 类',['../md_packages_2core_2src_2config_2config.html#autotoc_md528',1,'']]],
  ['mcpserverconfig_20_3a_20promise_20',['MCPServerConfig : Promise',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'getServerStatus(serverName: string, server: MCPServerConfig): Promise&lt;MCPServerStatus&gt;'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'testMCPConnection(serverName: string, config: MCPServerConfig): Promise&lt;MCPServerStatus&gt;']]],
  ['mergeexcludetools_21',['mergeExcludeTools()',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md288',1,'']]],
  ['mergemcpservers_22',['mergeMcpServers()',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md287',1,'']]],
  ['mergemcpservers_20函数_23',['mergeMcpServers 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md55',1,'']]],
  ['mergesettings_24',['mergeSettings()',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md354',1,'']]],
  ['messagerecord_25',['MessageRecord',['../md_packages_2core_2src_2services_2chat_recording_service.html#autotoc_md716',1,'']]],
  ['messagesendertype_20枚举_26',['MessageSenderType 枚举',['../md_packages_2core_2src_2core_2logger.html#autotoc_md604',1,'']]],
  ['method_20definitions_27',['3.3 Method Definitions',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md9',1,'']]],
  ['methods_28',['Methods',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md570',1,'Instance Methods'],['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md572',1,'Private Methods'],['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md568',1,'Static Methods']]],
  ['metric_20constants_29',['Metric Constants',['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md763',1,'']]],
  ['migratesettingstov1_20v2settings_3a_20record_20_3a_20record_30',['migrateSettingsToV1(v2Settings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt;',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md352',1,'']]],
  ['migratesettingstov2_20flatsettings_3a_20record_20_3a_20record_20null_31',['migrateSettingsToV2(flatSettings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt; | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md351',1,'']]],
  ['migration_5fmap_32',['MIGRATION_MAP',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md359',1,'']]],
  ['mocktool_20类_33',['MockTool 类',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md916',1,'']]],
  ['mocktoolinvocation_20类_34',['MockToolInvocation 类',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md918',1,'']]],
  ['mocktooloptions_20接口_35',['MockToolOptions 接口',['../md_packages_2core_2src_2test-utils_2index.html#autotoc_md917',1,'']]],
  ['mode_36',['Thinking Mode',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md562',1,'']]],
  ['model_20configuration_20constants_37',['Model Configuration Constants',['../md_packages_2core_2src_2config_2models_8ts.html',1,'']]],
  ['models_38',['Default Models',['../md_packages_2core_2src_2config_2models_8ts.html#autotoc_md557',1,'']]],
  ['motivation_39',['1.2 Motivation',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md3',1,'']]]
];
