var searchData=
[
  ['a_20example_20interaction_20flow_0',['A. Example Interaction Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md12',1,'']]],
  ['a2a_20development_20tool_20extension_1',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['a2a_20server_2',['Gemini CLI A2A Server',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md16',1,'']]],
  ['abortcontroller_3',['AbortController',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md413',1,'']]],
  ['accessibilitysettings_4',['AccessibilitySettings',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md539',1,'']]],
  ['active_20development_5',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['add_20ts_6',['add.ts',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html',1,'']]],
  ['addcommand_7',['addCommand',['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md259',1,'']]],
  ['addcommand_3a_20commandmodule_8',['addCommand: CommandModule',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md236',1,'']]],
  ['additionalargs_3a_20string_9',['relaunchWithAdditionalArgs(additionalArgs: string[])',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md385',1,'']]],
  ['addmcpserver_10',['addMcpServer()',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md235',1,'']]],
  ['agent_20executor_20ts_11',['src/agent/executor.ts',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html',1,'']]],
  ['agent_20task_20ts_12',['src/agent/task.ts',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html',1,'']]],
  ['agentsettings_20接口_13',['AgentSettings 接口',['../md_packages_2a2a-server_2src_2types_8ts.html#autotoc_md145',1,'']]],
  ['aliases_14',['Type Aliases',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1025',1,'']]],
  ['all_20code_20in_20this_20package_20is_20experimental_20and_20under_20active_20development_15',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['allowedmcpservers_16',['allowedMcpServers()',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md286',1,'']]],
  ['and_20file_20names_17',['Directory and File Names',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md566',1,'']]],
  ['and_20notifications_18',['2.1 Asynchronous Responses and Notifications',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md5',1,'']]],
  ['and_20privacy_20notice_19',['Terms of Service and Privacy Notice',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1073',1,'']]],
  ['and_20under_20active_20development_20',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['annotateactiveextensions_20extensions_20enabledextensionnames_20workspacedir_20_3a_20geminicliextension_21',['annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'']]],
  ['ansi_20转义序列处理_22',['ANSI 转义序列处理',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md753',1,'']]],
  ['anydeclarativetool_23',['AnyDeclarativeTool',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1027',1,'']]],
  ['anytoolinvocation_24',['AnyToolInvocation',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1026',1,'']]],
  ['api_20方法_25',['API 方法',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md496',1,'']]],
  ['apierrorevent_26',['ApiErrorEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md888',1,'']]],
  ['apirequestevent_27',['ApiRequestEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md887',1,'']]],
  ['apiresponseevent_28',['ApiResponseEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md889',1,'']]],
  ['app_20test_20ts_29',['app.test.ts',['../md_packages_2a2a-server_2src_2http_2app_8test_8ts.html',1,'']]],
  ['app_20ts_30',['src/http/app.ts',['../md_packages_2a2a-server_2src_2http_2app_8ts.html',1,'']]],
  ['appcontainer_20tsx_31',['AppContainer.tsx',['../md_packages_2cli_2src_2ui_2_app_container_8tsx.html',1,'']]],
  ['appendix_32',['Appendix',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md11',1,'']]],
  ['approvalmode_33',['ApprovalMode',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md536',1,'']]],
  ['approvalmode_20枚举_34',['ApprovalMode 枚举',['../md_packages_2core_2src_2config_2config.html#autotoc_md526',1,'']]],
  ['args_3a_20installargs_35',['handleInstall(args: InstallArgs)',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md215',1,'']]],
  ['argv_20cwd_36',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['asserttaskcreationandworkingstatus_37',['assertTaskCreationAndWorkingStatus',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html#autotoc_md159',1,'']]],
  ['assertuniquefinaleventislast_38',['assertUniqueFinalEventIsLast',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html#autotoc_md158',1,'']]],
  ['asynchronous_20responses_20and_20notifications_39',['2.1 Asynchronous Responses and Notifications',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md5',1,'']]],
  ['auth_20ts_40',['auth ts',['../md_packages_2cli_2src_2config_2auth_8ts.html',1,'auth.ts'],['../md_packages_2cli_2src_2core_2auth_8ts.html',1,'auth.ts']]],
  ['authenticate_41',['authenticate()',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md673',1,'']]],
  ['authprovidertype_42',['AuthProviderType',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md537',1,'']]],
  ['authprovidertype_20枚举_43',['AuthProviderType 枚举',['../md_packages_2core_2src_2config_2config.html#autotoc_md530',1,'']]],
  ['authtype_20枚举_44',['AuthType 枚举',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md585',1,'']]],
  ['authtype_20undefined_20_3a_20promise_45',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['authtype_3a_20authtype_20undefined_20_3a_20promise_46',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]]
];
