var searchData=
[
  ['canceltask_0',['&lt;span class=&quot;tt&quot;&gt;cancelTask&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md31',1,'']]],
  ['chatcompressionevent_1',['ChatCompressionEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md895',1,'']]],
  ['chatcompressioninfo_20接口_2',['ChatCompressionInfo 接口',['../md_packages_2core_2src_2core_2turn.html#autotoc_md635',1,'']]],
  ['chatcompressionsettings_3',['ChatCompressionSettings',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md541',1,'']]],
  ['chatrecordingservice_4',['聊天记录服务 (ChatRecordingService)',['../md_packages_2core_2src_2services_2chat_recording_service.html',1,'']]],
  ['checkpointingsettings_20接口_5',['CheckpointingSettings 接口',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md73',1,'']]],
  ['childprocessfallback_6',['childProcessFallback()',['../md_packages_2core_2src_2services_2shell_execution_service.html#autotoc_md750',1,'']]],
  ['class_7',['Storage Class',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md567',1,'']]],
  ['classes_8',['Classes',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1007',1,'Base Classes'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md546',1,'Classes'],['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md973',1,'Core Classes']]],
  ['clear_9',['clear()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md700',1,'']]],
  ['clearcut_20集成_10',['Clearcut 集成',['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md819',1,'']]],
  ['clearcutlogger_11',['ClearcutLogger',['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md785',1,'']]],
  ['cli_20代码说明文档索引_12',['Gemini CLI 代码说明文档索引',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md175',1,'']]],
  ['cli_20a2a_20development_20tool_20extension_13',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['cli_20a2a_20server_14',['Gemini CLI A2A Server',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md16',1,'']]],
  ['cli_20companion_15',['Gemini CLI Companion',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1070',1,'']]],
  ['cliargs_16',['CliArgs',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md280',1,'']]],
  ['closediff_17',['closeDiff()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md650',1,'']]],
  ['code_20in_20this_20package_20is_20experimental_20and_20under_20active_20development_18',['All code in this package is experimental and under active development',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md17',1,'']]],
  ['codeassist_19',['代码辅助功能 (codeAssist)',['../md_packages_2core_2src_2code__assist_2code_assist.html',1,'']]],
  ['codeassistserver_20类_20',['CodeAssistServer 类',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md490',1,'']]],
  ['coderagentcard_20对象_21',['coderAgentCard 对象',['../md_packages_2a2a-server_2src_2http_2app_8ts.html#autotoc_md89',1,'']]],
  ['coderagentevent_20枚举_22',['CoderAgentEvent 枚举',['../md_packages_2a2a-server_2src_2types_8ts.html#autotoc_md144',1,'']]],
  ['coderagentexecutor_20类_23',['CoderAgentExecutor 类',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md23',1,'']]],
  ['colors_24',['Colors',['../md_packages_2cli_2src_2ui_2colors_8ts.html#autotoc_md445',1,'']]],
  ['colors_20ts_25',['colors.ts',['../md_packages_2cli_2src_2ui_2colors_8ts.html',1,'']]],
  ['command_26',['Command',['../md_packages_2cli_2src_2config_2key_bindings_8ts.html#autotoc_md320',1,'']]],
  ['commandmodule_27',['CommandModule',['../md_packages_2cli_2src_2commands_2mcp_2add_8ts.html#autotoc_md236',1,'addCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md199',1,'extensionsCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md216',1,'installCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md227',1,'listCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md249',1,'listCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md257',1,'mcpCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2mcp_2remove_8ts.html#autotoc_md267',1,'removeCommand: CommandModule']]],
  ['communication_20flow_28',['2. Communication Flow',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md4',1,'']]],
  ['companion_29',['Gemini CLI Companion',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1070',1,'']]],
  ['compressionstatus_20枚举_30',['CompressionStatus 枚举',['../md_packages_2core_2src_2core_2turn.html#autotoc_md634',1,'']]],
  ['concerns_31',['4. Separation of Concerns',['../md_packages_2a2a-server_2development-extension-rfc.html#autotoc_md10',1,'']]],
  ['config_32',['Config',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md548',1,'']]],
  ['config_20类_33',['Config 类',['../md_packages_2core_2src_2config_2config.html',1,'']]],
  ['config_20_3a_20string_34',['getNodeMemoryArgs(config: Config): string[]',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'']]],
  ['config_20authtype_3a_20authtype_20undefined_20_3a_20promise_35',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['config_20config_20ts_36',['src/config/config.ts',['../md_packages_2a2a-server_2src_2config_2config_8ts.html',1,'']]],
  ['config_20extension_20ts_37',['src/config/extension.ts',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html',1,'']]],
  ['config_20input_3a_20string_20prompt_5fid_3a_20string_20_3a_20promise_38',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['config_20settings_20startupwarnings_20workspaceroot_20initializationresult_39',['startInteractiveUI(config, settings, startupWarnings, workspaceRoot, initializationResult)',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md387',1,'']]],
  ['config_20settings_20ts_40',['src/config/settings.ts',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html',1,'']]],
  ['config_20settings_3a_20loadedsettings_20_3a_20promise_41',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['config_20ts_42',['config ts',['../md_packages_2cli_2src_2config_2config_8ts.html',1,'config.ts'],['../md_packages_2a2a-server_2src_2config_2config_8ts.html',1,'src/config/config.ts'],['../md_packages_2a2a-server_2vitest_8config_8ts.html',1,'vitest.config.ts'],['../md_packages_2cli_2vitest_8config_8ts.html',1,'vitest.config.ts'],['../md_packages_2core_2vitest_8config_8ts.html',1,'vitest.config.ts']]],
  ['config_3a_20config_20_3a_20string_43',['getNodeMemoryArgs(config: Config): string[]',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'']]],
  ['config_3a_20config_20authtype_3a_20authtype_20undefined_20_3a_20promise_44',['performInitialAuth(config: Config, authType: AuthType | undefined): Promise&amp;lt;string | null&amp;gt;',['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'']]],
  ['config_3a_20config_20input_3a_20string_20prompt_5fid_3a_20string_20_3a_20promise_45',['runNonInteractive(config: Config, input: string, prompt_id: string): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'']]],
  ['config_3a_20config_20settings_3a_20loadedsettings_20_3a_20promise_46',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['config_3a_20mcpserverconfig_20_3a_20promise_47',['testMCPConnection(serverName: string, config: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'']]],
  ['configuration_48',['Configuration',['../md_packages_2core_2src_2config_2config_8ts.html',1,'Core Configuration'],['../md_packages_2core_2test-setup_8ts.html#autotoc_md1058',1,'Environment Configuration']]],
  ['configuration_20constants_49',['Model Configuration Constants',['../md_packages_2core_2src_2config_2models_8ts.html',1,'']]],
  ['connect_50',['connect()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md648',1,'']]],
  ['consolepatcher_51',['ConsolePatcher',['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md411',1,'']]],
  ['constants_52',['Constants',['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md549',1,'Constants'],['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md565',1,'Constants'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md790',1,'Constants'],['../md_packages_2core_2src_2tools_2diff_options_8ts.html#autotoc_md935',1,'Constants'],['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md762',1,'Event Constants'],['../md_packages_2core_2src_2ide_2constants_8ts.html',1,'IDE Constants'],['../md_packages_2core_2src_2telemetry_2constants_8ts.html#autotoc_md763',1,'Metric Constants'],['../md_packages_2core_2src_2config_2models_8ts.html',1,'Model Configuration Constants'],['../md_packages_2core_2src_2telemetry_2constants_8ts.html',1,'Telemetry Constants']]],
  ['constants_20ts_53',['constants.ts',['../md_packages_2cli_2src_2ui_2constants_8ts.html',1,'']]],
  ['contentgenerator_20接口和相关实现_54',['ContentGenerator 接口和相关实现',['../md_packages_2core_2src_2core_2content_generator.html',1,'']]],
  ['contentgenerator_20接口_55',['ContentGenerator 接口',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md583',1,'']]],
  ['contentgeneratorconfig_20类型_56',['ContentGeneratorConfig 类型',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md586',1,'']]],
  ['contentretryevent_57',['ContentRetryEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md905',1,'']]],
  ['contentretryfailureevent_58',['ContentRetryFailureEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md906',1,'']]],
  ['conversationfinishedevent_59',['ConversationFinishedEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md900',1,'']]],
  ['conversationrecord_60',['ConversationRecord',['../md_packages_2core_2src_2services_2chat_recording_service.html#autotoc_md715',1,'']]],
  ['core_20classes_61',['Core Classes',['../md_packages_2core_2src_2tools_2tool-registry_8ts.html#autotoc_md973',1,'']]],
  ['core_20configuration_62',['Core Configuration',['../md_packages_2core_2src_2config_2config_8ts.html',1,'']]],
  ['core_20interfaces_63',['Core Interfaces',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1003',1,'']]],
  ['core_20test_20setup_64',['Core Test Setup',['../md_packages_2core_2test-setup_8ts.html',1,'']]],
  ['create_65',['&lt;span class=&quot;tt&quot;&gt;create&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html#autotoc_md45',1,'']]],
  ['createapp_20函数_66',['createApp 函数',['../md_packages_2a2a-server_2src_2http_2app_8ts.html#autotoc_md91',1,'']]],
  ['createcodeassistcontentgenerator_67',['createCodeAssistContentGenerator()',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md487',1,'']]],
  ['createcontentgenerator_68',['createContentGenerator()',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md589',1,'']]],
  ['createcontentgeneratorconfig_69',['createContentGeneratorConfig()',['../md_packages_2core_2src_2core_2content_generator.html#autotoc_md588',1,'']]],
  ['createmockconfig_70',['createMockConfig',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html#autotoc_md156',1,'']]],
  ['createstreammessagerequest_71',['createStreamMessageRequest',['../md_packages_2a2a-server_2src_2utils_2testing__utils_8ts.html#autotoc_md157',1,'']]],
  ['createtask_72',['&lt;span class=&quot;tt&quot;&gt;createTask&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md28',1,'']]],
  ['creation_20functions_73',['Event Creation Functions',['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md796',1,'']]],
  ['csrf_20保护_74',['CSRF 保护',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md690',1,'']]],
  ['cwd_75',['cwd',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())'],['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'loadCliConfig(settings, extensions, sessionId, argv, cwd)']]],
  ['cwd_20_3a_20extension_76',['loadExtensions(workspaceDir: string = process.cwd()): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'']]],
  ['cwd_20_3a_20loadedsettings_77',['loadSettings(workspaceDir: string = process.cwd()): LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'']]],
  ['cwd_20_3a_20promise_78',['cwd : Promise',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]],
  ['cwd_3a_20string_20process_20cwd_79',['disableExtension(name: string, scope: SettingScope, cwd: string = process.cwd())',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md306',1,'']]],
  ['cwd_3a_20string_20process_20cwd_20_3a_20promise_80',['cwd: string process cwd : Promise',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]]
];
