var searchData=
[
  ['_3a_20boolean_0',['needsMigration(settings: Record&amp;lt;string, unknown&amp;gt;): boolean',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md350',1,'']]],
  ['_3a_20dnsresolutionorder_1',['validateDnsResolutionOrder(order: string | undefined): DnsResolutionOrder',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md383',1,'']]],
  ['_3a_20extension_2',[': Extension',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'loadExtensions(workspaceDir: string = process.cwd()): Extension[]'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'loadExtensionsFromDir(dir: string): Extension[]'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md300',1,'loadUserExtensions(): Extension[]']]],
  ['_3a_20extension_20null_3',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['_3a_20geminicliextension_4',['annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'']]],
  ['_3a_20loadedsettings_5',['loadSettings(workspaceDir: string = process.cwd()): LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'']]],
  ['_3a_20promise_6',[': Promise',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'getServerStatus(serverName: string, server: MCPServerConfig): Promise&lt;MCPServerStatus&gt;'],['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'initializeApp(config: Config, settings: LoadedSettings): Promise&lt;InitializationResult&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md303',1,'installExtension(installMetadata: ExtensionInstallMetadata, cwd: string = process.cwd()): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md248',1,'listMcpServers(): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md282',1,'parseArguments(settings: Settings): Promise&lt;CliArgs&gt;'],['../md_packages_2cli_2src_2core_2auth_8ts.html#autotoc_md366',1,'performInitialAuth(config: Config, authType: AuthType | undefined): Promise&lt;string | null&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md311',1,'performWorkspaceExtensionMigration(extensions: Extension[]): Promise&lt;string[]&gt;'],['../md_packages_2cli_2src_2utils_2read_stdin_8ts.html#autotoc_md461',1,'readStdin(): Promise&lt;string&gt;'],['../md_packages_2cli_2src_2non_interactive_cli_8ts.html#autotoc_md395',1,'runNonInteractive(config: Config, input: string, prompt_id: string): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md246',1,'testMCPConnection(serverName: string, config: MCPServerConfig): Promise&lt;MCPServerStatus&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md304',1,'uninstallExtension(extensionName: string, cwd: string = process.cwd()): Promise&lt;void&gt;'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md305',1,'updateExtension(extension: Extension, cwd: string = process.cwd()): Promise&lt;ExtensionUpdateInfo&gt;']]],
  ['_3a_20record_7',['migrateSettingsToV1(v2Settings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt;',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md352',1,'']]],
  ['_3a_20record_20null_8',['migrateSettingsToV2(flatSettings: Record&amp;lt;string, unknown&amp;gt;): Record&amp;lt;string, unknown&amp;gt; | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md351',1,'']]],
  ['_3a_20string_9',[': string',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'getNodeMemoryArgs(config: Config): string[]'],['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md229',1,'toOutputString(extension: Extension): string'],['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md310',1,'toOutputString(extension: Extension): string']]],
  ['_3a_20string_20null_10',['findEnvFile(startDir: string): string | null',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md356',1,'']]],
  ['_3a_20void_11',[': void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md355',1,'loadEnvironment(settings: Settings): void'],['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md349',1,'saveSettings(settingsFile: SettingsFile): void'],['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md357',1,'setUpCloudShellEnvironment(envFilePath: string | null): void']]]
];
