var searchData=
[
  ['library_20screen_20reader_20guidance_0',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]],
  ['linkcommand_1',['linkCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md207',1,'']]],
  ['list_20ts_2',['list ts',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html',1,'list.ts'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html',1,'list.ts']]],
  ['listcommand_3',['listCommand',['../md_packages_2cli_2src_2commands_2extensions_8tsx.html#autotoc_md203',1,'listCommand'],['../md_packages_2cli_2src_2commands_2mcp_2mcp_8ts.html#autotoc_md261',1,'listCommand']]],
  ['listcommand_3a_20commandmodule_4',['listCommand: CommandModule',['../md_packages_2cli_2src_2commands_2extensions_2list_8ts.html#autotoc_md227',1,'listCommand: CommandModule'],['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md249',1,'listCommand: CommandModule']]],
  ['listmcpservers_20_3a_20promise_5',['listMcpServers(): Promise&amp;lt;void&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md248',1,'']]],
  ['load_6',['load',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md132',1,'<span class="tt">load</span>'],['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md137',1,'<span class="tt">load</span>']]],
  ['loadcliconfig_20settings_20extensions_20sessionid_20argv_20cwd_7',['loadCliConfig(settings, extensions, sessionId, argv, cwd)',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md284',1,'']]],
  ['loadconfig_20函数_8',['loadConfig 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md54',1,'']]],
  ['loadedsettings_9',['LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md345',1,'LoadedSettings'],['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'loadSettings(workspaceDir: string = process.cwd()): LoadedSettings']]],
  ['loadedsettings_20_3a_20promise_10',['initializeApp(config: Config, settings: LoadedSettings): Promise&amp;lt;InitializationResult&amp;gt;',['../md_packages_2cli_2src_2core_2initializer_8ts.html#autotoc_md376',1,'']]],
  ['loadenvironment_20函数_11',['loadEnvironment 函数',['../md_packages_2a2a-server_2src_2config_2config_8ts.html#autotoc_md57',1,'']]],
  ['loadenvironment_20settings_3a_20settings_20_3a_20void_12',['loadEnvironment(settings: Settings): void',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md355',1,'']]],
  ['loadextension_20函数_13',['loadExtension 函数',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md66',1,'']]],
  ['loadextension_20extensiondir_3a_20string_20_3a_20extension_20null_14',['loadExtension(extensionDir: string): Extension | null',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md302',1,'']]],
  ['loadextensions_20函数_15',['loadExtensions 函数',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md64',1,'']]],
  ['loadextensions_20workspacedir_3a_20string_20process_20cwd_20_3a_20extension_16',['loadExtensions(workspaceDir: string = process.cwd()): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md299',1,'']]],
  ['loadextensionsfromdir_20函数_17',['loadExtensionsFromDir 函数',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md65',1,'']]],
  ['loadextensionsfromdir_20dir_3a_20string_20_3a_20extension_18',['loadExtensionsFromDir(dir: string): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md301',1,'']]],
  ['loadhierarchicalgeminimemory_19',['loadHierarchicalGeminiMemory()',['../md_packages_2cli_2src_2config_2config_8ts.html#autotoc_md283',1,'']]],
  ['loadsandboxconfig_20',['loadSandboxConfig',['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html#autotoc_md332',1,'']]],
  ['loadsettings_20函数_21',['loadSettings 函数',['../md_packages_2a2a-server_2src_2config_2settings_8ts.html#autotoc_md75',1,'']]],
  ['loadsettings_20workspacedir_3a_20string_20process_20cwd_20_3a_20loadedsettings_22',['loadSettings(workspaceDir: string = process.cwd()): LoadedSettings',['../md_packages_2cli_2src_2config_2settings_8ts.html#autotoc_md348',1,'']]],
  ['loaduserextensions_20_3a_20extension_23',['loadUserExtensions(): Extension[]',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md300',1,'']]],
  ['local_20development_24',['Local Development',['../md_packages_2vscode-ide-companion_2development.html',1,'']]],
  ['logapierror_25',['logApiError',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md835',1,'logApiError'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md774',1,'logApiError()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md808',1,'logApiError()']]],
  ['logapirequest_26',['logApiRequest',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md833',1,'logApiRequest'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md773',1,'logApiRequest()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md807',1,'logApiRequest()']]],
  ['logapiresponse_27',['logApiResponse',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md836',1,'logApiResponse'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md775',1,'logApiResponse()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md809',1,'logApiResponse()']]],
  ['logchatcompression_28',['logChatCompression',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md842',1,'']]],
  ['logcliconfiguration_29',['logCliConfiguration',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md829',1,'logCliConfiguration'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md770',1,'logCliConfiguration()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md803',1,'logCliConfiguration()']]],
  ['logcontentretry_30',['logContentRetry',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md846',1,'']]],
  ['logcontentretryfailure_31',['logContentRetryFailure',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md847',1,'']]],
  ['logconversationfinishedevent_32',['logConversationFinishedEvent',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md841',1,'']]],
  ['logentry_20接口_33',['LogEntry 接口',['../md_packages_2core_2src_2core_2logger.html#autotoc_md605',1,'']]],
  ['logfileoperation_34',['logFileOperation',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md832',1,'logFileOperation'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md806',1,'logFileOperation()']]],
  ['logflashfallback_35',['logFlashFallback',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md834',1,'']]],
  ['logger_20对象_36',['logger 对象',['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html#autotoc_md151',1,'']]],
  ['logger_20类_37',['Logger 类',['../md_packages_2core_2src_2core_2logger.html',1,'']]],
  ['logger_20ts_38',['src/utils/logger.ts',['../md_packages_2a2a-server_2src_2utils_2logger_8ts.html',1,'']]],
  ['loggers_39',['Telemetry Loggers',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html',1,'']]],
  ['loggers_20ts_40',['遥测日志记录器 (loggers.ts)',['../md_packages_2core_2src_2telemetry_2loggers.html',1,'']]],
  ['logging_20functions_41',['Logging Functions',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md828',1,'Event Logging Functions'],['../md_packages_2core_2src_2telemetry_2index_8ts.html#autotoc_md794',1,'Logging Functions']]],
  ['logideconnection_42',['logIdeConnection',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md840',1,'']]],
  ['loginvalidchunk_43',['logInvalidChunk',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md845',1,'']]],
  ['logkittysequenceoverflow_44',['logKittySequenceOverflow',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md843',1,'']]],
  ['logloopdetected_45',['logLoopDetected',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md837',1,'']]],
  ['logmalformedjsonresponse_46',['logMalformedJsonResponse',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md844',1,'']]],
  ['lognextspeakercheck_47',['logNextSpeakerCheck',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md838',1,'']]],
  ['logslashcommand_48',['logSlashCommand',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md839',1,'']]],
  ['logtoolcall_49',['logToolCall',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md831',1,'logToolCall'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md772',1,'logToolCall()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md805',1,'logToolCall()']]],
  ['loguserprompt_50',['logUserPrompt',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md830',1,'logUserPrompt'],['../md_packages_2core_2src_2telemetry_2index.html#autotoc_md771',1,'logUserPrompt()'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md804',1,'logUserPrompt()']]],
  ['loopdetectedevent_51',['LoopDetectedEvent',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md892',1,'']]],
  ['looptype_52',['LoopType',['../md_packages_2core_2src_2telemetry_2types.html#autotoc_md908',1,'']]]
];
