var searchData=
[
  ['gcs_20test_20ts_0',['gcs.test.ts',['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html',1,'']]],
  ['gcs_20ts_1',['src/persistence/gcs.ts',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html',1,'']]],
  ['gcstaskstore_20测试套件_2',['GCSTaskStore 测试套件',['../md_packages_2a2a-server_2src_2persistence_2gcs_8test_8ts.html#autotoc_md118',1,'']]],
  ['gcstaskstore_20类_3',['GCSTaskStore 类',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md125',1,'']]],
  ['gemini_20cli_20代码说明文档索引_4',['Gemini CLI 代码说明文档索引',['../D:/大学文件/大学学习/技术/AI-CLI/packages/cli/README.md#autotoc_md175',1,'']]],
  ['gemini_20cli_20a2a_20development_20tool_20extension_5',['RFC: Gemini CLI A2A Development-Tool Extension',['../md_packages_2a2a-server_2development-extension-rfc.html',1,'']]],
  ['gemini_20cli_20a2a_20server_6',['Gemini CLI A2A Server',['../D:/大学文件/大学学习/技术/AI-CLI/packages/a2a-server/README.md#autotoc_md16',1,'']]],
  ['gemini_20cli_20companion_7',['Gemini CLI Companion',['../D:/大学文件/大学学习/技术/AI-CLI/packages/vscode-ide-companion/README.md#autotoc_md1070',1,'']]],
  ['gemini_20tsx_8',['gemini.tsx',['../md_packages_2cli_2src_2gemini_8tsx.html',1,'']]],
  ['gemini_5fcli_5fcompanion_5fextension_5fname_9',['GEMINI_CLI_COMPANION_EXTENSION_NAME',['../md_packages_2core_2src_2ide_2constants_8ts.html#autotoc_md640',1,'']]],
  ['gemini_5fdir_10',['GEMINI_DIR',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1048',1,'']]],
  ['geminichat_20类_11',['GeminiChat 类',['../md_packages_2core_2src_2core_2gemini_chat.html',1,'']]],
  ['geminiclient_20类_12',['GeminiClient 类',['../md_packages_2core_2src_2core_2client.html',1,'']]],
  ['geminicliextension_13',['GeminiCLIExtension',['../md_packages_2cli_2src_2config_2extension_8ts.html#autotoc_md309',1,'annotateActiveExtensions(extensions, enabledExtensionNames, workspaceDir): GeminiCLIExtension[]'],['../md_packages_2core_2src_2config_2config_8ts.html#autotoc_md554',1,'GeminiCLIExtension']]],
  ['geminieventtype_20枚举_14',['GeminiEventType 枚举',['../md_packages_2core_2src_2core_2turn.html#autotoc_md631',1,'']]],
  ['general_20principles_15',['General Principles',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html#autotoc_md211',1,'']]],
  ['getallprompts_16',['getAllPrompts()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md697',1,'']]],
  ['getalltasks_17',['&lt;span class=&quot;tt&quot;&gt;getAllTasks&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md30',1,'']]],
  ['getcitations_18',['getCitations()',['../md_packages_2core_2src_2core_2turn.html#autotoc_md637',1,'']]],
  ['getcodeassistserver_19',['getCodeAssistServer()',['../md_packages_2core_2src_2code__assist_2code_assist.html#autotoc_md488',1,'']]],
  ['getcommonattributes_20',['getCommonAttributes',['../md_packages_2core_2src_2telemetry_2loggers_8ts.html#autotoc_md827',1,'getCommonAttributes'],['../md_packages_2core_2src_2telemetry_2loggers.html#autotoc_md811',1,'getCommonAttributes()']]],
  ['getcompressionprompt_21',['getCompressionPrompt()',['../md_packages_2core_2src_2core_2prompts.html#autotoc_md612',1,'']]],
  ['getconfig_22',['&lt;span class=&quot;tt&quot;&gt;getConfig&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md26',1,'']]],
  ['getcontextfilenames_20函数_23',['getContextFileNames 函数',['../md_packages_2a2a-server_2src_2config_2extension_8ts.html#autotoc_md67',1,'']]],
  ['getcoresystemprompt_24',['getCoreSystemPrompt()',['../md_packages_2core_2src_2core_2prompts.html#autotoc_md611',1,'']]],
  ['getdiffstat_25',['getDiffStat',['../md_packages_2core_2src_2tools_2diff_options_8ts.html#autotoc_md938',1,'']]],
  ['geterrormessage_26',['错误消息提取 (getErrorMessage)',['../md_packages_2core_2src_2utils_2errors.html#autotoc_md1039',1,'']]],
  ['getinstance_27',['getInstance()',['../md_packages_2core_2src_2ide_2ide-client.html#autotoc_md647',1,'']]],
  ['getmcpserversfromconfig_28',['getMcpServersFromConfig()',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md245',1,'']]],
  ['getmetadata_29',['&lt;span class=&quot;tt&quot;&gt;getMetadata&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2task_8ts.html#autotoc_md47',1,'']]],
  ['getnodememoryargs_20config_3a_20config_20_3a_20string_30',['getNodeMemoryArgs(config: Config): string[]',['../md_packages_2cli_2src_2gemini_8tsx.html#autotoc_md384',1,'']]],
  ['getobjectpath_31',['&lt;span class=&quot;tt&quot;&gt;getObjectPath&lt;/span&gt;',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md130',1,'']]],
  ['getprojecthash_32',['项目哈希 (getProjectHash)',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1055',1,'']]],
  ['getprompt_33',['getPrompt()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md698',1,'']]],
  ['getpromptsbyserver_34',['getPromptsByServer()',['../md_packages_2core_2src_2prompts_2prompt-registry.html#autotoc_md699',1,'']]],
  ['getsandboxcommand_20内部函数_35',['getSandboxCommand (内部函数)',['../md_packages_2cli_2src_2config_2sandbox_config_8ts.html#autotoc_md333',1,'']]],
  ['getserverstatus_20servername_3a_20string_20server_3a_20mcpserverconfig_20_3a_20promise_36',['getServerStatus(serverName: string, server: MCPServerConfig): Promise&amp;lt;MCPServerStatus&amp;gt;',['../md_packages_2cli_2src_2commands_2mcp_2list_8ts.html#autotoc_md247',1,'']]],
  ['gettask_37',['&lt;span class=&quot;tt&quot;&gt;getTask&lt;/span&gt;',['../md_packages_2a2a-server_2src_2agent_2executor_8ts.html#autotoc_md29',1,'']]],
  ['gettmparchivefilename_20函数_38',['getTmpArchiveFilename 函数',['../md_packages_2a2a-server_2src_2persistence_2gcs_8ts.html#autotoc_md141',1,'']]],
  ['getvalidtoken_39',['getValidToken()',['../md_packages_2core_2src_2mcp_2oauth-provider.html#autotoc_md674',1,'']]],
  ['git_20仓库_40',['Git 仓库',['../md_packages_2cli_2src_2commands_2extensions_2install_8ts.html#autotoc_md218',1,'']]],
  ['global_20directory_20paths_41',['Global Directory Paths',['../md_packages_2core_2src_2config_2storage_8ts.html#autotoc_md569',1,'']]],
  ['global_20variables_42',['Global Variables',['../md_packages_2core_2src_2telemetry_2sdk_8ts.html#autotoc_md871',1,'']]],
  ['google_5faccounts_5ffilename_43',['GOOGLE_ACCOUNTS_FILENAME',['../md_packages_2core_2src_2utils_2paths.html#autotoc_md1049',1,'']]],
  ['guards_44',['Type Guards',['../md_packages_2core_2src_2tools_2tools_8ts.html#autotoc_md1023',1,'']]],
  ['guidance_45',['Ink Library Screen Reader Guidance',['../md_packages_2cli_2src_2commands_2extensions_2examples_2context_2_g_e_m_i_n_i.html',1,'']]]
];
